import type { AssetEntry, AssetKind } from "../engine/types";
import { appPathname } from "../pwa/basePath";
import { storyAssetIds } from "./assets";

interface ArtAssetSpec {
  readonly id: string;
  readonly kind: AssetKind;
  readonly path: string;
  readonly width: number;
  readonly height: number;
  readonly focalPoint: AssetEntry["focalPoint"];
  readonly preloadGroup: string;
  readonly alt: string;
  readonly promptReference: string;
}

const generatedProvenance = (promptReference: string) => ({
  creator: "OpenAI image generation",
  promptReference,
  license: "All rights reserved; generated for Return to Me",
});

const background = (
  id: string,
  group: string,
  alt: string,
  focalPoint: AssetEntry["focalPoint"] = { x: 0.5, y: 0.5 },
): ArtAssetSpec => ({
  id,
  kind: "background",
  path: `assets/art/backgrounds/${id}.webp`,
  width: 1600,
  height: 900,
  focalPoint,
  preloadGroup: group,
  alt,
  promptReference: `art/prompts/provenance.md#${id}`,
});

const cg = (
  id: string,
  group: string,
  alt: string,
  focalPoint: AssetEntry["focalPoint"] = { x: 0.5, y: 0.5 },
): ArtAssetSpec => ({
  id,
  kind: "cg",
  path: `assets/art/cg/${id}.webp`,
  width: 1600,
  height: 900,
  focalPoint,
  preloadGroup: group,
  alt,
  promptReference: `art/prompts/provenance.md#${id}`,
});

const sprite = (
  id: string,
  directory: string,
  filename: string,
  width: number,
  height: number,
  group: string,
  alt: string,
  focalPoint: AssetEntry["focalPoint"],
): ArtAssetSpec => ({
  id,
  kind: "sprite",
  path: `assets/art/characters/${directory}/${filename}.webp`,
  width,
  height,
  focalPoint,
  preloadGroup: group,
  alt,
  promptReference: `art/prompts/provenance.md#${directory}`,
});

const ART_SPECS = [
  background(
    "bg-primary-classroom",
    "chapter-1",
    "A warm Singapore primary-school classroom with light-blue accents.",
  ),
  background(
    "bg-primary-corridor",
    "chapter-1",
    "A sunlit primary-school corridor overlooking a courtyard.",
    { x: 0.52, y: 0.46 },
  ),
  background(
    "bg-primary-canteen",
    "chapter-1",
    "A warm, unbranded Singapore primary-school canteen prepared for everyday memories.",
    { x: 0.52, y: 0.44 },
  ),
  background(
    "bg-graduation-gate",
    "chapter-1",
    "An unnamed primary-school gate decorated for graduation.",
    { x: 0.5, y: 0.42 },
  ),
  background(
    "bg-bus-stop",
    "chapter-1",
    "A quiet Singapore bus stop suggesting two diverging school journeys.",
    { x: 0.55, y: 0.5 },
  ),
  background(
    "bg-bedroom-2009",
    "chapter-1",
    "A modest 2009 bedroom lit by the cool glow of a mobile phone.",
    { x: 0.62, y: 0.48 },
  ),
  background(
    "bg-bedroom-2009-warm",
    "chapter-1",
    "Aleem's modest 2009 bedroom in warm evening light, before the messages become less frequent.",
    { x: 0.62, y: 0.48 },
  ),
  background(
    "bg-alya-bedroom-2010",
    "chapter-1",
    "A fictionalized, modest bedroom corner where Alya reads and answers a feature-phone message.",
    { x: 0.42, y: 0.47 },
  ),
  background(
    "bg-boys-classroom",
    "chapter-2",
    "A plain secondary-school classroom in an unnamed boys' school.",
  ),
  background(
    "bg-boys-school-corridor",
    "chapter-2",
    "An empty open-air corridor at Aleem's unnamed boys' secondary school.",
    { x: 0.52, y: 0.45 },
  ),
  background(
    "bg-boys-classroom-overcast",
    "chapter-2",
    "The boys' secondary-school classroom under subdued overcast daylight.",
    { x: 0.5, y: 0.46 },
  ),
  background(
    "bg-language-classroom",
    "chapter-2",
    "A bright mixed-school classroom hosting an external language class.",
  ),
  background(
    "bg-language-classroom-late",
    "chapter-2",
    "The external language classroom late in the day, emptied into cool teal shadows.",
    { x: 0.5, y: 0.46 },
  ),
  background(
    "bg-language-courtyard",
    "chapter-2",
    "A leafy school courtyard in warm afternoon light.",
    { x: 0.5, y: 0.44 },
  ),
  background(
    "bg-language-corridor-rain",
    "chapter-2",
    "A generic external-school corridor during rain, with no identifying signs or badges.",
    { x: 0.5, y: 0.44 },
  ),
  background(
    "bg-bedroom-pc-day",
    "chapter-2",
    "Aleem's bedroom workspace and block-inspired game server setup by day.",
    { x: 0.65, y: 0.48 },
  ),
  background(
    "bg-bedroom-pc-night",
    "chapter-2",
    "Aleem's bedroom workspace illuminated by electric-blue monitors at night.",
    { x: 0.65, y: 0.48 },
  ),
  background(
    "bg-exam-hall",
    "chapter-2",
    "Rows of desks in a quiet, unnamed O-Level examination hall.",
  ),
  background(
    "bg-results-hall",
    "chapter-2",
    "A generic fluorescent results-collection hall in desaturated blue-grey, with no readable grades.",
    { x: 0.5, y: 0.44 },
  ),
  background(
    "bg-dark-bedroom",
    "chapter-2",
    "Aleem's darkened bedroom during a period of withdrawal.",
    { x: 0.63, y: 0.48 },
  ),
  background(
    "bg-dawn-window",
    "shared",
    "Soft dawn light entering through a bedroom window.",
    { x: 0.62, y: 0.46 },
  ),
  cg(
    "cg-wrong-message",
    "chapter-1",
    "Young Aleem reacting to an unexpected SMS on an unreadable feature-phone screen in cold blue light.",
    { x: 0.65, y: 0.46 },
  ),
  cg(
    "cg-first-confession",
    "chapter-1",
    "Primary 6 Aleem and Alya speaking nervously in a school corridor, with a respectful gap between them.",
    { x: 0.5, y: 0.42 },
  ),
  cg(
    "cg-graduation-promise",
    "chapter-1",
    "Primary 6 Aleem and Alya sharing a hopeful, bittersweet moment near their unnamed school gate after graduation.",
    { x: 0.5, y: 0.42 },
  ),
  cg(
    "cg-server-night",
    "chapter-2",
    "Teenage Aleem absorbed in late-night administration of an original block-inspired game server.",
    { x: 0.66, y: 0.48 },
  ),
  cg(
    "cg-results",
    "chapter-2",
    "Teenage Aleem processing an unreadable O-Level results paper in a generic collection hall.",
    { x: 0.65, y: 0.46 },
  ),
  cg(
    "cg-faris-wingman",
    "chapter-2",
    "Faris encouraging Hana on Aleem's behalf in a school courtyard while Aleem waits at a respectful distance.",
    { x: 0.5, y: 0.42 },
  ),
  cg(
    "cg-hana-breakup",
    "chapter-2",
    "Aleem and Hana having a quiet, balanced conversation in the late external-language classroom.",
    { x: 0.5, y: 0.42 },
  ),
  cg(
    "cg-o-level-exam",
    "chapter-2",
    "Teenage Aleem working under pressure in an unnamed O-Level examination hall with unreadable papers.",
    { x: 0.55, y: 0.44 },
  ),
  background(
    "bg-hdb-dining",
    "chapter-3",
    "A modest Singapore HDB dining area carrying the quiet weight of family expectations.",
    { x: 0.58, y: 0.46 },
  ),
  background(
    "bg-jc-walkway",
    "chapter-3",
    "A bright covered walkway at an unnamed junior college.",
    { x: 0.5, y: 0.45 },
  ),
  background(
    "bg-jc-classroom",
    "chapter-3",
    "A welcoming classroom at an unnamed junior college.",
    { x: 0.5, y: 0.46 },
  ),
  background(
    "bg-bus-interior-morning",
    "chapter-3",
    "The interior of a Singapore public bus in soft morning light.",
    { x: 0.5, y: 0.46 },
  ),
  background(
    "bg-bus-interior-evening",
    "chapter-3",
    "The same Singapore bus interior in cool blue evening light.",
    { x: 0.5, y: 0.46 },
  ),
  background(
    "bg-jc-study-area",
    "chapter-4",
    "A quiet junior-college study area with room for two friends.",
    { x: 0.52, y: 0.46 },
  ),
  background(
    "bg-a-level-results",
    "chapter-5",
    "An unnamed junior-college results area on A-Level results day.",
    { x: 0.5, y: 0.44 },
  ),
  background(
    "bg-zoo-path",
    "chapter-5",
    "An unbranded tropical zoo path in humid daylight.",
    { x: 0.5, y: 0.45 },
  ),
  background(
    "bg-zoo-shelter",
    "chapter-5",
    "A shaded, unbranded shelter beside a tropical zoo path.",
    { x: 0.52, y: 0.45 },
  ),
  cg(
    "cg-shared-earpiece",
    "chapter-3",
    "Aleem and Syafiqa dozing side by side on a morning bus, each wearing one wired earpiece.",
    { x: 0.55, y: 0.43 },
  ),
  cg(
    "cg-syafiqa-sighting",
    "chapter-3",
    "Aleem noticing Syafiqa walking closely with someone who remains out of view.",
    { x: 0.6, y: 0.44 },
  ),
  cg(
    "cg-zoo-distance",
    "chapter-5",
    "Aleem and Mei Lin standing apart with unresolved emotional distance between them at the zoo.",
    { x: 0.5, y: 0.44 },
  ),
  background(
    "bg-raya-living-room-2016",
    "chapter-6",
    "A warm, generic Singapore HDB living room prepared for Hari Raya visiting in 2016.",
    { x: 0.52, y: 0.45 },
  ),
  background(
    "bg-ns-camp-gate",
    "chapter-6",
    "An anonymous National Service camp gate and parade area without unit or national identifiers.",
    { x: 0.5, y: 0.44 },
  ),
  background(
    "bg-ns-bunk-night",
    "chapter-6",
    "An anonymous National Service bunk at night without insignia, weapons, or personal identifiers.",
    { x: 0.52, y: 0.44 },
  ),
  background(
    "bg-university-lecture-theatre",
    "chapter-6",
    "An ordinary, welcoming university lecture theatre during generic club recruitment.",
    { x: 0.5, y: 0.44 },
  ),
  background(
    "bg-university-corridor",
    "chapter-6",
    "A quiet corridor outside an unnamed university lecture theatre.",
    { x: 0.5, y: 0.46 },
  ),
  cg(
    "cg-raya-first-sight",
    "chapter-6",
    "Aleem and the wholly fictional Nadiah first noticing each other during a busy Hari Raya visit.",
    { x: 0.5, y: 0.42 },
  ),
  cg(
    "cg-relationship-montage",
    "chapter-6",
    "A restrained composite of mutual calls, messages, book-outs, and one public meeting between Aleem and Nadiah.",
    { x: 0.5, y: 0.44 },
  ),
  cg(
    "cg-close-friends-reveal",
    "chapter-6",
    "A generic private-story reveal showing Nadiah without hijab beside an unnamed, distant, unidentifiable man at an unbranded theme park.",
    { x: 0.54, y: 0.44 },
  ),

  sprite(
    "aleem-p6-neutral",
    "aleem-p6",
    "neutral",
    768,
    1152,
    "chapter-1",
    "Primary 6 Aleem, neutral.",
    { x: 0.5, y: 0.24 },
  ),
  sprite(
    "aleem-p6-smile",
    "aleem-p6",
    "smile",
    768,
    1152,
    "chapter-1",
    "Primary 6 Aleem smiling shyly.",
    { x: 0.5, y: 0.24 },
  ),
  sprite(
    "aleem-p6-cheerful",
    "aleem-p6",
    "cheerful",
    768,
    1152,
    "chapter-1",
    "Primary 6 Aleem looking openly cheerful.",
    { x: 0.5, y: 0.24 },
  ),
  sprite(
    "aleem-p6-surprised",
    "aleem-p6",
    "surprised",
    768,
    1152,
    "chapter-1",
    "Primary 6 Aleem looking surprised.",
    { x: 0.5, y: 0.24 },
  ),
  sprite(
    "aleem-p6-nervous",
    "aleem-p6",
    "nervous",
    768,
    1152,
    "chapter-1",
    "Primary 6 Aleem looking nervous.",
    { x: 0.5, y: 0.24 },
  ),
  sprite(
    "aleem-p6-reflective",
    "aleem-p6",
    "reflective",
    768,
    1152,
    "chapter-1",
    "Primary 6 Aleem in a reflective mood.",
    { x: 0.5, y: 0.24 },
  ),
  sprite(
    "alya-neutral",
    "alya",
    "neutral",
    768,
    1152,
    "chapter-1",
    "Alya, neutral.",
    { x: 0.5, y: 0.23 },
  ),
  sprite(
    "alya-smile",
    "alya",
    "smile",
    768,
    1152,
    "chapter-1",
    "Alya smiling.",
    { x: 0.5, y: 0.23 },
  ),
  sprite(
    "alya-playful",
    "alya",
    "playful",
    768,
    1152,
    "chapter-1",
    "Alya with a playful expression.",
    { x: 0.5, y: 0.23 },
  ),
  sprite(
    "alya-shy",
    "alya",
    "shy",
    768,
    1152,
    "chapter-1",
    "Alya looking shy but receptive.",
    { x: 0.5, y: 0.23 },
  ),
  sprite(
    "alya-hopeful",
    "alya",
    "hopeful",
    768,
    1152,
    "chapter-1",
    "Alya looking hopeful about staying in touch after graduation.",
    { x: 0.5, y: 0.23 },
  ),

  sprite(
    "aleem-young-home-neutral",
    "aleem-young-home",
    "neutral",
    768,
    1152,
    "chapter-1",
    "Young Aleem in modest home clothes, neutral.",
    { x: 0.5, y: 0.24 },
  ),
  sprite(
    "aleem-young-home-smile",
    "aleem-young-home",
    "smile",
    768,
    1152,
    "chapter-1",
    "Young Aleem smiling while keeping in touch from home.",
    { x: 0.5, y: 0.24 },
  ),
  sprite(
    "aleem-young-home-waiting",
    "aleem-young-home",
    "waiting",
    768,
    1152,
    "chapter-1",
    "Young Aleem waiting for a reply on his feature phone.",
    { x: 0.5, y: 0.24 },
  ),
  sprite(
    "aleem-young-home-startled",
    "aleem-young-home",
    "startled",
    768,
    1152,
    "chapter-1",
    "Young Aleem startled by an unexpected message at home.",
    { x: 0.5, y: 0.24 },
  ),
  sprite(
    "aleem-young-home-hurt",
    "aleem-young-home",
    "hurt",
    768,
    1152,
    "chapter-1",
    "Young Aleem looking quietly hurt at home.",
    { x: 0.5, y: 0.24 },
  ),
  sprite(
    "alya-young-home-startled",
    "alya-young-home",
    "startled",
    768,
    1152,
    "chapter-1",
    "Alya in modest home clothes, startled after realizing she sent a message to the wrong person.",
    { x: 0.5, y: 0.23 },
  ),
  sprite(
    "alya-young-home-apologetic",
    "alya-young-home",
    "apologetic",
    768,
    1152,
    "chapter-1",
    "Alya in modest home clothes, offering a sincere apology.",
    { x: 0.5, y: 0.23 },
  ),
  sprite(
    "alya-young-home-sad",
    "alya-young-home",
    "sad",
    768,
    1152,
    "chapter-1",
    "Alya in modest home clothes, sad as the relationship ends.",
    { x: 0.5, y: 0.23 },
  ),

  sprite(
    "aleem-sec-neutral",
    "aleem-sec",
    "neutral",
    768,
    1152,
    "chapter-2",
    "Secondary-school Aleem, neutral.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "aleem-sec-nervous",
    "aleem-sec",
    "nervous",
    768,
    1152,
    "chapter-2",
    "Secondary-school Aleem looking nervous.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "aleem-sec-smile",
    "aleem-sec",
    "smile",
    768,
    1152,
    "chapter-2",
    "Secondary-school Aleem smiling.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "aleem-sec-embarrassed",
    "aleem-sec",
    "embarrassed",
    768,
    1152,
    "chapter-2",
    "Secondary-school Aleem looking embarrassed.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "aleem-sec-confused",
    "aleem-sec",
    "confused",
    768,
    1152,
    "chapter-2",
    "Secondary-school Aleem looking confused.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "aleem-sec-defensive",
    "aleem-sec",
    "defensive",
    768,
    1152,
    "chapter-2",
    "Secondary-school Aleem becoming defensive during a difficult conversation.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "aleem-sec-guilty",
    "aleem-sec",
    "guilty",
    768,
    1152,
    "chapter-2",
    "Secondary-school Aleem looking guilty.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "aleem-sec-tired",
    "aleem-sec",
    "tired",
    768,
    1152,
    "chapter-2",
    "Secondary-school Aleem looking tired.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "aleem-sec-devastated",
    "aleem-sec",
    "devastated",
    768,
    1152,
    "chapter-2",
    "Secondary-school Aleem processing devastating news.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "aleem-home-focused",
    "aleem-home",
    "focused",
    768,
    1152,
    "chapter-2",
    "Aleem in home clothes, focused on his computer.",
    { x: 0.5, y: 0.22 },
  ),
  sprite(
    "aleem-home-proud",
    "aleem-home",
    "proud",
    768,
    1152,
    "chapter-2",
    "Aleem in home clothes, proud of his server.",
    { x: 0.5, y: 0.22 },
  ),
  sprite(
    "aleem-home-distracted",
    "aleem-home",
    "distracted",
    768,
    1152,
    "chapter-2",
    "Aleem in home clothes, distracted by server alerts.",
    { x: 0.5, y: 0.22 },
  ),
  sprite(
    "aleem-home-overwhelmed",
    "aleem-home",
    "overwhelmed",
    768,
    1152,
    "chapter-2",
    "Aleem in home clothes, overwhelmed by competing server, relationship, and school demands.",
    { x: 0.5, y: 0.22 },
  ),
  sprite(
    "aleem-home-regretful",
    "aleem-home",
    "regretful",
    768,
    1152,
    "chapter-2",
    "Aleem in home clothes, reflecting with regret on what he neglected.",
    { x: 0.5, y: 0.22 },
  ),
  sprite(
    "aleem-home-numb",
    "aleem-home",
    "numb",
    768,
    1152,
    "chapter-2",
    "Aleem in home clothes, withdrawn and numb.",
    { x: 0.5, y: 0.22 },
  ),
  sprite(
    "hana-neutral",
    "hana",
    "neutral",
    768,
    1152,
    "chapter-2",
    "Hana, neutral.",
    { x: 0.5, y: 0.21 },
  ),
  sprite(
    "hana-curious",
    "hana",
    "curious",
    768,
    1152,
    "chapter-2",
    "Hana looking curious.",
    { x: 0.5, y: 0.21 },
  ),
  sprite(
    "hana-shy",
    "hana",
    "shy",
    768,
    1152,
    "chapter-2",
    "Hana with a shy expression.",
    { x: 0.5, y: 0.21 },
  ),
  sprite(
    "hana-smile",
    "hana",
    "smile",
    768,
    1152,
    "chapter-2",
    "Hana smiling.",
    { x: 0.5, y: 0.21 },
  ),
  sprite(
    "hana-supportive",
    "hana",
    "supportive",
    768,
    1152,
    "chapter-2",
    "Hana offering Aleem patient support.",
    { x: 0.5, y: 0.21 },
  ),
  sprite(
    "hana-concerned",
    "hana",
    "concerned",
    768,
    1152,
    "chapter-2",
    "Hana looking concerned as Aleem becomes harder to reach.",
    { x: 0.5, y: 0.21 },
  ),
  sprite(
    "hana-disappointed",
    "hana",
    "disappointed",
    768,
    1152,
    "chapter-2",
    "Hana looking disappointed.",
    { x: 0.5, y: 0.21 },
  ),
  sprite(
    "hana-distant",
    "hana",
    "distant",
    768,
    1152,
    "chapter-2",
    "Hana with a distant expression.",
    { x: 0.5, y: 0.21 },
  ),
  sprite(
    "hana-apologetic",
    "hana",
    "apologetic",
    768,
    1152,
    "chapter-2",
    "Hana looking apologetic during a difficult but direct conversation.",
    { x: 0.5, y: 0.21 },
  ),
  sprite(
    "faris-neutral",
    "faris",
    "neutral",
    768,
    1152,
    "chapter-2",
    "Faris, neutral.",
    { x: 0.5, y: 0.24 },
  ),
  sprite(
    "faris-teasing",
    "faris",
    "teasing",
    768,
    1152,
    "chapter-2",
    "Faris teasing Aleem with friendly energy.",
    { x: 0.5, y: 0.24 },
  ),
  sprite(
    "faris-encouraging",
    "faris",
    "encouraging",
    768,
    1152,
    "chapter-2",
    "Faris looking encouraging.",
    { x: 0.5, y: 0.24 },
  ),
  sprite(
    "faris-confident",
    "faris",
    "confident",
    768,
    1152,
    "chapter-2",
    "Faris with a confident expression.",
    { x: 0.5, y: 0.24 },
  ),
  sprite(
    "aleem-jc-neutral",
    "aleem-jc",
    "neutral",
    768,
    1152,
    "chapter-3",
    "Junior-college Aleem, neutral.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-jc-smile",
    "aleem-jc",
    "smile",
    768,
    1152,
    "chapter-3",
    "Junior-college Aleem smiling.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-jc-nervous",
    "aleem-jc",
    "nervous",
    768,
    1152,
    "chapter-3",
    "Junior-college Aleem looking nervous.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-jc-uncertain",
    "aleem-jc",
    "uncertain",
    768,
    1152,
    "chapter-3",
    "Junior-college Aleem looking uncertain.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-jc-focused",
    "aleem-jc",
    "focused",
    768,
    1152,
    "chapter-4",
    "Junior-college Aleem studying with renewed focus.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-jc-tired",
    "aleem-jc",
    "tired",
    768,
    1152,
    "chapter-3",
    "Junior-college Aleem looking tired.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-jc-hurt",
    "aleem-jc",
    "hurt",
    768,
    1152,
    "chapter-3",
    "Junior-college Aleem looking hurt.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-jc-relieved",
    "aleem-jc",
    "relieved",
    768,
    1152,
    "chapter-5",
    "Junior-college Aleem looking relieved after his A-Level results.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "syafiqa-neutral",
    "syafiqa",
    "neutral",
    768,
    1152,
    "chapter-3",
    "Syafiqa, neutral.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "syafiqa-smile",
    "syafiqa",
    "smile",
    768,
    1152,
    "chapter-3",
    "Syafiqa smiling warmly.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "syafiqa-amused",
    "syafiqa",
    "amused",
    768,
    1152,
    "chapter-3",
    "Syafiqa looking amused.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "syafiqa-sleepy",
    "syafiqa",
    "sleepy",
    768,
    1152,
    "chapter-3",
    "Syafiqa looking sleepy during the morning commute.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "syafiqa-attentive",
    "syafiqa",
    "attentive",
    768,
    1152,
    "chapter-3",
    "Syafiqa listening attentively.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "syafiqa-gentle-firm",
    "syafiqa",
    "gentle-firm",
    768,
    1152,
    "chapter-3",
    "Syafiqa giving a gentle but firm answer.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "mei-lin-jc-neutral",
    "mei-lin-jc",
    "neutral",
    768,
    1152,
    "chapter-4",
    "Mei Lin, neutral, in her junior-college uniform.",
    { x: 0.5, y: 0.29 },
  ),
  sprite(
    "mei-lin-jc-supportive",
    "mei-lin-jc",
    "supportive",
    768,
    1152,
    "chapter-4",
    "Mei Lin offering quiet support.",
    { x: 0.5, y: 0.29 },
  ),
  sprite(
    "mei-lin-jc-focused",
    "mei-lin-jc",
    "focused",
    768,
    1152,
    "chapter-4",
    "Mei Lin focused on studying.",
    { x: 0.5, y: 0.29 },
  ),
  sprite(
    "mei-lin-jc-amused",
    "mei-lin-jc",
    "amused",
    768,
    1152,
    "chapter-4",
    "Mei Lin sharing a quietly amused expression.",
    { x: 0.5, y: 0.29 },
  ),
  sprite(
    "mei-lin-jc-disappointed",
    "mei-lin-jc",
    "disappointed",
    768,
    1152,
    "chapter-5",
    "Mei Lin processing disappointing A-Level results.",
    { x: 0.5, y: 0.29 },
  ),
  sprite(
    "aleem-casual-neutral",
    "aleem-casual",
    "neutral",
    768,
    1152,
    "chapter-5",
    "Aleem in casual clothes at the zoo, neutral.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-casual-smile",
    "aleem-casual",
    "smile",
    768,
    1152,
    "chapter-5",
    "Aleem smiling in casual clothes at the zoo.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-casual-patient",
    "aleem-casual",
    "patient",
    768,
    1152,
    "chapter-5",
    "Aleem maintaining a patient expression at the zoo.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-casual-frustrated",
    "aleem-casual",
    "frustrated",
    768,
    1152,
    "chapter-5",
    "Aleem containing his frustration at the zoo.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "mei-lin-casual-neutral",
    "mei-lin-casual",
    "neutral",
    768,
    1152,
    "chapter-5",
    "Mei Lin in casual clothes at the zoo, neutral.",
    { x: 0.5, y: 0.29 },
  ),
  sprite(
    "mei-lin-casual-smile",
    "mei-lin-casual",
    "smile",
    768,
    1152,
    "chapter-5",
    "Mei Lin relaxing into a smile at the zoo.",
    { x: 0.5, y: 0.29 },
  ),
  sprite(
    "mei-lin-casual-animated",
    "mei-lin-casual",
    "animated",
    768,
    1152,
    "chapter-5",
    "Mei Lin speaking animatedly at the zoo.",
    { x: 0.5, y: 0.29 },
  ),
  sprite(
    "mei-lin-casual-guarded",
    "mei-lin-casual",
    "guarded",
    768,
    1152,
    "chapter-5",
    "Mei Lin with a thoughtful, guarded expression at the zoo.",
    { x: 0.5, y: 0.29 },
  ),
  sprite(
    "aleem-ns-neutral",
    "aleem-ns",
    "neutral",
    768,
    1152,
    "chapter-6",
    "Young-adult Aleem in an anonymous National Service uniform, neutral.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-ns-proud",
    "aleem-ns",
    "proud",
    768,
    1152,
    "chapter-6",
    "Young-adult Aleem in an anonymous National Service uniform, proud after Passing Out Parade.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-ns-warm",
    "aleem-ns",
    "warm",
    768,
    1152,
    "chapter-6",
    "Young-adult Aleem in an anonymous National Service uniform, warmed by an ordinary message.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-ns-stunned",
    "aleem-ns",
    "stunned",
    768,
    1152,
    "chapter-6",
    "Young-adult Aleem in an anonymous National Service uniform, stunned.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-ns-hurt",
    "aleem-ns",
    "hurt",
    768,
    1152,
    "chapter-6",
    "Young-adult Aleem in an anonymous National Service uniform, visibly hurt.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-ns-numb",
    "aleem-ns",
    "numb",
    768,
    1152,
    "chapter-6",
    "Young-adult Aleem in an anonymous National Service uniform, numb while service continues.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-raya-awed",
    "aleem-raya",
    "awed",
    768,
    1152,
    "chapter-6",
    "Young-adult Aleem in a modest baju melayu, caught in a first look.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-raya-shy-smile",
    "aleem-raya",
    "shy-smile",
    768,
    1152,
    "chapter-6",
    "Young-adult Aleem in a modest baju melayu, smiling shyly during Hari Raya visiting.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-uni-neutral",
    "aleem-uni",
    "neutral",
    768,
    1152,
    "chapter-6",
    "Young-adult Aleem in plain university clothes, neutral.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-uni-guarded",
    "aleem-uni",
    "guarded",
    768,
    1152,
    "chapter-6",
    "Young-adult Aleem in plain university clothes, guarded at a doorway.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-uni-frozen",
    "aleem-uni",
    "frozen",
    768,
    1152,
    "chapter-6",
    "Young-adult Aleem in plain university clothes, frozen while entering an ordinary room.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-uni-overwhelmed",
    "aleem-uni",
    "overwhelmed",
    768,
    1152,
    "chapter-6",
    "Young-adult Aleem in plain university clothes, overwhelmed by his own alarm.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "aleem-uni-breathless",
    "aleem-uni",
    "breathless",
    768,
    1152,
    "chapter-6",
    "Young-adult Aleem catching his breath in a university corridor.",
    { x: 0.5, y: 0.18 },
  ),
  sprite(
    "nadiah-neutral",
    "nadiah",
    "neutral",
    768,
    1152,
    "chapter-6",
    "Nadiah, a wholly fictional young Malay woman in modest Hari Raya clothing and hijab, neutral.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "nadiah-warm",
    "nadiah",
    "warm",
    768,
    1152,
    "chapter-6",
    "Nadiah, a wholly fictional young Malay woman in modest Hari Raya clothing and hijab, warm.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "nadiah-amused",
    "nadiah",
    "amused",
    768,
    1152,
    "chapter-6",
    "Nadiah, a wholly fictional young Malay woman in modest Hari Raya clothing and hijab, amused.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "nadiah-thoughtful",
    "nadiah",
    "thoughtful",
    768,
    1152,
    "chapter-6",
    "Nadiah, a wholly fictional young Malay woman in modest Hari Raya clothing and hijab, thoughtful.",
    { x: 0.5, y: 0.2 },
  ),
  sprite(
    "nadiah-guarded",
    "nadiah",
    "guarded",
    768,
    1152,
    "chapter-6",
    "Nadiah, a wholly fictional young Malay woman in modest Hari Raya clothing and hijab, guarded but not villainised.",
    { x: 0.5, y: 0.2 },
  ),
] as const satisfies readonly ArtAssetSpec[];

const defaultBaseUrl = (): string =>
  (
    import.meta as ImportMeta & {
      readonly env?: { readonly BASE_URL?: string };
    }
  ).env?.BASE_URL || "/";

export const createArtAssetManifest = (
  baseUrl = defaultBaseUrl(),
): readonly AssetEntry[] =>
  ART_SPECS.map(({ path, promptReference, ...spec }) => ({
    ...spec,
    url: appPathname(path, baseUrl),
    provenance: generatedProvenance(promptReference),
  }));

export const artAssets = createArtAssetManifest();

const mappedIds = new Set(ART_SPECS.map((asset) => asset.id));

export const unmappedStoryAssetIds = storyAssetIds.filter(
  (id) => !mappedIds.has(id),
);

export const extraArtAssetIds = ART_SPECS.map((asset) => asset.id).filter(
  (id) => !(storyAssetIds as readonly string[]).includes(id),
);
