export const storyBackgroundIds = [
  "bg-primary-classroom",
  "bg-primary-corridor",
  "bg-graduation-gate",
  "bg-bus-stop",
  "bg-bedroom-2009",
  "bg-boys-classroom",
  "bg-language-classroom",
  "bg-language-courtyard",
  "bg-bedroom-pc-day",
  "bg-bedroom-pc-night",
  "bg-exam-hall",
  "bg-results-hall",
  "bg-dark-bedroom",
  "bg-dawn-window",
  "cg-wrong-message",
  "cg-server-night",
  "cg-results",
] as const;

export const storySpriteAssetIds = [
  "aleem-p6-neutral",
  "aleem-p6-smile",
  "aleem-p6-surprised",
  "aleem-p6-hurt",
  "aleem-p6-reflective",
  "alya-neutral",
  "alya-smile",
  "alya-playful",
  "alya-startled",
  "alya-apologetic",
  "aleem-sec-neutral",
  "aleem-sec-nervous",
  "aleem-sec-smile",
  "aleem-sec-confused",
  "aleem-sec-guilty",
  "aleem-sec-tired",
  "aleem-sec-devastated",
  "aleem-home-focused",
  "aleem-home-proud",
  "aleem-home-distracted",
  "aleem-home-numb",
  "hana-neutral",
  "hana-curious",
  "hana-shy",
  "hana-smile",
  "hana-disappointed",
  "hana-distant",
  "faris-neutral",
  "faris-encouraging",
  "faris-confident",
] as const;

export const storyAssetIds = [
  ...storyBackgroundIds,
  ...storySpriteAssetIds,
] as const;

