import type { StageSnapshot, StoryNode } from "../engine/types";
import { choice, line } from "./helpers";
import { adulthoodStages as stages } from "./adulthoodStages";

const beat = (id: string, stage: StageSnapshot, speaker: string, text: string, next: string) =>
  line(id, "chapter-7", stage, speaker, text, next);

export const chapterSevenNodes = [
  beat("ch7-001", stages.officeArrival, "adult-aleem",
    "Working life gave my days a different shape. There were names to learn, tasks whose urgency I could not yet judge, and mornings when I arrived early because being lost seemed less embarrassing without an audience. I tried to look settled while checking the same instructions for the third time.", "ch7-002"),
  beat("ch7-002", stages.officeTogether, "adult-aleem",
    "Claire found me in the pantry studying the drinks as if there might be a correct first-week choice. She was Chinese, easy to talk to, and had joined six months before me. That made her recent enough to remember being new and experienced enough to know which cupboard held the decent mugs.", "ch7-003"),
  beat("ch7-003", stages.officeTogether, "claire",
    "That one leaks. Unless you want coffee on your shirt before your first meeting, take the blue one.", "ch7-004"),
  beat("ch7-004", stages.officeWarm, "aleem-adult",
    "Very useful onboarding. They should have put you in charge.", "ch7-005"),
  beat("ch7-005", stages.officeTeasing, "claire",
    "Six months of experience. Cannot waste it.", "ch7-006"),
  beat("ch7-006", stages.officeWarm, "adult-aleem",
    "She showed me where people usually ate and which questions could safely wait until after lunch. When I looked overwhelmed, she checked in without making a performance of helping. Soon I had things to offer back: a second pair of eyes, a remembered drink order, company when a difficult day ran late.", "ch7-007"),
  beat("ch7-007", stages.officeTogether, "claire",
    "Do you have five minutes? I need someone to tell me whether this makes sense or I've been looking at it too long.", "ch7-008"),
  beat("ch7-008", stages.officeTeasing, "aleem-adult",
    "Those can both be true. Let me see.", "ch7-009"),
  beat("ch7-009", stages.officeWarm, "adult-aleem",
    "Five minutes became a conversation over lunch. Lunch became a message on the way home. She sent me a picture of something ridiculous she had passed; I saved a story from my day because I wanted to hear her laugh at it. Friendship slipped beyond the office without either of us needing to announce it.", "ch7-pantry-routine"),
  beat("ch7-pantry-routine", stages.officeTogether, "adult-aleem",
    "I learned to recognise her footsteps when she came into the pantry. Some afternoons she only had time to refill her cup, but we could fit a surprising amount of conversation around the kettle. If one of us had been quiet all morning, the other noticed. Being noticed made the unfamiliar parts of working life feel less lonely.", "ch7-010"),
  beat("ch7-010", stages.cafeTogether, "adult-aleem",
    "Outside work, Claire talked more slowly. She would turn her cup round while deciding how to describe something, then say exactly what she meant. I liked that. After all the meanings I had once hunted between somebody else's words, her plainness felt restful. I began wanting to be the person she chose for these conversations.", "ch7-011"),
  beat("ch7-011", stages.cafeTogether, "claire",
    "You know you can stop doing the polite work voice. We're not in a meeting.", "ch7-012"),
  beat("ch7-012", stages.cafeTogether, "aleem-adult",
    "This is my normal voice. Very professional person, me.", "ch7-013"),
  beat("ch7-013", stages.cafeTogether, "adult-aleem",
    "She laughed into her drink. I watched her try to recover her dignity and felt that familiar warmth spread through an ordinary evening. This time I recognised what I was hoping for. I also knew our religions were different. The difference sat among things we knew about each other, waiting for a conversation I couldn't keep avoiding.", "ch7-014"),
  beat("ch7-014", stages.workPreparing, "adult-aleem",
    "I thought about Jia Wen's question. Earlier had become a word I could trip over even in a new life. With Claire, I would speak before years collected around an assumption. Valentine's Day in 2023 gave me a date to stop postponing it. I chose the words for a question, not a speech about everything I had done.", "ch7-before-valentines"),
  beat("ch7-before-valentines", stages.workPreparing, "adult-aleem",
    "I still rehearsed. That part had survived every lesson. But this time, when I imagined her answer, I tried to let it be something I hadn't chosen for her. It was easy enough alone in my room. In the morning, seeing a message from her made me hopeful all over again, and I had to start the exercise over.", "ch7-015"),
  beat("ch7-015", stages.valentine, "adult-aleem",
    "On 14 February, I could barely follow our ordinary conversation. By the waterfront, couples kept stopping for photographs while we moved aside to let people pass. The date was suddenly embarrassingly obvious. I had chosen a day that said the thing for me, and still needed to say it myself.", "ch7-016"),
  beat("ch7-016", stages.valentine, "aleem-adult",
    "Claire, I like you. More than a friend. I wanted to tell you properly and ask whether you could see us being together.", "ch7-017"),
  beat("ch7-017", stages.claireClear, "claire",
    "I'm sorry, Aleem. I care about you, but I can't be with you that way. Our religions are different. Being with someone who shares my religion matters to me.", "ch7-018"),
  beat("ch7-018", stages.claireClear, "adult-aleem",
    "I nodded too quickly. Some part of me had prepared for this answer; preparation did very little when it arrived in her voice. I looked out at the water so I could stop managing my expression for a moment. She let the silence stay instead of filling it with a softer possibility.", "ch7-choice-rejection"),
  choice("ch7-choice-rejection", "chapter-7", stages.claireReflection,
    "What could I say while the answer was still hurting?", [
      { id: "rejection-thanks", label: "Thank you for telling me clearly.", next: "ch7-rejection-thanks" },
      { id: "rejection-minute", label: "I understand. I need a minute.", next: "ch7-rejection-minute" },
      { id: "rejection-respect", label: "I won't ask you to change what matters to you.", next: "ch7-rejection-respect" },
    ]),
  beat("ch7-rejection-thanks", stages.claireReflection, "aleem-adult",
    "Thank you for telling me clearly. It hurts, but I'm glad you didn't leave me guessing. I don't have a very graceful response prepared. Just... I heard you. You don't need to explain it over and over to make me feel better.", "ch7-rejection-join"),
  beat("ch7-rejection-minute", stages.claireReflection, "aleem-adult",
    "Okay. I understand. Can we stand here a bit? I need a minute before I can talk normally again. I'm not waiting for you to say something different. My face just hasn't caught up with the part of me that's trying to be sensible.", "ch7-rejection-join"),
  beat("ch7-rejection-respect", stages.claireReflection, "aleem-adult",
    "I won't ask you to change that for me. I knew religion mattered, but I hoped there might be a way you saw this differently. Now you've told me. I respect it. Give me a little time to get past what I was hoping to hear.", "ch7-rejection-join"),
  beat("ch7-rejection-join", stages.claireReflection, "adult-aleem",
    "There was no negotiation. I accepted her answer, though disappointment followed me home. For once I did not have to reconstruct a hidden message. She had told me something definite about the future she wanted. The difficult part was learning how to remain beside her without treating that future as a challenge.", "ch7-019"),
  beat("ch7-019", stages.officeTogether, "adult-aleem",
    "The next workday, I reached the pantry and found her making a drink. There was a strange little pause before she asked how I was. I could hear the care in the ordinary question, and the uncertainty about whether ordinary questions were still allowed. I was grateful she had asked anyway.", "ch7-020"),
  beat("ch7-020", stages.officeTogether, "aleem-adult",
    "I'm okay enough for coffee. Maybe not okay enough for a long conversation about feelings before lunch.", "ch7-021"),
  beat("ch7-021", stages.officeWarm, "claire",
    "Coffee I can manage. The blue mug is free.", "ch7-022"),
  beat("ch7-022", stages.officeWarm, "adult-aleem",
    "We stayed friends. There were careful moments at first, then familiar ones. She still needed somebody to complain to after a frustrating afternoon. I still wanted to tell her things. We found our way back through small exchanges until the confession no longer entered the room ahead of us every time we met.", "ch7-staying-friends"),
  beat("ch7-staying-friends", stages.officeTogether, "adult-aleem",
    "When she laughed at something I said, I felt relieved before I felt anything else. We could still do this. I could hand her a mug without making an occasion of it, ask about her weekend, tell her I was having a difficult day. I wanted those things to count as evidence that I was managing the friendship properly.", "ch7-023"),
  beat("ch7-023", stages.cafeFriends, "claire",
    "There's a café I want to try. Everybody posts couple photos there, but I just want to know whether the food is actually good. You free this weekend?", "ch7-024"),
  beat("ch7-024", stages.cafeFriends, "aleem-adult",
    "As your very objective food research partner, yes.", "ch7-025"),
  beat("ch7-025", stages.cafeFriends, "adult-aleem",
    "The place had soft lighting, small tables, and prices that encouraged us to make jokes about the rent. Around us, people leaned close for photographs. Claire handed me her phone and asked for a picture before the food arrived. I took several because she always found something wrong with the first one.", "ch7-026"),
  beat("ch7-026", stages.cafeFriends, "claire",
    "You made the empty chair the main character. I'm over here, thanks.", "ch7-027"),
  beat("ch7-027", stages.cafeFriends, "adult-aleem",
    "We laughed, checked the menu, and spent an unhurried afternoon together. Afterwards, she said she was glad she'd had someone to go with. So was I. That became our explanation for other places too: somewhere we wanted to try, something nicer with company. We were friends. We had already settled that.", "ch7-cafe-photo"),
  beat("ch7-cafe-photo", stages.cafeFriends, "adult-aleem",
    "She took my photograph too, directing me to move my cup because it covered half my face. I complained until she showed me the result. Then we sat shoulder to shoulder over the pictures, choosing which ones to keep. It was a small, lovely thing to do with someone. I carried the feeling home longer than the afternoon lasted.", "ch7-028"),
  beat("ch7-028", stages.waterfrontFriends, "adult-aleem",
    "There were evenings by the water when the city lights broke into long lines around the boats. We walked at the same pace, stopped when one of us noticed something, and talked until we should have gone home. Anybody passing could have mistaken us for a couple. I knew how little that proved now.", "ch7-choice-companionship"),
  choice("ch7-choice-companionship", "chapter-7", stages.waterfrontFriends,
    "What kept me saying yes to these evenings?", [
      { id: "companionship-company", label: "I loved having her company.", next: "ch7-companionship-company" },
      { id: "companionship-hope", label: "Some hope was still there.", next: "ch7-companionship-hope" },
      { id: "companionship-alone", label: "I didn't want to go home alone yet.", next: "ch7-companionship-alone" },
    ]),
  beat("ch7-companionship-company", stages.waterfrontFriends, "adult-aleem",
    "I liked the actual person walking beside me: her terrible photographs, her patient questions, the way she remembered a story I had mentioned once. The friendship wasn't an empty consolation. That was what made it so difficult to notice when enjoying her company slipped back into wanting more.", "ch7-companionship-join"),
  beat("ch7-companionship-hope", stages.waterfrontFriends, "adult-aleem",
    "Her answer had not changed. Still, an especially good evening could wake a small, stubborn maybe in me. I didn't say it aloud or ask her to reconsider. I simply let tomorrow remain a little less definite in my head than she had made it in our conversation.", "ch7-companionship-join"),
  beat("ch7-companionship-alone", stages.waterfrontFriends, "adult-aleem",
    "I knew what waited at home: a quiet room and more time to think than I wanted. Here, somebody was asking whether we should get a drink before leaving. I could accept a small kindness tonight without solving the whole future. It was very easy to keep choosing tonight.", "ch7-companionship-join"),
  beat("ch7-companionship-join", stages.waterfrontFriends, "adult-aleem",
    "We gave each other company, a reason to go somewhere, someone to send the pictures to afterwards. We said the outings came without feelings attached. I could say it convincingly enough. But I still caught myself smiling at her name on my phone in a way I did not smile at everybody else's.", "ch7-waterfront-goodnight"),
  beat("ch7-waterfront-goodnight", stages.waterfrontFriends, "adult-aleem",
    "Near the end of an evening, one of us would check the time and groan. We stayed for another few minutes anyway. Then she would wave, turn towards her way home, and leave me with a goodnight that meant exactly what she had said. I tried to keep the evening that simple while I waited for my own journey back.", "ch7-029"),
  beat("ch7-029", stages.officeWarm, "adult-aleem",
    "Time passed like that. I could be happy through a whole meal and feel lonely on the journey back. I had learned to ask the question earlier. I had not learned how quickly closeness could become waiting again, even after an answer. Nobody had promised me anything. The waiting happened quietly inside me.", "ch7-030"),
  beat("ch7-030", stages.claireNews, "claire",
    "There's someone I've been getting to know. I wanted to tell you myself. We share the same religion. I think this could become something.", "ch7-031"),
  beat("ch7-031", stages.claireNews, "adult-aleem",
    "This time there was no overheard conversation, no stranger appearing at the edge of a scene I thought I understood. She told me across a table. I watched her choose the words carefully and wished I could make it easy for her without having to feel them first.", "ch7-032"),
  beat("ch7-032", stages.claireNews, "aleem-adult",
    "I'm glad you told me. I hope it goes well. Really.", "ch7-033"),
  beat("ch7-033", stages.claireNews, "adult-aleem",
    "I meant it. I also wanted to go somewhere I could stop holding my expression together. Both things sat inside me while she answered. Later, as that relationship found its place in her life, our habits changed. The invitations grew less frequent. Plans that once started with the two of us began somewhere else.", "ch7-changed-plans"),
  beat("ch7-changed-plans", stages.claireNews, "adult-aleem",
    "I could still send her something funny and get a reply. That almost made the change harder to explain to myself. There was no single conversation I could point to and call the ending. I simply stopped assuming she would be free, and began putting the phone down before asking about places we had once said we should visit.", "ch7-034"),
  beat("ch7-034", stages.workAlone, "adult-aleem",
    "I stayed nearby until there was no longer the same place to stand. There wasn't a second confession or a final argument. Just evenings opening up where her company used to be, and the knowledge that she had found the kind of relationship she had told me she wanted.", "ch7-035"),
  beat("ch7-035", stages.workAlone, "adult-aleem",
    "At home, I opened a picture from one of our outings. The table, the food, the lighting we had made fun of. I remembered being happy there. Then I locked the phone and sat in the quiet, exhausted by how often happiness had become something I could only visit afterwards.", "ch7-036"),
  beat("ch7-036", stages.workAlone, "adult-aleem",
    "I had tried speaking quickly. I had tried waiting. I had finally said what I felt and accepted a clear no. Still, I was here again. The room seemed to hold every earlier disappointment at once, until the life I had imagined felt as if it had come down around me.", "ch7-037"),
  beat("ch7-037", stages.workAlone, "aleem-adult",
    "Maybe that's enough. Maybe I just stop looking for love.", "ch7-038"),
  beat("ch7-038", stages.workAlone, "adult-aleem",
    "I said it into an empty room. There was no one to challenge me, no new message to interrupt the thought. I wanted to mean it. I wanted the wanting itself to stop, so I could get through a day without feeling that some essential part of my life was missing.", "ch8-001"),
] as const satisfies readonly StoryNode[];
