import type { StageSnapshot, StoryNode } from "../engine/types";
import { choice, line } from "./helpers";
import { finaleStages as stages } from "./finaleStages";

const beat = (id: string, stage: StageSnapshot, speaker: string, text: string, next: string) =>
  line(id, "chapter-11", stage, speaker, text, next);

export const chapterElevenNodes = [
  beat("ch11-001", stages.introduction, "mariam",
    "Aleem, there's someone I work with. A girl I know. I'd like to introduce you to her.", "ch11-002"),
  beat("ch11-002", stages.introduction, "mariam",
    "Her name is Nurulain.", "ch11-003"),
  beat("ch11-003", stages.introduction, "adult-aleem",
    "Nurulain. A name I had never attached to a memory, a disappointment, or something I wished I had said differently. I listened to Kak Mariam and felt a small, unfamiliar willingness. I could get to know someone. That was all an introduction needed to mean for now.", "ch11-004"),
  beat("ch11-004", stages.firstMessage, "adult-aleem",
    "When it was time to message her, I made the first move. Moving on had given me room to try again; it hadn't removed every doubt. I still paused over the screen. Then I thought of the trust I had carried home from Umrah. I couldn't know His plans by waiting until I felt completely certain.", "ch11-005"),
  beat("ch11-005", stages.firstMessage, "aleem-adult",
    "Assalamualaikum, Nurul. I'm Aleem. Kak Mariam introduced us. How are you?", "ch11-006"),
  beat("ch11-006", stages.messages, "adult-aleem",
    "She answered, and we began talking. Nothing went dramatically wrong. There were greetings, questions, little exchanges about our days. If you had asked me then, I would have said things were okay. Looking back at how little I gave her to work with, I think she deserved a more generous conversation than okay.", "ch11-007"),
  beat("ch11-007", stages.messages, "nurulain",
    "What do you usually do when you're free? Meet your friends?", "ch11-008"),
  beat("ch11-008", stages.messages, "aleem-adult",
    "Sometimes. Depends if everyone's free.", "ch11-009"),
  beat("ch11-009", stages.messages, "adult-aleem",
    "That was the sort of answer I sent. Accurate. Finished. No question travelling back with it. Nurul would find another opening: something about me, something about the people I mentioned. I would answer that too. From my side of the phone, I thought I was allowing things to happen naturally. She was doing most of the happening.", "ch11-010"),
  beat("ch11-010", stages.messages, "adult-aleem",
    "My excuse was familiar to me. If a girl wasn't interested, I didn't want to pour my effort and energy into persuading her. I had done enough waiting beside one-sided conversations. But I had brought that caution into a conversation with someone who kept showing up. I was watching for her interest while doing very little to show my own.", "ch11-011"),
  beat("ch11-011", stages.messages, "adult-aleem",
    "Much later, Nurul told me what she had thought of those early messages. She had wondered whether I was a narcissist. I winced when I heard it. She was describing her first impression of a man who answered questions about himself and scarcely asked about her. I understood how I had given her that impression.", "ch11-012"),
  beat("ch11-012", stages.invitation, "nurulain",
    "Would you like to meet? We can eat and talk properly.", "ch11-013"),
  beat("ch11-013", stages.invitation, "adult-aleem",
    "She initiated our first meeting. Even that small suggestion reached me more deeply than she could have known. Someone wanted to spend time with me enough to ask. I accepted, pleased and still a little careful, and we arranged to eat at Yakiniku. At least there, my replies would have a face and a voice attached to them.", "ch11-014"),
  beat("ch11-014", stages.yakiniku, "adult-aleem",
    "Across the grill, Nurul became more than the person keeping my phone conversation alive. Her smile was bright. I could see when a thought amused her before she said it, and hear the small changes in her voice that a message couldn't carry. We settled opposite each other with beef to grill and plenty we still didn't know.", "ch11-015"),
  beat("ch11-015", stages.yakinikuCurious, "nurulain",
    "So. Are you always this quiet, or only when you're texting?", "ch11-016"),
  beat("ch11-016", stages.yakinikuAmused, "aleem-adult",
    "Is my texting that bad?", "ch11-017"),
  beat("ch11-017", stages.yakinikuAmused, "nurulain",
    "You answer the question very efficiently.", "ch11-018"),
  beat("ch11-018", stages.yakinikuAmused, "adult-aleem",
    "I laughed, partly because I could hear the space she had politely left after that sentence. The beef sizzled between us. I turned a piece and found it easier to admit my awkwardness with something ordinary to do with my hands. She waited, smiling, and I managed more than the few words I would have sent from home.", "ch11-019"),
  beat("ch11-019", stages.yakinikuCurious, "aleem-adult",
    "I think I hold back at first. I don't want to keep bothering someone if she's not interested. But I can see how that looks from your side.", "ch11-020"),
  beat("ch11-020", stages.yakinikuCurious, "nurulain",
    "If I ask you something, you can ask me also. I don't mind answering.", "ch11-021"),
  beat("ch11-021", stages.yakinikuWarm, "adult-aleem",
    "There was nothing difficult about her request. Still, hearing it aloud made me notice how often I had treated a reply as the end of my part. I asked something back. She answered. A detail led to another question, and for a while neither of us needed to search for the next subject. We only had to remember the food.", "ch11-yakiniku-pause"),
  beat("ch11-yakiniku-pause", stages.yakinikuAmused, "adult-aleem",
    "Once, I stopped halfway through an answer to turn the beef. By the time I looked up, I had lost the rest of the sentence. She reminded me where I had been. I liked that: we could interrupt a conversation to deal with dinner, laugh about it, and find our way back together.", "ch11-022"),
  beat("ch11-022", stages.yakinikuWarm, "adult-aleem",
    "The grill gave us pauses without making them feel empty. We could stop to eat, look down to see what was ready, then return to a sentence. Nurul seemed more at ease as we talked. She would tell me that meeting face to face was much better. I was glad she had given the person behind those dry messages a chance.", "ch11-023"),
  beat("ch11-023", stages.yakinikuWarm, "aleem-adult",
    "I want to say something. When you greet me, or start a conversation... I really appreciate it. It may seem small to you, but it means a lot to me.", "ch11-024"),
  beat("ch11-024", stages.yakinikuWarm, "adult-aleem",
    "I didn't give her my whole history across that table. I simply wanted her to know I noticed. I had grown used to being the one reaching, keeping a thread alive, finding a reason to speak. With Nurul, a conversation could arrive because she had thought of me. It felt like a breath of fresh air.", "ch11-025"),
  beat("ch11-025", stages.yakinikuWarm, "adult-aleem",
    "That was when I first wondered whether she could be the one. The thought arrived quietly while she was still right there, talking to me. I didn't need to turn it into an announcement. I wanted another meal, another conversation, more chances to know the woman who had made this one possible.", "ch11-choice-reciprocity"),
  choice("ch11-choice-reciprocity", "chapter-11", stages.yakinikuWarm,
    "What did her effort help me recognise?", [
      { id: "reciprocity-greeting", label: "A small greeting could make me feel wanted.", next: "ch11-reciprocity-greeting" },
      { id: "reciprocity-return", label: "I wanted to return the interest she showed me.", next: "ch11-reciprocity-return" },
      { id: "reciprocity-ease", label: "I could enjoy being here without proving myself.", next: "ch11-reciprocity-ease" },
    ]),
  beat("ch11-reciprocity-greeting", stages.yakinikuWarm, "adult-aleem",
    "Her hello had already changed the shape of an ordinary day. I wanted to remember that feeling when it was my turn to reach for the phone: how good it was to know someone had made a little room for me.", "ch11-reciprocity-join"),
  beat("ch11-reciprocity-return", stages.yakinikuWarm, "adult-aleem",
    "She had given me so many chances to speak. I wanted to know what she would say if I gave her the same room. There was a person across from me, with a whole life I had barely begun to ask about.", "ch11-reciprocity-join"),
  beat("ch11-reciprocity-ease", stages.yakinikuWarm, "adult-aleem",
    "I had spent so long trying to become someone another person might choose. Here I could eat, laugh at myself, and finish a thought. I wanted to stay present enough to enjoy that ease with her.", "ch11-reciprocity-join"),
  beat("ch11-reciprocity-join", stages.meetings, "adult-aleem",
    "We met again. Then again. The first meeting became something we could refer back to, instead of the only thing we knew about being together. A familiar smile greeted me. Conversation picked up from something we had mentioned before. I began looking forward to her company in the middle of otherwise ordinary days.", "ch11-026"),
  beat("ch11-026", stages.meetings, "adult-aleem",
    "Getting to know her didn't happen in one long, revealing conversation. It came in smaller pieces: an answer she expanded because I had asked, a joke I understood more quickly now, a pause I could leave alone. I was still learning to be curious. Sometimes I noticed a question only after I had already started talking about myself again.", "ch11-meetings-listening"),
  beat("ch11-meetings-listening", stages.meetings, "adult-aleem",
    "I could catch myself and return to what she had been saying. It was a little awkward sometimes. I would ask her to go on, then wait while she found the thread again. But I wanted her to finish. I was beginning to understand how much of a person I could miss while preparing my own next sentence.", "ch11-027"),
  beat("ch11-027", stages.distance, "adult-aleem",
    "And I could still feel a distance between us. We could have a good time together and reach a point where she held something back. I pictured a wall in front of her, though I knew that was my way of describing what I felt. Nurul had her own reasons for being careful. I didn't yet know all of them.", "ch11-028"),
  beat("ch11-028", stages.distance, "adult-aleem",
    "I wanted her to feel safe with me. Wanting it didn't make it happen immediately. I couldn't count our meetings and decide she had been given enough time. So I kept showing up, and tried to leave space around what she wasn't ready to share. The person who had been patient with my dry replies deserved patience from me too.", "ch11-029"),
  beat("ch11-029", stages.question, "adult-aleem",
    "Then, in our messages, she asked a question that made me sit with the phone for a moment. We had been seeing each other, becoming part of each other's time. She wanted to know where we were going with it.", "ch11-030"),
  beat("ch11-030", stages.question, "nurulain",
    "What's next?", "ch11-031"),
  beat("ch11-031", stages.question, "adult-aleem",
    "I thought about giving her another reassuring sentence. Instead, I found myself considering something I had never done before. I wanted to meet her parents. I wanted to sit with the people who knew and loved her, let them know who I was, and show her that my interest had a sincere direction.", "ch11-032"),
  beat("ch11-032", stages.question, "aleem-adult",
    "I'd like to meet your parents, if you're comfortable with that. I'm serious about getting to know you. I would like to know them too.", "ch11-033"),
  beat("ch11-033", stages.herPerspective, "adult-aleem",
    "At the time, I thought I had made my intention clearer. I didn't know that my answer had made her feel even more intimidated. She told me later that it had felt as though I might force my way into her life. I had heard her question as an opening; she still needed to feel that she had room to choose.", "ch11-034"),
  beat("ch11-034", stages.patience, "adult-aleem",
    "Remembering that now, I can understand both sides of the message. I was trying to offer something solid. From where she stood, it was a large step arriving while she was still learning to trust me. Sincerity needed to be felt in the way I treated her, including how I made room for her uncertainty.", "ch11-035"),
  beat("ch11-035", stages.patience, "adult-aleem",
    "We arranged the meeting for after my trip to Kazakhstan. The plan gave us something ahead of us, and some time before it arrived. I wanted the evening to go well. More than that, I wanted us to keep getting to know each other in the days before it. Meeting her parents couldn't do that work for us.", "ch11-choice-patience"),
  choice("ch11-choice-patience", "chapter-11", stages.patience,
    "What did patience need to mean here?", [
      { id: "patience-pace", label: "Give her room to find her own pace.", next: "ch11-patience-pace" },
      { id: "patience-listen", label: "Listen when an answer was hard to give.", next: "ch11-patience-listen" },
      { id: "patience-consistent", label: "Let ordinary days show that I meant it.", next: "ch11-patience-consistent" },
    ]),
  beat("ch11-patience-pace", stages.patience, "adult-aleem",
    "My readiness couldn't decide hers. I could tell her what I hoped for, then leave enough room for an honest answer. I wanted whatever grew between us to be something she could step towards willingly.", "ch11-patience-join"),
  beat("ch11-patience-listen", stages.patience, "adult-aleem",
    "I knew how easily a careful reply could make me anxious. I wanted to hear her properly even then. If something felt too much, she should be able to tell me without having to manage my disappointment first.", "ch11-patience-join"),
  beat("ch11-patience-consistent", stages.patience, "adult-aleem",
    "One serious proposal wasn't the whole of sincerity. There would be another greeting, another question, another chance to remember something she had said. Those were things I could give my attention to now.", "ch11-patience-join"),
  beat("ch11-patience-join", stages.departure, "adult-aleem",
    "I left for Kazakhstan with our conversation still open. Travel made the days different, but she remained someone I wanted to speak to within them. When a quiet moment came, I found myself wondering what her day had been like. This time the thought became a question I actually sent.", "ch11-036"),
  beat("ch11-036", stages.kazakhstan, "aleem-adult",
    "How was your day? You mentioned something earlier. How did that go?", "ch11-037"),
  beat("ch11-037", stages.kazakhstan, "adult-aleem",
    "It was a small change on the screen. Inside me, it felt larger. I wanted the answer for its own sake. When she replied, I read what she said instead of only feeling relieved that she had replied. There was something to follow up on, something to remember when we next spoke.", "ch11-038"),
  beat("ch11-038", stages.kazakhstanQuiet, "adult-aleem",
    "I could picture her beyond the conversation with me now: having her own day, dealing with things I wasn't there to see, deciding what she wanted to share. I asked about those things. Sometimes I told her something from the trip, and she asked more. Our messages began to feel like a place we both brought our lives to.", "ch11-kazakhstan-answer"),
  beat("ch11-kazakhstan-answer", stages.kazakhstanQuiet, "adult-aleem",
    "Back at the accommodation, I would sit with a reply a little longer. If I hadn't understood something, I could ask what she meant. I didn't have to offer an immediate solution or turn it into my own similar story. Sometimes she only needed someone to follow what had happened and care enough to hear the rest.", "ch11-039"),
  beat("ch11-039", stages.kazakhstan, "nurulain",
    "You remembered?", "ch11-040"),
  beat("ch11-040", stages.kazakhstan, "aleem-adult",
    "Yes. I wanted to know how it turned out.", "ch11-041"),
  beat("ch11-041", stages.kazakhstan, "adult-aleem",
    "Curiosity became the key. I had been so occupied with whether someone would choose me that I could forget to learn who she was. Wanting to know Nurul gave my attention somewhere better to go. I could be interested without demanding a promise in return. I liked discovering how much more there was to talk about.", "ch11-042"),
  beat("ch11-042", stages.kazakhstan, "adult-aleem",
    "I told the friends travelling with me that I was seeing someone. Saying it aloud made me smile before I had finished. They were happy for me and wished us all the best. I let myself receive that warmth without immediately adding a warning about everything that might go wrong.", "ch11-043"),
  beat("ch11-043", stages.kazakhstanQuiet, "adult-aleem",
    "There were still stretches when we were each occupied with our own days. I could leave a message and return to the people around me. Then there would be something from her to read later. I liked that she was becoming part of my life while the rest of it continued around our conversation.", "ch11-044"),
  beat("ch11-044", stages.return, "adult-aleem",
    "As the trip came to a close, the meeting we had arranged became the next real thing on the calendar. Soon I would be sitting opposite her parents. I thought about what I wanted them to understand. There was no impressive version of myself I needed to invent. I wanted to be clear, respectful, and present.", "ch11-045"),
  beat("ch11-045", stages.parentsArrival, "adult-aleem",
    "We met at a restaurant. Her mother had a warm, rounded face; her father was a slim Malay uncle with an easy presence. They were two people curious about the man their daughter was seeing. Standing there before we settled at the table, I felt the importance of it without feeling that I had to hide behind it.", "ch11-046"),
  beat("ch11-046", stages.parentsDinner, "nurul-mother",
    "Come, Aleem. Sit. Have you been waiting long?", "ch11-047"),
  beat("ch11-047", stages.parentsDinner, "aleem-adult",
    "No, not long. Thank you for meeting me.", "ch11-048"),
  beat("ch11-048", stages.parentsDinner, "nurul-father",
    "So, you've just come back from your trip?", "ch11-049"),
  beat("ch11-049", stages.parentsDinner, "adult-aleem",
    "We began there, with something straightforward. I told them about having been away with friends. They asked about me, about work and the shape of my ordinary life. I answered without looking to Nurul to finish every sentence for me. When I needed a moment to think, I took one and continued.", "ch11-parents-listening"),
  beat("ch11-parents-listening", stages.parentsDinner, "adult-aleem",
    "I asked them questions too. As they spoke, I could see Nurul listening to familiar voices from a place that was new to me. I liked being allowed into that little circle. There was more to knowing her than the time we spent alone together. Here were people for whom she had never been a recent introduction.", "ch11-050"),
  beat("ch11-050", stages.parentsDinner, "nurul-mother",
    "And how has it been, getting to know Nurul?", "ch11-051"),
  beat("ch11-051", stages.parentsDinner, "aleem-adult",
    "Good. I'm happy I met her. She's made a lot of effort to know me. At the beginning my messages were very short, so I think she had quite a difficult job.", "ch11-052"),
  beat("ch11-052", stages.parentsDinner, "nurulain",
    "At least you know now.", "ch11-053"),
  beat("ch11-053", stages.parentsDinner, "adult-aleem",
    "I looked towards her and smiled. A little laughter travelled around the table, and the conversation felt easier afterwards. I could admit something imperfect about myself and remain there. Her parents listened with the ordinary curiosity of people trying to place a new face within the life of someone they loved.", "ch11-054"),
  beat("ch11-054", stages.parentsDinner, "nurul-father",
    "And what are you hoping for, with the two of you?", "ch11-055"),
  beat("ch11-055", stages.parentsDinner, "aleem-adult",
    "I'm serious about knowing her. I wanted to meet you because you're part of her life. I hope we can build towards a future together, at a pace we're both comfortable with.", "ch11-056"),
  beat("ch11-056", stages.parentsDinner, "adult-aleem",
    "I meant it, and I could hear that in my own voice. I didn't have every future detail ready. I could tell them why I was here. Around that answer, we went on having dinner: listening, eating, asking another question when there was room. The evening had space for everyone at the table.", "ch11-057"),
  beat("ch11-057", stages.parentsAfter, "adult-aleem",
    "Nurul would later tell me that seeing me there changed something for her. She saw my confidence, and finally felt the affection behind what I was doing. What had first seemed intimidating began to make sense as sincerity. I was serious about getting to know her and being with her. That was what reached her during the conversation.", "ch11-058"),
  beat("ch11-058", stages.parentsAfter, "adult-aleem",
    "I treasure that part of her account because I hadn't been able to see it happening inside her. I had simply tried to speak honestly to two kind people. Later, knowing what the evening had meant to her, I felt grateful that she had let me come, and that we had given each other the time to understand it.", "ch11-059"),
  beat("ch11-059", stages.pier, "adult-aleem",
    "The following weekend, we met again. We sat by the pier near the Kallang River and watched the sunset. Light stretched across the water, shifting as the surface moved. For a while, admiring it together was enough. I was glad to be beside her with no table between us and nowhere our conversation had to arrive.", "ch11-060"),
  beat("ch11-060", stages.pier, "nurulain",
    "It's nice here.", "ch11-061"),
  beat("ch11-061", stages.pier, "aleem-adult",
    "Yeah. I'm glad we came.", "ch11-062"),
  beat("ch11-062", stages.pierListening, "adult-aleem",
    "I began telling her about my past. One part led to another: the times I had hoped too quickly, the times I had stayed too long, the hurt I had carried into the next beginning. She was learning where I had been. I was hearing myself describe it without feeling that I had fallen back into it.", "ch11-pier-past"),
  beat("ch11-pier-past", stages.pierListening, "aleem-adult",
    "Sometimes I kept hoping even when the answer was already there. I thought if I did enough, or waited long enough, things might change. By the end I was tired of being hurt, but I was also tired of the way I kept living inside that hope.", "ch11-063"),
  beat("ch11-063", stages.pierListening, "adult-aleem",
    "I told her about being so tired of love that I had almost stopped wanting to try. About going for Umrah, and the relief I found in Masjidil Nabawi. I could still remember the breath leaving me. Sitting beside the river, I paused, surprised that I had brought her all the way into that memory.", "ch11-pier-surprise"),
  beat("ch11-pier-surprise", stages.pierListening, "aleem-adult",
    "Sorry. I didn't realise how much I was going to say.", "ch11-064"),
  beat("ch11-064", stages.pierListening, "nurulain",
    "You can take your time. I'm listening.", "ch11-065"),
  beat("ch11-065", stages.pierMoved, "adult-aleem",
    "I looked at her. There was no need to hurry through the difficult part so we could return to something pleasant. She let me find the next sentence. I had imagined openness as a difficult thing I would one day prepare myself to do. Here I was, already doing it, with someone who wanted to hear me.", "ch11-pier-quiet"),
  beat("ch11-pier-quiet", stages.pierMoved, "adult-aleem",
    "For a moment I watched the light on the water instead. I could feel how much I had said, and how calm it was between us afterwards. The stories hadn't made her look at me as though I belonged somewhere else. When I turned back towards her, I still felt welcome beside her.", "ch11-choice-openness"),
  choice("ch11-choice-openness", "chapter-11", stages.pierMoved,
    "How could I tell her what this moment meant?", [
      { id: "openness-surprise", label: "I'm surprised I can share this with you.", next: "ch11-openness-surprise" },
      { id: "openness-grateful", label: "I'm grateful you're here to listen.", next: "ch11-openness-grateful" },
      { id: "openness-ready", label: "I finally feel ready for something new.", next: "ch11-openness-ready" },
    ]),
  beat("ch11-openness-surprise", stages.pierMoved, "aleem-adult",
    "I'm surprised I'm telling you all this. I didn't come here with a speech prepared. I just started talking, and it felt okay to keep going. That means a lot to me.", "ch11-openness-join"),
  beat("ch11-openness-grateful", stages.pierMoved, "aleem-adult",
    "Thank you for listening like this. I know some of it is difficult to hear. I'm really grateful I can sit here with you and say it in my own time.", "ch11-openness-join"),
  beat("ch11-openness-ready", stages.pierMoved, "aleem-adult",
    "For a long time I kept bringing the same hurt into everything. I feel ready to have something new in my life now. And I'm happy that getting to know you is part of that.", "ch11-openness-join"),
  beat("ch11-openness-join", stages.pierWarm, "adult-aleem",
    "The water kept moving below us. I thought about the timing of her arrival: after I had found some peace, after I had stopped trying to reopen an old ending. I had decided to begin a new book. Then Mariam had turned towards me, and a name I didn't know had entered my life.", "ch11-066"),
  beat("ch11-066", stages.pierWarm, "aleem-adult",
    "I'm really happy you came into my life when you did. After Umrah, I felt like I could begin again. Then I met you. It feels like the pieces have been clicking together.", "ch11-067"),
  beat("ch11-067", stages.pierWarm, "adult-aleem",
    "That was how it felt, sitting there with her. I couldn't explain every part of His plans. I could feel my gratitude for the path that had brought me to this evening: the release, the introduction, her persistence, and our growing willingness to meet each other honestly. I wanted her to know how happy I was that she was here.", "ch11-pier-gratitude"),
  beat("ch11-pier-gratitude", stages.pierWarm, "adult-aleem",
    "I remembered her asking whether we could meet, the questions she had kept finding, the way she had stayed in our first conversation when I barely knew how to help it along. Now I knew more of her, and I wanted to keep knowing her. The words I needed were simple enough to say without rehearsing them.", "ch11-068"),
  beat("ch11-068", stages.pierWarm, "aleem-adult",
    "Nurul, I love you.", "ch11-069"),
  beat("ch11-069", stages.confession, "nurulain",
    "I love you too, Aleem.", "ch11-070"),
  beat("ch11-070", stages.confession, "adult-aleem",
    "We confessed our love to each other that evening by the river. I could hear her words without searching them for a smaller meaning, without needing to persuade myself they had happened. The sunset continued around us. Beside me was someone I loved, telling me that she loved me too.", "epilogue-001"),
] as const satisfies readonly StoryNode[];
