import type { StoryNode } from "../engine/types";
import { choice, line } from "./helpers";
import { stages } from "./stages";

export const chapterSixNodes = [
  line(
    "ch6-001",
    "chapter-6",
    stages.nsOpening,
    "adult-aleem",
    "National Service began before the relief of my A-Level results had settled into confidence. The uniform gave every hour a purpose: wake, train, wait, move, clean, repeat. It was difficult, but difficulty with instructions felt safer than uncertainty without them.",
    "ch6-002",
  ),
  line(
    "ch6-002",
    "chapter-6",
    stages.nsOpening,
    "adult-aleem",
    "By 2016, I could point to evidence that I was disciplined and capable. I could endure exhaustion, learn quickly, and be useful to the people beside me. None of that automatically repaired the private rules I had built around affection.",
    "ch6-003",
  ),
  line(
    "ch6-003",
    "chapter-6",
    stages.nsOpening,
    "aleem-young-adult",
    "Do the work in front of you. Do not expect too much from anyone. That is how you avoid being surprised.",
    "ch6-004",
  ),
  line(
    "ch6-004",
    "chapter-6",
    stages.nsOpening,
    "adult-aleem",
    "I called that rule maturity. Much of it was fear dressed in practical language. Earlier rejection had already encouraged an unfair suspicion of Malay girls; I had challenged the thought sometimes, but I had not removed its roots.",
    "ch6-005",
  ),
  line(
    "ch6-005",
    "chapter-6",
    stages.nsOpening,
    "adult-aleem",
    "Camp compressed the world. Inside, rank, routine, and the next book-out mattered. Outside, family meals and ordinary messages acquired the brightness of another country. A weekend could feel enormous because it belonged to me for only a little while.",
    "ch6-006",
  ),
  line(
    "ch6-006",
    "chapter-6",
    stages.rayaArrival,
    "adult-aleem",
    "During Hari Raya, my family visited one of my father's good friends. Nadiah was connected through that family's wider circle—the niece of his friend's brother—a relationship distant enough that we had never properly met.",
    "ch6-007",
  ),
  line(
    "ch6-007",
    "chapter-6",
    stages.rayaArrival,
    "adult-aleem",
    "The house carried the familiar movement of visiting: greetings crossing in the doorway, plates being replenished before they were empty, children migrating between rooms, adults rebuilding conversations from the previous year.",
    "ch6-008",
  ),
  line(
    "ch6-008",
    "chapter-6",
    stages.rayaArrival,
    "aleem-young-adult",
    "Salam. Sorry—where should I put these? The table is already losing the battle.",
    "ch6-009",
  ),
  line(
    "ch6-009",
    "chapter-6",
    stages.rayaFirstSight,
    "adult-aleem",
    "Then I looked across the room and saw Nadiah. She wore a hijab that framed her face softly, and for one suspended instant every other detail seemed to move behind her. She looked up at almost the same moment.",
    "ch6-010",
  ),
  line(
    "ch6-010",
    "chapter-6",
    stages.rayaFirstSight,
    "adult-aleem",
    "We held each other's gaze long enough for me to feel noticed and briefly embarrassed by how completely I had stopped listening. I knew almost nothing about her. Attraction rushed ahead and offered to fill every empty space.",
    "ch6-011",
  ),
  line(
    "ch6-011",
    "chapter-6",
    stages.rayaAleemAwed,
    "aleem-young-adult",
    "She is beautiful. Not just beautiful—there is something peaceful about her. The hijab suits her so perfectly.",
    "ch6-012",
  ),
  line(
    "ch6-012",
    "chapter-6",
    stages.rayaAleemAwed,
    "adult-aleem",
    "That was the first image I made of Nadiah: beauty, modesty, calm, certainty. Her hijab was part of her appearance that day, not evidence about the whole of her character. I did not yet understand how much meaning I had assigned without permission.",
    "ch6-013",
  ),
  line(
    "ch6-013",
    "chapter-6",
    stages.rayaNadiahWarm,
    "nadiah",
    "You look like somebody just asked you a question and you missed all of it.",
    "ch6-014",
  ),
  line(
    "ch6-014",
    "chapter-6",
    stages.rayaNadiahWarm,
    "aleem-young-adult",
    "That is possible. I have been in camp too long. Civilian conversations move very fast.",
    "ch6-015",
  ),
  line(
    "ch6-015",
    "chapter-6",
    stages.rayaNadiahWarm,
    "adult-aleem",
    "We spoke only briefly, surrounded by relatives and interrupted by the needs of the room. She was warm and amused, and I carried those few minutes away as though they contained a promise neither of us had made.",
    "ch6-016",
  ),
  line(
    "ch6-016",
    "chapter-6",
    stages.nsOpening,
    "adult-aleem",
    "Back in camp, her face returned during the quiet edges of routine. I wondered whether she remembered me, then criticised myself for wondering. Wanting to reach out felt hopeful and dangerous in equal measure.",
    "ch6-017",
  ),
  line(
    "ch6-017",
    "chapter-6",
    stages.nsOpening,
    "aleem-young-adult",
    "Wait until Passing Out Parade. Finish this first. If the feeling survives all these weeks, maybe it deserves a real conversation.",
    "ch6-018",
  ),
  line(
    "ch6-018",
    "chapter-6",
    stages.nsPopGate,
    "adult-aleem",
    "Passing Out Parade arrived in heat, rehearsed movement, and the sight of families searching formations for one familiar face. Completion did not transform me, but it made the future feel briefly negotiable.",
    "ch6-019",
  ),
  line(
    "ch6-019",
    "chapter-6",
    stages.nsPopGate,
    "adult-aleem",
    "Afterward, Nadiah and I began talking properly. The first messages were cautious, then surprisingly easy. We moved from polite updates to conversations that followed me through bus rides and the final minutes before sleep.",
    "ch6-020",
  ),
  line(
    "ch6-020",
    "chapter-6",
    stages.nsPopGate,
    "nadiah",
    "So now that you have passed out, are you finally allowed to have a personality again?",
    "ch6-021",
  ),
  line(
    "ch6-021",
    "chapter-6",
    stages.nsPopGate,
    "aleem-young-adult",
    "Limited issue only. I need to return it before every book-in.",
    "ch6-022",
  ),
  line(
    "ch6-022",
    "chapter-6",
    stages.nsBunkWarm,
    "adult-aleem",
    "The dialogue here is reconstructed from memory, and the moments that follow are composites of many ordinary exchanges. I remember their emotional shape more reliably than exact wording: mutual attention, anticipation, and the comfort of being expected.",
    "ch6-023",
  ),
  line(
    "ch6-023",
    "chapter-6",
    stages.nsBunkWarm,
    "nadiah",
    "Message when you reach camp. I know you will be busy; I just want to know the journey was okay.",
    "ch6-024",
  ),
  line(
    "ch6-024",
    "chapter-6",
    stages.nsBunkWarm,
    "aleem-young-adult",
    "Reached. The bunk is exactly as glamorous as I left it. I already miss talking without checking the time.",
    "ch6-025",
  ),
  line(
    "ch6-025",
    "chapter-6",
    stages.nsBunkWarm,
    "adult-aleem",
    "We called ourselves a couple. We behaved like one: affectionate messages, planned meetings, reassurance across book-ins, small claims on each other's days. The warmth was real. So was a gap we failed to examine.",
    "ch6-026",
  ),
  line(
    "ch6-026",
    "chapter-6",
    stages.relationshipMontage,
    "adult-aleem",
    "We never had one reliable conversation defining exclusivity, unfinished attachments, or what being together required from each of us. I assumed the word couple had completed that work. Assumption felt romantic while everything seemed secure.",
    "ch6-027",
  ),
  line(
    "ch6-027",
    "chapter-6",
    stages.relationshipMontage,
    "adult-aleem",
    "Our relationship lived mostly in modest pieces: a call before lights-out, her message waiting after training, a public meal where neither of us wanted to be first to say the evening should end.",
    "ch6-028",
  ),
  line(
    "ch6-028",
    "chapter-6",
    stages.relationshipMontage,
    "nadiah",
    "You always sound surprised when I remember something you told me.",
    "ch6-029",
  ),
  line(
    "ch6-029",
    "chapter-6",
    stages.relationshipMontage,
    "aleem-young-adult",
    "I am adjusting to being important enough for somebody to remember the small things.",
    "ch6-030",
  ),
  line(
    "ch6-030",
    "chapter-6",
    stages.relationshipMontage,
    "adult-aleem",
    "She did remember. She made space for me, and I made space for her. Whatever remained unresolved elsewhere in her life does not make every tender moment counterfeit. Memory becomes less honest when pain is allowed to erase all preceding care.",
    "ch6-031",
  ),
  line(
    "ch6-031",
    "chapter-6",
    stages.nsBunkWarm,
    "adult-aleem",
    "Months passed. I began treating the relationship as an answer to older fears: here was a Malay woman who seemed to contradict every suspicious rule I had built. Instead of releasing the category, I made Nadiah its exception.",
    "ch6-032",
  ),
  line(
    "ch6-032",
    "chapter-6",
    stages.nsBunkWarm,
    "adult-aleem",
    "That distinction mattered later. If one person carries the burden of disproving a prejudice, her mistake can appear to prove it again. I had placed Nadiah inside an argument she did not know I was conducting.",
    "ch6-033",
  ),
  line(
    "ch6-033",
    "chapter-6",
    stages.nsBunkSocialReveal,
    "adult-aleem",
    "One day in camp, Aisyah—a pseudonym for Nadiah's friend—sent me a message. It began with a question that seemed small enough to answer casually: had I seen Nadiah's Instagram story from Universal Studios Singapore?",
    "ch6-034",
  ),
  line(
    "ch6-034",
    "chapter-6",
    stages.nsBunkSocialReveal,
    "aleem-young-adult",
    "USS? No. She didn't tell me she was going. There is nothing on her story.",
    "ch6-035",
  ),
  line(
    "ch6-035",
    "chapter-6",
    stages.nsBunkSocialReveal,
    "aisyah",
    "It was posted to Close Friends. I thought you would be included. I'll send what I saw, but I don't want to pretend I know the whole situation.",
    "ch6-036",
  ),
  line(
    "ch6-036",
    "chapter-6",
    stages.closeFriendsReveal,
    "adult-aleem",
    "The screenshot arrived inside our chat. It showed Nadiah at USS beside another man. Aisyah identified him as Chinese and as someone from Nadiah's past. Nadiah was not wearing hijab in the image.",
    "ch6-037",
  ),
  line(
    "ch6-037",
    "chapter-6",
    stages.closeFriendsReveal,
    "aleem-young-adult",
    "She hid this from me. She even took off her hijab for him. What else could this mean?",
    "ch6-038",
  ),
  line(
    "ch6-038",
    "chapter-6",
    stages.nsBunkShocked,
    "adult-aleem",
    "I did not know why Nadiah was not wearing hijab that day, and the screenshot could not tell me. Connecting that choice to the man beside her was my immediate inference, not an explanation she gave.",
    "ch6-choice-discovery",
  ),
  choice(
    "ch6-choice-discovery",
    "chapter-6",
    stages.nsBunkShocked,
    "What did Aleem do with the first shock?",
    [
      {
        id: "discovery-ask",
        label: "Ask Aisyah what she actually knows.",
        next: "ch6-discovery-ask-001",
      },
      {
        id: "discovery-inspect",
        label: "Inspect the screenshot again and again.",
        next: "ch6-discovery-inspect-001",
      },
      {
        id: "discovery-verdict",
        label: "Decide the image already explains everything.",
        next: "ch6-discovery-verdict-001",
      },
    ],
  ),
  line(
    "ch6-discovery-ask-001",
    "chapter-6",
    stages.nsBunkSocialReveal,
    "aleem-young-adult",
    "Did she tell you she was going with him? Do you know whether they are together, or only what is in this picture?",
    "ch6-discovery-ask-002",
  ),
  line(
    "ch6-discovery-ask-002",
    "chapter-6",
    stages.nsBunkSocialReveal,
    "aisyah",
    "I know they have history, and I saw the story. I don't know what they agreed today. You need to ask Nadiah, not let me answer for her.",
    "ch6-discovery-join",
  ),
  line(
    "ch6-discovery-inspect-001",
    "chapter-6",
    stages.closeFriendsReveal,
    "adult-aleem",
    "I enlarged the screenshot, returned it to normal size, then enlarged it again. Every gesture and inch of distance became evidence in a trial whose witnesses could not speak.",
    "ch6-discovery-inspect-002",
  ),
  line(
    "ch6-discovery-inspect-002",
    "chapter-6",
    stages.nsBunkShocked,
    "adult-aleem",
    "Repeated inspection created familiarity, not knowledge. The image never changed. My interpretation became more certain simply because I had rehearsed it so many times.",
    "ch6-discovery-join",
  ),
  line(
    "ch6-discovery-verdict-001",
    "chapter-6",
    stages.nsBunkShocked,
    "aleem-young-adult",
    "I am not stupid. People hide things because the truth would expose them. Asking will only give her time to make the story sound harmless.",
    "ch6-discovery-verdict-002",
  ),
  line(
    "ch6-discovery-verdict-002",
    "chapter-6",
    stages.nsBunkControlled,
    "adult-aleem",
    "A verdict offered relief from not knowing. It also ensured that every answer would arrive already classified as confession, excuse, or lie. Certainty protected the wound by closing the door to information.",
    "ch6-discovery-join",
  ),
  line(
    "ch6-discovery-join",
    "chapter-6",
    stages.nsBunkShocked,
    "adult-aleem",
    "However I held the phone, three facts remained: Nadiah had gone to USS, the private story did not include me, and she appeared beside a man with whom Aisyah said she had history. Everything else still required a conversation.",
    "ch6-039",
  ),
  line(
    "ch6-039",
    "chapter-6",
    stages.nsBunkShocked,
    "adult-aleem",
    "Shock moved through my body before thought could organise it. My throat tightened. Heat climbed beneath my uniform. I wanted to cry in front of everyone and wanted even more fiercely not to be seen crying.",
    "ch6-040",
  ),
  line(
    "ch6-040",
    "chapter-6",
    stages.nsBunkControlled,
    "aleem-young-adult",
    "Not here. Breathe. Put the phone down. Finish what you need to finish, then talk when you can form a sentence.",
    "ch6-041",
  ),
  line(
    "ch6-041",
    "chapter-6",
    stages.nsBunkControlled,
    "adult-aleem",
    "I waited a few hours. Calming down did not make me neutral; it only gave my hurt a quieter voice. When I finally messaged Nadiah, restraint and accusation travelled together in every line.",
    "ch6-042",
  ),
  line(
    "ch6-042",
    "chapter-6",
    stages.nsBunkControlled,
    "aleem-young-adult",
    "Aisyah sent me your Close Friends story. I didn't know you were at USS, and I saw who you were with. I need you to tell me what is happening.",
    "ch6-043",
  ),
  line(
    "ch6-043",
    "chapter-6",
    stages.nsBunkControlled,
    "nadiah",
    "I should have told you I was going, and I should have spoken about him before you had to see anything through somebody else. I understand why this hurt you.",
    "ch6-choice-confrontation",
  ),
  choice(
    "ch6-choice-confrontation",
    "chapter-6",
    stages.nsBunkControlled,
    "Which question did Aleem need answered first?",
    [
      {
        id: "confrontation-couple",
        label: "Were we ever truly a couple?",
        next: "ch6-confrontation-couple-001",
      },
      {
        id: "confrontation-waiting",
        label: "Were you waiting for your first love?",
        next: "ch6-confrontation-waiting-001",
      },
      {
        id: "confrontation-disclosure",
        label: "Why did I have to learn from someone else?",
        next: "ch6-confrontation-disclosure-001",
      },
    ],
  ),
  line(
    "ch6-confrontation-couple-001",
    "chapter-6",
    stages.nsBunkControlled,
    "aleem-young-adult",
    "When we called ourselves a couple, did that mean the same thing to you? Was I the only one treating this as exclusive?",
    "ch6-confrontation-couple-002",
  ),
  line(
    "ch6-confrontation-couple-002",
    "chapter-6",
    stages.nsBunkHurt,
    "nadiah",
    "I cared about us and I called us a couple too. We should have defined what that meant instead of assuming. My feelings elsewhere were unresolved, and I was not clear with you.",
    "ch6-confrontation-join",
  ),
  line(
    "ch6-confrontation-waiting-001",
    "chapter-6",
    stages.nsBunkControlled,
    "aleem-young-adult",
    "Were you waiting for him to decide while I stayed beside you? Was I here only because he had not confirmed what he felt?",
    "ch6-confrontation-waiting-002",
  ),
  line(
    "ch6-confrontation-waiting-002",
    "chapter-6",
    stages.nsBunkHurt,
    "nadiah",
    "I did not begin this with a plan to use you. But he was my first love, and I had not resolved those feelings. I should have told you before we became this close.",
    "ch6-confrontation-join",
  ),
  line(
    "ch6-confrontation-disclosure-001",
    "chapter-6",
    stages.nsBunkControlled,
    "aleem-young-adult",
    "Why did Aisyah have to show me? Why wasn't I trusted with something that directly affected what I thought our relationship was?",
    "ch6-confrontation-disclosure-002",
  ),
  line(
    "ch6-confrontation-disclosure-002",
    "chapter-6",
    stages.nsBunkHurt,
    "nadiah",
    "You should have heard it from me. I avoided a difficult conversation until the silence became more hurtful than the truth. I am sorry for making you discover it this way.",
    "ch6-confrontation-join",
  ),
  line(
    "ch6-confrontation-join",
    "chapter-6",
    stages.nsBunkHurt,
    "adult-aleem",
    "Across the conversation, Nadiah acknowledged the central history: the other man was her first love. When she and I started talking, his feelings had not been confirmed, while her own attachment to him remained unresolved.",
    "ch6-044",
  ),
  line(
    "ch6-044",
    "chapter-6",
    stages.nsBunkHurt,
    "adult-aleem",
    "She did not give me the exact sentence, You were my backup. That was the meaning I made from the order of events: he was the person she wanted first, his uncertainty created space, and I had occupied it temporarily.",
    "ch6-045",
  ),
  line(
    "ch6-045",
    "chapter-6",
    stages.nsBunkHurt,
    "aleem-young-adult",
    "So I was never the main choice. I was the safe answer while you waited for the answer you actually wanted.",
    "ch6-046",
  ),
  line(
    "ch6-046",
    "chapter-6",
    stages.nsBunkHurt,
    "nadiah",
    "I understand why it feels that way. I did care for you. I also handled my uncertainty badly, and saying I cared does not undo what that cost you.",
    "ch6-047",
  ),
  line(
    "ch6-047",
    "chapter-6",
    stages.nsBunkHurt,
    "adult-aleem",
    "Her answer did not fit the clean categories I needed. Care and harm could exist in the same history. A person could be confused rather than calculating and still make choices that left somebody else devastated.",
    "ch6-048",
  ),
  line(
    "ch6-048",
    "chapter-6",
    stages.nsBunkHurt,
    "adult-aleem",
    "But that night, nuance felt like an attempt to reduce the injury. The image of the woman I believed I knew collapsed, and I treated the collapse as proof that the image had been deliberately constructed for me.",
    "ch6-049",
  ),
  line(
    "ch6-049",
    "chapter-6",
    stages.darkRoomCrying,
    "aleem-young-adult",
    "All Malay girls will turn out like this. Different face, same ending. I was stupid to believe she was different.",
    "ch6-050",
  ),
  line(
    "ch6-050",
    "chapter-6",
    stages.darkRoomCrying,
    "adult-aleem",
    "That thought was prejudice, not revelation. Nadiah's choices belonged to Nadiah. My pain deepened an unfair generalisation that had begun years earlier; it did not transform the generalisation into evidence about Malay women.",
    "ch6-051",
  ),
  line(
    "ch6-051",
    "chapter-6",
    stages.darkRoomCrying,
    "adult-aleem",
    "I cried for days—sometimes openly, more often when the room was dark enough to hide the effort of holding myself together. Sleep arrived late and released me early. Ordinary notifications could pull my stomach tight.",
    "ch6-052",
  ),
  line(
    "ch6-052",
    "chapter-6",
    stages.homeFamilySupport,
    "adult-aleem",
    "My family supported me without having a solution. Food appeared near me. Somebody stayed at the table when conversation was impossible. Their concern could not shorten grief, but it kept grief from becoming the only presence in the house.",
    "ch6-053",
  ),
  line(
    "ch6-053",
    "chapter-6",
    stages.homeFamilySupport,
    "aleem-young-adult",
    "I know everyone is trying. I just cannot switch this off because the day has moved on. Everything I believed about us keeps replaying with a different meaning.",
    "ch6-054",
  ),
  line(
    "ch6-054",
    "chapter-6",
    stages.nsCampNumb,
    "adult-aleem",
    "Service continued. Timetables did not pause to recognise heartbreak. I returned to camp, completed tasks, answered when called, and discovered that a person can function reliably while feeling absent from his own life.",
    "ch6-055",
  ),
  line(
    "ch6-055",
    "chapter-6",
    stages.nsCampNumb,
    "adult-aleem",
    "The practical lesson should have been about clarity: define a relationship, ask about unresolved attachments, and leave when trust cannot be rebuilt. Instead, I wrote a broader and more damaging rule.",
    "ch6-056",
  ),
  line(
    "ch6-056",
    "chapter-6",
    stages.nsCampNumb,
    "aleem-young-adult",
    "No more. I cannot trust Malay girls. If I never let another one close, this cannot happen to me again.",
    "ch6-057",
  ),
  line(
    "ch6-057",
    "chapter-6",
    stages.nsCampNumb,
    "adult-aleem",
    "Avoidance promised safety by turning ethnicity into a warning label. It also prevented any future person from being encountered as herself. I did not recognise the cost because withdrawal felt like the first decision I controlled.",
    "ch6-058",
  ),
  line(
    "ch6-058",
    "chapter-6",
    stages.ordGate,
    "adult-aleem",
    "Eventually, Operationally Ready Date arrived. I returned what belonged to the Army, carried out the familiar final procedures, and stepped beyond the gate with civilian time opening in front of me.",
    "ch6-059",
  ),
  line(
    "ch6-059",
    "chapter-6",
    stages.ordGate,
    "adult-aleem",
    "I had served, endured, and completed something demanding. I also left as a single man who believed heartbreak had exposed a truth about an entire community. Strength in one part of life had not corrected fear in another.",
    "ch6-060",
  ),
  line(
    "ch6-060",
    "chapter-6",
    stages.ordGate,
    "adult-aleem",
    "University waited next. I imagined new subjects, new friends, and a future large enough to leave the relationship behind. I did not yet know that what I carried would announce itself before the first week was over.",
    "epilogue-001",
  ),
] as const satisfies readonly StoryNode[];
