import type { StoryNode } from "../engine/types";
import { choice, line } from "./helpers";
import { stages } from "./stages";

export const chapterThreeNodes = [
  line(
    "ch3-001",
    "chapter-3",
    stages.jcFamilyPressure,
    "adult-aleem",
    "The morning after disappointment is rarely dramatic. The sun still reaches the dining table. Cups still clink. Then somebody asks what comes next, and the question makes the whole room feel smaller.",
    "ch3-002",
  ),
  line(
    "ch3-002",
    "chapter-3",
    stages.jcFamilyPressure,
    "adult-aleem",
    "My family wanted reassurance that one poor result had not closed every respectable route. Their concern arrived as comparisons, repeated suggestions, and questions from relatives whose voices I could hear even when they were not there.",
    "ch3-003",
  ),
  line(
    "ch3-003",
    "chapter-3",
    stages.jcFamilyPressure,
    "adult-aleem",
    "Which school would take me? Would I cope? Had I finally understood what was at stake? Nobody needed to say I had disappointed them. I supplied that sentence myself and placed it underneath everything they did say.",
    "ch3-004",
  ),
  line(
    "ch3-004",
    "chapter-3",
    stages.darkBedroom,
    "aleem-sec",
    "I know I messed up. I do not need everyone to keep translating the results for me.",
    "ch3-005",
  ),
  line(
    "ch3-005",
    "chapter-3",
    stages.darkBedroom,
    "adult-aleem",
    "I said that mostly inside my room. Outside it, I nodded and answered as little as possible. Shame made even ordinary advice sound like a verdict, and silence felt safer than admitting how frightened I was.",
    "ch3-006",
  ),
  line(
    "ch3-006",
    "chapter-3",
    stages.jcDawn,
    "adult-aleem",
    "Still, I did not give up. The route available to me led to a junior college people around me casually called weak. I repeated the word before anyone could use it against me.",
    "ch3-007",
  ),
  line(
    "ch3-007",
    "chapter-3",
    stages.jcDawn,
    "adult-aleem",
    "A school is not weak. It is rooms, teachers, ambitions, tired students, second chances, and hundreds of lives moving at different speeds. But at sixteen, prestige felt like a measurement of the person wearing the uniform.",
    "ch3-008",
  ),
  line(
    "ch3-008",
    "chapter-3",
    stages.jcArrival,
    "adult-aleem",
    "On the first day of 2014, I entered in a new white, charcoal, and muted-teal uniform, taller than most people around me and determined to look as though this had always been the plan.",
    "ch3-009",
  ),
  line(
    "ch3-009",
    "chapter-3",
    stages.jcArrival,
    "adult-aleem",
    "Orientation turned the campus into a tide of unfamiliar faces. I checked classroom signs twice, followed whichever crowd looked confident, and hoped nobody would ask why I had chosen the school.",
    "ch3-010",
  ),
  line(
    "ch3-010",
    "chapter-3",
    stages.jcSyafiqaWarm,
    "syafiqa",
    "Aleem? From Chinese class? You still look lost in every school, ah?",
    "ch3-011",
  ),
  line(
    "ch3-011",
    "chapter-3",
    stages.jcSyafiqaWarm,
    "adult-aleem",
    "Syafiqa stood beside the noticeboard, tall, with long hair tied back and the expression of someone pleased to have found one familiar person. She had attended the same external Chinese class as Hana and me, though we had never been close then.",
    "ch3-012",
  ),
  line(
    "ch3-012",
    "chapter-3",
    stages.jcSyafiqaWarm,
    "aleem-sec",
    "I am not lost. I am checking whether the signs are accurate.",
    "ch3-013",
  ),
  line(
    "ch3-013",
    "chapter-3",
    stages.jcSyafiqaWarm,
    "syafiqa",
    "Of course. Very responsible. Come, our class is this way.",
    "ch3-014",
  ),
  line(
    "ch3-014",
    "chapter-3",
    stages.chineseClassRecall,
    "adult-aleem",
    "Recognition did what confidence could not. For a few minutes we were back in the borrowed classroom, complaining about characters that looked almost identical and pretending our pronunciation was better than it was.",
    "ch3-015",
  ),
  line(
    "ch3-015",
    "chapter-3",
    stages.jcSyafiqaClassroom,
    "adult-aleem",
    "Then the coincidence widened. We were classmates. We lived along the same direction home. Our mornings began at the same interchange, which gave us an easy reason to meet again the next day.",
    "ch3-016",
  ),
  line(
    "ch3-016",
    "chapter-3",
    stages.busStopWaiting,
    "syafiqa",
    "If you are late tomorrow, I am leaving without you.",
    "ch3-017",
  ),
  line(
    "ch3-017",
    "chapter-3",
    stages.busStopWaiting,
    "aleem-sec",
    "Fair. If you are late, I will wait and complain the whole way.",
    "ch3-018",
  ),
  line(
    "ch3-018",
    "chapter-3",
    stages.busMorningTogether,
    "adult-aleem",
    "The arrangement became routine before either of us named it. A message before leaving home. A familiar figure near the queue. Two seats if the bus was kind, or two handholds near each other if it was not.",
    "ch3-019",
  ),
  line(
    "ch3-019",
    "chapter-3",
    stages.busMorningTogether,
    "adult-aleem",
    "We spoke about tutorials, teachers, family rules, and the peculiar exhaustion of beginning again. Syafiqa could make a complaint sound like a story. By the time we reached school, I usually felt less like an admission mistake.",
    "ch3-020",
  ),
  line(
    "ch3-020",
    "chapter-3",
    stages.busStopWaiting,
    "adult-aleem",
    "Some mornings one bus arrived before she did. I let it leave. Then another came with space, but her message said she was close, so I let that one leave too.",
    "ch3-021",
  ),
  line(
    "ch3-021",
    "chapter-3",
    stages.busStopWaiting,
    "syafiqa",
    "You skipped two buses? Aleem, you could have gone first.",
    "ch3-022",
  ),
  line(
    "ch3-022",
    "chapter-3",
    stages.busStopWaiting,
    "aleem-sec",
    "And listen to you blame traffic for being late by myself? Cannot. I need the full performance.",
    "ch3-023",
  ),
  line(
    "ch3-023",
    "chapter-3",
    stages.busMorningTogether,
    "adult-aleem",
    "She laughed, and the wasted minutes felt transformed into something chosen. Soon she waited for me too. We never called it a promise. We simply began expecting the other person to appear.",
    "ch3-024",
  ),
  line(
    "ch3-024",
    "chapter-3",
    stages.busEarpiece,
    "adult-aleem",
    "On quieter rides, one of us offered an earpiece. The wire crossed the small distance between our shoulders. We never needed the same favourite song; sharing the silence around it seemed to be enough.",
    "ch3-choice-bus",
  ),
  choice(
    "ch3-choice-bus",
    "chapter-3",
    stages.busEarpiece,
    "What did Aleem believe the shared rides meant?",
    [
      {
        id: "bus-proof",
        label: "This must mean she likes me too.",
        next: "ch3-bus-proof-001",
      },
      {
        id: "bus-possibility",
        label: "It could be affection, but I need to ask.",
        next: "ch3-bus-possibility-001",
      },
      {
        id: "bus-friendship",
        label: "Do not turn a good friendship into evidence.",
        next: "ch3-bus-friendship-001",
      },
    ],
  ),
  line(
    "ch3-bus-proof-001",
    "chapter-3",
    stages.busEarpiece,
    "aleem-sec",
    "People do not keep choosing the same bus, the same seat, and the same pair of earphones for no reason. Surely this is her way of saying it.",
    "ch3-bus-proof-002",
  ),
  line(
    "ch3-bus-proof-002",
    "chapter-3",
    stages.busEveningAleem,
    "adult-aleem",
    "I treated repetition as proof because certainty was comforting. But intimacy can be real without being romantic, and another person's comfort is not consent to the meaning you privately assign it.",
    "ch3-bus-join",
  ),
  line(
    "ch3-bus-possibility-001",
    "chapter-3",
    stages.busEarpiece,
    "aleem-sec",
    "Maybe she feels something. Maybe she simply trusts me. Guessing harder will not turn either possibility into an answer.",
    "ch3-bus-possibility-002",
  ),
  line(
    "ch3-bus-possibility-002",
    "chapter-3",
    stages.busEveningAleem,
    "adult-aleem",
    "That was the fairest thought available to me. Closeness created a question, not a claim. Clarity would require risking an answer that did not match the hope behind it.",
    "ch3-bus-join",
  ),
  line(
    "ch3-bus-friendship-001",
    "chapter-3",
    stages.busEarpiece,
    "aleem-sec",
    "She is my friend. I should be grateful for that instead of measuring every kind thing for a hidden message.",
    "ch3-bus-friendship-002",
    ),
  line(
    "ch3-bus-friendship-002",
    "chapter-3",
    stages.busEveningAleem,
    "adult-aleem",
    "Restraint protected the friendship from entitlement, but it could not erase my feelings. Pretending the question did not exist would eventually make the ordinary moments heavier, not simpler.",
    "ch3-bus-join",
  ),
  line(
    "ch3-bus-join",
    "chapter-3",
    stages.busEarpiece,
    "adult-aleem",
    "There were afternoons when tiredness ended the conversation before either of us chose to. Our heads tipped toward the glass, the shared earpieces remained in place, and we woke near our stop with the embarrassed alertness of people caught being comfortable.",
    "ch3-025",
  ),
  line(
    "ch3-025",
    "chapter-3",
    stages.busMorningTogether,
    "syafiqa",
    "We fell asleep again. Next time you are responsible for not missing the stop.",
    "ch3-026",
  ),
  line(
    "ch3-026",
    "chapter-3",
    stages.busMorningTogether,
    "aleem-sec",
    "You say that every time, then you sleep first.",
    "ch3-027",
  ),
  line(
    "ch3-027",
    "chapter-3",
    stages.busEveningAleem,
    "adult-aleem",
    "I liked the version of myself beside her: less defensive, less defined by results, able to make somebody laugh before eight in the morning. Wanting that feeling to have a name was not unreasonable.",
    "ch3-028",
  ),
  line(
    "ch3-028",
    "chapter-3",
    stages.jcClassroom,
    "adult-aleem",
    "What confused me was the space between our routines and our words. We could arrange whole days around each other, yet neither of us spoke about whether the closeness pointed anywhere beyond friendship.",
    "ch3-029",
  ),
  line(
    "ch3-029",
    "chapter-3",
    stages.jcArrival,
    "adult-aleem",
    "Eventually, uncertainty became harder to carry than rejection. I asked Syafiqa to stay behind near a quieter stretch of campus after the last lesson.",
    "ch3-choice-confession",
  ),
  choice(
    "ch3-choice-confession",
    "chapter-3",
    stages.jcConfession,
    "How did Aleem put his feelings into words?",
    [
      {
        id: "confession-direct",
        label: "I like you. Do you feel the same?",
        next: "ch3-confession-direct-001",
      },
      {
        id: "confession-gentle",
        label: "Our time together matters to me. Could this be more?",
        next: "ch3-confession-gentle-001",
      },
      {
        id: "confession-defensive",
        label: "I may be reading this wrongly, but I need to know.",
        next: "ch3-confession-defensive-001",
      },
    ],
  ),
  line(
    "ch3-confession-direct-001",
    "chapter-3",
    stages.jcConfession,
    "aleem-sec",
    "I like you, Syafiqa. Not only as the person I travel with. Do you feel the same way?",
    "ch3-confession-direct-002",
  ),
  line(
    "ch3-confession-direct-002",
    "chapter-3",
    stages.jcConfession,
    "adult-aleem",
    "Directness gave her a clear question and gave me nowhere to hide from the answer. It was frightening, but it did not make her responsible for rewarding the courage it required.",
    "ch3-confession-join",
  ),
  line(
    "ch3-confession-gentle-001",
    "chapter-3",
    stages.jcConfession,
    "aleem-sec",
    "The mornings and rides with you have become important to me. I was wondering whether you could ever see us as more than friends.",
    "ch3-confession-gentle-002",
  ),
  line(
    "ch3-confession-gentle-002",
    "chapter-3",
    stages.jcConfession,
    "adult-aleem",
    "I tried to leave room around the question. Gentle wording could reduce pressure, but it could not guarantee a gentle outcome. Some truths hurt however carefully they are invited in.",
    "ch3-confession-join",
  ),
  line(
    "ch3-confession-defensive-001",
    "chapter-3",
    stages.jcConfession,
    "aleem-sec",
    "Maybe I understood everything wrongly. If I did, just tell me. But I like you, and I need to know what all this means to you.",
    "ch3-confession-defensive-002",
  ),
  line(
    "ch3-confession-defensive-002",
    "chapter-3",
    stages.jcConfession,
    "adult-aleem",
    "The defence arrived before the rejection. I wanted honesty while already bracing for humiliation, which made the question carry more accumulated fear than Syafiqa had created.",
    "ch3-confession-join",
  ),
  line(
    "ch3-confession-join",
    "chapter-3",
    stages.jcSyafiqaFirm,
    "adult-aleem",
    "Syafiqa went quiet. She did not laugh, look disgusted, or punish me for asking. She chose her words slowly, aware that friendship would not make them painless.",
    "ch3-030",
  ),
  line(
    "ch3-030",
    "chapter-3",
    stages.jcSyafiqaFirm,
    "syafiqa",
    "I care about you, but I do not want a relationship. I really need to focus on my studies now. I hope we can still be friends.",
    "ch3-031",
  ),
  line(
    "ch3-031",
    "chapter-3",
    stages.jcConfession,
    "aleem-sec",
    "Okay. Thank you for telling me. I will not make things difficult for you.",
    "ch3-032",
  ),
  line(
    "ch3-032",
    "chapter-3",
    stages.busEveningAleem,
    "adult-aleem",
    "I had asked for clarity and received a no. The reason hurt, but it was believable. Junior college moved quickly; all of us had been warned how easily one neglected week could become a lost term.",
    "ch3-033",
  ),
  line(
    "ch3-033",
    "chapter-3",
    stages.busEveningAleem,
    "adult-aleem",
    "For several days, I worked at accepting the answer exactly as given. We travelled separately. I told myself distance was respectful, not punishment, though some mornings I still watched the usual bus leave.",
    "ch3-034",
  ),
  line(
    "ch3-034",
    "chapter-3",
    stages.syafiqaOtherBoy,
    "adult-aleem",
    "A week after the confession, I saw Syafiqa elsewhere on campus, walking closely beside another boy. They looked at ease in the way people do when a conversation began long before you entered the scene.",
    "ch3-035",
  ),
  line(
    "ch3-035",
    "chapter-3",
    stages.syafiqaOtherBoy,
    "adult-aleem",
    "Seeing them did not prove they were together. It did not rewrite her no into a debt she owed me. But hurt is impatient with careful distinctions, and mine supplied a conclusion immediately.",
    "ch3-036",
  ),
  line(
    "ch3-036",
    "chapter-3",
    stages.jcAleemHurt,
    "aleem-sec",
    "So studying was not the real reason. There was already somebody else.",
    "ch3-037",
  ),
  line(
    "ch3-037",
    "chapter-3",
    stages.jcAleemHurt,
    "adult-aleem",
    "Later, through a separate conversation, I learned that she had liked him before I confessed. That information was firmer than what I had seen, and it struck the same bruise Alya's wrong message had left years earlier.",
    "ch3-038",
  ),
  line(
    "ch3-038",
    "chapter-3",
    stages.jcAleemHurt,
    "adult-aleem",
    "Again, I believed the important truth had existed behind me while I behaved according to a softer explanation. Again, I wondered why someone could not simply trust me with the answer they seemed to give everyone else.",
    "ch3-choice-belief",
  ),
  choice(
    "ch3-choice-belief",
    "chapter-3",
    stages.jcAleemHurt,
    "What belief began taking root in Aleem?",
    [
      {
        id: "belief-generalise",
        label: "Malay girls will always hide the real reason.",
        next: "ch3-belief-generalise-001",
      },
      {
        id: "belief-protect",
        label: "Do not trust soft answers; look for what is hidden.",
        next: "ch3-belief-protect-001",
      },
      {
        id: "belief-question",
        label: "Her answer hurt, but one answer cannot explain everyone.",
        next: "ch3-belief-question-001",
      },
    ],
  ),
  line(
    "ch3-belief-generalise-001",
    "chapter-3",
    stages.jcAleemHurt,
    "aleem-sec",
    "Alya, Hana, now Syafiqa. Maybe Malay girls simply will not tell me the truth until I discover it somewhere else.",
    "ch3-belief-generalise-002",
  ),
  line(
    "ch3-belief-generalise-002",
    "chapter-3",
    stages.jcDawn,
    "adult-aleem",
    "I turned three different people and three different endings into a rule about Malay girls. The pattern felt protective because it made pain predictable. It was also unfair, shaped by selective memory and large enough to erase every individual person inside it.",
    "ch3-belief-join",
  ),
  line(
    "ch3-belief-protect-001",
    "chapter-3",
    stages.jcAleemHurt,
    "aleem-sec",
    "People say the kindest reason, not the truest one. From now on, I need to watch what they do and find the answer myself.",
    "ch3-belief-protect-002",
  ),
  line(
    "ch3-belief-protect-002",
    "chapter-3",
    stages.jcDawn,
    "adult-aleem",
    "That rule sounded cautious and mature. In practice, it trained me to treat ambiguity as evidence and inference as certainty. Suspicion could prevent surprise, but it could also manufacture betrayal where a boundary or private feeling was enough.",
    "ch3-belief-join",
  ),
  line(
    "ch3-belief-question-001",
    "chapter-3",
    stages.jcAleemHurt,
    "aleem-sec",
    "I wish she had told me about him. But Syafiqa is one person, and rejection is still rejection whatever explanation comes with it.",
    "ch3-belief-question-002",
  ),
  line(
    "ch3-belief-question-002",
    "chapter-3",
    stages.jcDawn,
    "adult-aleem",
    "It was the thought I needed, though not always the one I could sustain. A wish for direct communication was reasonable. Turning that wish into entitlement to somebody's private feelings—or a judgement on an entire group—was not.",
    "ch3-belief-join",
  ),
  line(
    "ch3-belief-join",
    "chapter-3",
    stages.jcDawn,
    "adult-aleem",
    "Syafiqa had every right to reject me and no obligation to disclose a crush. I could also honestly say that the softened explanation made later knowledge harder to absorb. Both truths fit, even when teenage me wanted only one guilty side.",
    "ch3-039",
  ),
  line(
    "ch3-039",
    "chapter-3",
    stages.busStopWaiting,
    "adult-aleem",
    "The rides did not recover their old ease. We remained civil, then less present in each other's routines. The queue where I had once waited through two buses became only a place to get home.",
    "ch3-040",
  ),
  line(
    "ch3-040",
    "chapter-3",
    stages.jcAleemHurt,
    "adult-aleem",
    "I told myself the lesson was about other people: ask sooner, trust less, look beneath every answer. I was slower to notice the more urgent question underneath—why one rejection had become a referendum on whether I was worth choosing at all.",
    "ch4-001",
  ),
] as const satisfies readonly StoryNode[];
