import type { StageSnapshot, StoryNode } from "../engine/types";
import { choice, line } from "./helpers";
import { adulthoodStages as stages } from "./adulthoodStages";

const beat = (id: string, stage: StageSnapshot, speaker: string, text: string, next: string) =>
  line(id, "chapter-6", stage, speaker, text, next);

export const chapterSixNodes = [
  beat("ch6-001", stages.orientation, "adult-aleem",
    "By my second year at university, I could stand in front of an orientation group and sound as if I knew what I was doing. I had a list of names, an overworked voice, and responsibility for people who still looked at every building as though it might be the wrong one.", "ch6-002"),
  beat("ch6-002", stages.orientation, "adult-aleem",
    "I had also brought my old rules with me. With Malay girls, I kept conversations safely practical. Directions, group work, nothing that might become a crush. I called it knowing my type. Really, I was still arranging my life around the fear of being hurt in a familiar way.", "ch6-003"),
  beat("ch6-003", stages.orientationMeet, "adult-aleem",
    "Jia Wen stood near the front of my group, a Chinese freshie with a small backpack and a face I kept accidentally checking for a smile. She was short enough that somebody behind her could read my clipboard over her head. Very cute, I thought, then reminded myself to take attendance.", "ch6-004"),
  beat("ch6-004", stages.orientationMeet, "jia-wen",
    "You already called my name. Twice. Am I supposed to attend twice also?", "ch6-005"),
  beat("ch6-005", stages.orientationTeasing, "aleem-adult",
    "Just making sure the group is complete. Very thorough leadership.", "ch6-006"),
  beat("ch6-006", stages.orientationTeasing, "jia-wen",
    "Wah. Then later you better count us properly. I don't want to get left at the wrong faculty.", "ch6-007"),
  beat("ch6-007", stages.orientationTeasing, "adult-aleem",
    "She said it without the careful politeness of somebody meeting a senior. I laughed, and after that talking to her felt strangely easy. She asked actual questions instead of nodding at my explanations, and caught me when I pointed confidently in a direction I then had to correct.", "ch6-008"),
  beat("ch6-008", stages.orientationMeet, "adult-aleem",
    "When orientation ended, the group chat grew quieter. Ours did the opposite. A question about where to find a tutorial room became a complaint about lunch, then a photograph of a queue, then a conversation that wandered past midnight without either of us announcing that we were staying.", "ch6-chat"),
  beat("ch6-chat", stages.orientationMeet, "adult-aleem",
    "I would say I was going to sleep, put the phone down, and reach for it when it lit up again. She did the same. Our goodnights became negotiations neither of us was particularly determined to finish. The next morning, I could be tired in a lecture and still smile when she sent a complaint about hers.", "ch6-009"),
  beat("ch6-009", stages.studyTogether, "jia-wen",
    "What time you finish tomorrow? I have this horrible gap between classes. Too short to go back, too long to pretend I'm being productive.", "ch6-010"),
  beat("ch6-010", stages.studyTogether, "aleem-adult",
    "Send me your timetable. We can compare suffering.", "ch6-011"),
  beat("ch6-011", stages.studyLaughing, "adult-aleem",
    "Soon I knew her free afternoons better than my own assignment deadlines. We compared timetables before committing to other plans, chose lunch around whichever of us finished later, and found study spaces near the other's next class. It was never only me adjusting. She waited for me too, and those small decisions mattered enormously.", "ch6-012"),
  beat("ch6-012", stages.studyLaughing, "jia-wen",
    "I saved you the seat with the plug. Please appreciate this. People were eyeing it.", "ch6-013"),
  beat("ch6-013", stages.studyTogether, "adult-aleem",
    "She pushed a drink towards me without stopping her typing. I put my bag down beside hers and felt the day's noise settle. We could work quietly for an hour, then lose another twenty minutes to something neither of us would remember the next morning. I began looking forward to nothing in particular, as long as it involved her.", "ch6-study-break"),
  beat("ch6-study-break", stages.studyTogether, "adult-aleem",
    "Once, I arrived annoyed with myself after a class and opened my laptop much harder than necessary. She waited until I had finished pretending to work, then nudged my drink closer. I told her what had happened. She listened, asked one useful question, and stayed until I could laugh about the way I had slammed the lid.", "ch6-014"),
  beat("ch6-014", stages.studyLaughing, "adult-aleem",
    "People noticed. Somebody would ask where my girlfriend was when I arrived alone; somebody else would tell Jia Wen to ask her boyfriend for help. The joke travelled beyond our original orientation group. Every time we appeared together, another person seemed to nod as if a rumour had just been confirmed.", "ch6-015"),
  beat("ch6-015", stages.studyLaughing, "jia-wen",
    "We're friends lah. You all see two people eating lunch and immediately start planning a wedding.", "ch6-016"),
  beat("ch6-016", stages.studySilence, "adult-aleem",
    "I laughed along. The word friends should have registered more clearly than the teasing around it. Instead, I carried the teasing home. If everybody could see something between us, surely there was something to see. I told myself she was simply embarrassed to admit it in front of everyone.", "ch6-choice-silence"),
  choice("ch6-choice-silence", "chapter-6", stages.studySilence,
    "What kept the words in my mouth?", [
      { id: "silence-time", label: "Let the friendship become love in its own time.", next: "ch6-silence-time" },
      { id: "silence-fear", label: "A direct question could take all of this away.", next: "ch6-silence-fear" },
      { id: "silence-obvious", label: "Surely she can already tell how I feel.", next: "ch6-silence-obvious" },
    ]),
  beat("ch6-silence-time", stages.studySilence, "adult-aleem",
    "Maybe this was what I had rushed before: the ordinary hours that made somebody indispensable. I wanted to give us those hours. I could imagine a day when she looked at me differently, and the friendship changed without either of us having to risk an awkward beginning.", "ch6-silence-join"),
  beat("ch6-silence-fear", stages.studySilence, "adult-aleem",
    "I could survive not knowing while there was still a place saved beside her. A no might change every comfortable thing we had. I held on to tomorrow's lunch, next week's study session, any small certainty I could keep by postponing the one question that frightened me.", "ch6-silence-join"),
  beat("ch6-silence-obvious", stages.studySilence, "adult-aleem",
    "Who else knew her timetable this well? Who else stayed up answering messages about a bad day? I thought my feelings must be visible in the time I gave her. Saying them aloud felt almost unnecessary, like explaining a joke everybody in the room already understood.", "ch6-silence-join"),
  beat("ch6-silence-join", stages.studyTogether, "adult-aleem",
    "So I tried a different approach. No sudden declaration, no demand for an answer before we were close. Just stay nearby until she liked me. Hover, if I was being honest. I made it sound patient in my head, though I was quietly expecting that patience to lead somewhere specific.", "ch6-017"),
  beat("ch6-017", stages.studyJealous, "adult-aleem",
    "And I began keeping watch. If a guy asked whether she was joining something, I listened for more than the question. Did he ask anyone else? Was he finding excuses to message? A friendly conversation could become a threat in the few seconds it took me to decide he liked her.", "ch6-018"),
  beat("ch6-018", stages.studyJealous, "aleem-adult",
    "She has plans already. We're studying later. Maybe ask the group another time.", "ch6-019"),
  beat("ch6-019", stages.studyQuestioned, "jia-wen",
    "Eh, I haven't even answered him yet.", "ch6-020"),
  beat("ch6-020", stages.studyQuestioned, "aleem-adult",
    "Thought you said you had work to finish. I was helping you escape.", "ch6-021"),
  beat("ch6-021", stages.studyJealous, "adult-aleem",
    "The excuse passed easily enough. Sometimes I discouraged a guy before she heard about his interest at all. I would mention how busy she was, turn an invitation into a group outing, or stay planted beside her until he left. I felt useful afterwards. That should have troubled me more than it did.", "ch6-keeping-watch"),
  beat("ch6-keeping-watch", stages.studyJealous, "adult-aleem",
    "I watched him put his phone away and felt myself relax. Then Jia Wen asked what I thought about something she had just said. I had to ask her to repeat it. I was sitting beside the person I wanted to know better, missing her actual conversation because I was busy deciding who else could have one with her.", "ch6-022"),
  beat("ch6-022", stages.dorm, "adult-aleem",
    "In her dorm, I took the chair while she sat with her laptop on the bed, surrounded by notes she insisted were in a system. A desk fan clicked each time it turned. She would ask me to read a sentence, then argue with my suggestion until we both forgot why she had asked.", "ch6-023"),
  beat("ch6-023", stages.dormWarm, "jia-wen",
    "You're making it sound like a government announcement. I just need it to sound like me, but more intelligent.", "ch6-024"),
  beat("ch6-024", stages.dormWarm, "aleem-adult",
    "That one a bit difficult. Need a bigger editing budget.", "ch6-025"),
  beat("ch6-025", stages.dormWarm, "adult-aleem",
    "She threatened to take back the snack she had given me. I surrendered immediately. Later, while she worked, I watched the fan stir a loose page and felt so comfortable that I could almost believe comfort was an agreement. Nobody had invited me to imagine a shared future. I was already furnishing one.", "ch6-dorm-evening"),
  beat("ch6-dorm-evening", stages.dorm, "adult-aleem",
    "Sometimes she got tired of the assignment before I did. She would close the laptop and tell me about her day, shifting the pile of notes so she could sit properly. I knew which stories needed advice and which needed somebody to agree that people could be very irritating. It pleased me that she trusted me with both.", "ch6-026"),
  beat("ch6-026", stages.dropoff, "adult-aleem",
    "When she went home, I sometimes sent her back. Our conversation stretched across the journey, grew quieter near her stop, then found one last thing to say. At the drop-off, she would turn round because she had remembered something small, and I would get another minute before goodbye.", "ch6-027"),
  beat("ch6-027", stages.dropoff, "jia-wen",
    "Message when you reach, okay? And don't forget to eat. You were so busy complaining you never finished dinner.", "ch6-028"),
  beat("ch6-028", stages.dropoff, "adult-aleem",
    "Those were the lines I replayed. Her checking that I got home, her saving a seat, her asking whether I was free before making plans. They were real kindnesses. I stacked them carefully in my mind, each one evidence for a conclusion we had never spoken about together.", "ch6-home-message"),
  beat("ch6-home-message", stages.dropoff, "adult-aleem",
    "Back in my own room, I would send the promised message and wait for her reply before putting the phone to charge. She usually had one more thing to add. I began to expect that small exchange at the end of a day. Without ever discussing it, I had made her part of how I knew the day was over.", "ch6-029"),
  beat("ch6-029", stages.studyTogether, "adult-aleem",
    "By fourth year, graduation had begun to appear in conversations. People discussed the world beyond campus as if we were all ready to leave. I looked at our matching gaps in the timetable and realised there would soon be no timetable holding us near each other. I needed to say something before that happened.", "ch6-030"),
  beat("ch6-030", stages.uniPlanning, "adult-aleem",
    "I chose Universal Studios Singapore. December 2021, at the end of the year. We could have a full day together, something larger than lunch between classes, and I would find a quiet moment to tell her. I planned the outing until the planning itself began to feel like courage.", "ch6-031"),
  beat("ch6-031", stages.uniPlanning, "aleem-adult",
    "Jia Wen, I like you. More than a friend. I've liked you for a long time.", "ch6-032"),
  beat("ch6-032", stages.uniPlanning, "adult-aleem",
    "Alone in my room, I kept adjusting that opening. Too serious. Too sudden. Too much like I had rehearsed it in my room, which was exactly what I was doing. I checked the plans again, imagined her expression, and let myself picture the journey home with everything finally understood.", "ch6-preparing"),
  beat("ch6-preparing", stages.uniPlanning, "adult-aleem",
    "I asked whether the date still worked for her and read her yes with ridiculous relief. I was careful to make the outing sound casual when we talked about it. Afterwards, I went back to planning a moment she had no reason to expect. Even now, with a confession ahead, secrecy felt easier than letting her see me nervous.", "ch6-033"),
  beat("ch6-033", stages.uniDiscovery, "adult-aleem",
    "Then the week before the outing arrived. I overheard her name in a conversation nearby, followed by boyfriend. Nothing dramatic in the way it was said. Just ordinary news moving between people who did not know they were pulling the floor out from under somebody within earshot.", "ch6-034"),
  beat("ch6-034", stages.uniDiscovery, "adult-aleem",
    "I went still, then tried to look as if I hadn't. Maybe I had misheard. Maybe they meant someone else. I checked my phone without reading anything, giving my hands a task while my mind went through every name I knew around her. None of them fitted.", "ch6-dread"),
  beat("ch6-dread", stages.uniDiscovery, "adult-aleem",
    "Her chat was still there, full of ordinary things. Nothing on the screen announced that my place in her life was different from what I had imagined. I scrolled up, looking for some warning I had missed, then stopped. I had years of messages and could not find the question whose answer I suddenly needed.", "ch6-035"),
  beat("ch6-035", stages.boyfriend, "adult-aleem",
    "Then I saw them together. She reached for his hand with an ease that needed no explanation. He leaned closer to hear her, and she smiled the way people smile when they are continuing a conversation that belongs to them. There was nothing uncertain about what I was seeing.", "ch6-036"),
  beat("ch6-036", stages.boyfriend, "adult-aleem",
    "I did not recognise him. After all the attention I had paid, all the approaches I thought I had intercepted, the person beside her had appeared from outside my carefully maintained radar. For a few stunned seconds, that felt like the most impossible part: how had something so important happened without me knowing?", "ch6-037"),
  beat("ch6-037", stages.uniAlone, "adult-aleem",
    "At home, I put the outing plans away, then opened them again. I had spent too long preparing to cancel. That was the reason I gave myself. Underneath it was another one: if I cancelled, these words might stay inside me forever, and I was tired of being the only person who heard them.", "ch6-038"),
  beat("ch6-038", stages.ussArrival, "adult-aleem",
    "We still went. December lights brightened the park, and music followed us past shopfronts and families stopping for pictures. She arrived as the friend who had agreed to spend the day with me. I arrived carrying a confession that already knew it could not have the ending I had rehearsed.", "ch6-039"),
  beat("ch6-039", stages.ussArrival, "jia-wen",
    "You okay? You're very quiet today. Usually by now you have complained about at least three things.", "ch6-040"),
  beat("ch6-040", stages.ussTogether, "aleem-adult",
    "Saving my energy. Long day ahead. The complaints need to last.", "ch6-041"),
  beat("ch6-041", stages.ussTogether, "adult-aleem",
    "For stretches of the afternoon, we were almost ourselves. We argued about where to go next, laughed at a photograph, stood in a queue with nothing to do except talk. Then she looked away and the knowledge returned. I had become good at keeping things from her. Now I had to keep this too, until I didn't.", "ch6-uss-waiting"),
  beat("ch6-uss-waiting", stages.ussTogether, "adult-aleem",
    "She asked whether I wanted something to drink. I nodded and followed her, absurdly grateful for a decision that required so little of me. There were still minutes I wanted to keep: her making room for someone to pass, then turning straight back to finish her story. I listened harder because I knew I might miss this soon.", "ch6-042"),
  beat("ch6-042", stages.ussQuiet, "adult-aleem",
    "When we found a quieter place beneath the lights, I stopped pretending to study the view. My prepared sentences had deserted me. She noticed my hands, then my face, and waited. After years of conversation, the space before this one felt longer than anything we had ever said.", "ch6-043"),
  beat("ch6-043", stages.confession, "aleem-adult",
    "I know you're seeing someone. I'm not asking you to do anything about that. But I need to tell you. I like you, Jia Wen. I've liked you for a long time.", "ch6-044"),
  beat("ch6-044", stages.confession, "adult-aleem",
    "She looked at me without speaking. Somewhere behind us, somebody called for their family to stand closer for a picture. I could hear every little sound that should have disappeared for a moment like this. The world continued at exactly its usual volume.", "ch6-045"),
  beat("ch6-045", stages.ussQuestion, "jia-wen",
    "Why didn’t you tell me earlier?", "ch6-046"),
  beat("ch6-046", stages.ussQuestion, "adult-aleem",
    "That sentence stayed. Not just that evening, not just on the way home. It found me afterwards while I was eating, working, trying to sleep. Earlier. The word suggested a door I might have reached before it closed, without telling me whether that door had ever actually been open.", "ch6-choice-question"),
  choice("ch6-choice-question", "chapter-6", stages.ussQuestion,
    "What did I hear inside her question?", [
      { id: "question-chance", label: "Maybe we could have been together.", next: "ch6-question-chance" },
      { id: "question-surprise", label: "Maybe she had no idea what I was hoping for.", next: "ch6-question-surprise" },
      { id: "question-unknown", label: "I cannot tell what earlier would have changed.", next: "ch6-question-unknown" },
    ]),
  beat("ch6-question-chance", stages.ussQuestion, "adult-aleem",
    "My mind ran backwards through every evening I could have spoken. The seat she saved. Her dorm. The minute before she went home. In each memory I replaced my silence with a confession and imagined her saying yes. It hurt like losing a life I had almost lived.", "ch6-question-join"),
  beat("ch6-question-surprise", stages.ussQuestion, "adult-aleem",
    "I looked at the surprise on her face and wondered whether all my careful signals had simply looked like friendship. Had she spent these years beside somebody she trusted, while I kept waiting for her to understand a conversation we were not having? The possibility made my rehearsed certainty falter.", "ch6-question-join"),
  beat("ch6-question-unknown", stages.ussQuestion, "adult-aleem",
    "I wanted to ask her to explain every word. Instead, I stood there with the terrible possibility that even an explanation would not give me the past back. Her question was real. The answer I kept hearing beneath it might still be something I was supplying myself.", "ch6-question-join"),
  beat("ch6-question-join", stages.ussQuiet, "aleem-adult",
    "I thought... I thought you knew. We spent so much time together. Everyone thought we were together already.", "ch6-047"),
  beat("ch6-047", stages.ussFarewell, "jia-wen",
    "I knew we were close. You're important to me. But we never said we were a couple, Aleem.", "ch6-048"),
  beat("ch6-048", stages.ussFarewell, "adult-aleem",
    "I wanted to lay out everything I had done. Every journey, every late reply I had stayed awake for, every afternoon arranged around her. It felt like more than friendship, so much more that I had allowed myself to treat us as already together. Hearing the missing agreement spoken aloud made my face burn.", "ch6-049"),
  beat("ch6-049", stages.ussFarewell, "adult-aleem",
    "The feelings were real. So were those afternoons. But no amount of remembering them could produce a moment when she had agreed to be my girlfriend. I had taken the meaning those things held for me and quietly written her name beneath it too.", "ch6-050"),
  beat("ch6-050", stages.ussFarewell, "jia-wen",
    "What happens to us now? Can we still be friends?", "ch6-choice-farewell"),
  choice("ch6-choice-farewell", "chapter-6", stages.ussFarewell,
    "How could I explain the distance I needed?", [
      { id: "farewell-ready", label: "I'm not ready to be only friends.", next: "ch6-farewell-ready" },
      { id: "farewell-hurt", label: "Seeing you would hurt too much right now.", next: "ch6-farewell-hurt" },
      { id: "farewell-honest", label: "I can't pretend my feelings are gone.", next: "ch6-farewell-honest" },
    ]),
  beat("ch6-farewell-ready", stages.ussFarewell, "aleem-adult",
    "I'm not ready. I know friends is what we've been, but in my head I kept waiting for something else. I can't just switch that off and come for lunch like nothing happened. I need to be away for a while.", "ch6-farewell-join"),
  beat("ch6-farewell-hurt", stages.ussFarewell, "aleem-adult",
    "I don't think I can face you right now. Every normal thing would hurt, even you asking about my day. I don't want you to have to watch everything you say around me. I need some distance because I don't know how to do this yet.", "ch6-farewell-join"),
  beat("ch6-farewell-honest", stages.ussFarewell, "aleem-adult",
    "If I say yes now, I'll still be hoping. You'd think we were okay and I'd still be waiting for your feelings to change. I can't promise a friendship I don't know how to give you. I'm sorry. I need to step back.", "ch6-farewell-join"),
  beat("ch6-farewell-join", stages.ussFarewell, "adult-aleem",
    "She grew quiet. I had imagined relief after finally speaking, but it was awful watching my words reach her. She was losing a close friend in the same place where I was grieving a relationship we had never had. Neither of us could make the other person's loss smaller.", "ch6-051"),
  beat("ch6-051", stages.ussFarewell, "jia-wen",
    "Okay. I won't push you. Take care of yourself, can?", "ch6-052"),
  beat("ch6-052", stages.uniAlone, "adult-aleem",
    "Afterwards, my hand still moved towards her chat whenever something funny happened. I would compose half a message before remembering. The gap was in lunch, in the hours after class, in reaching home without anybody expecting an update. There was no official anniversary to mourn. My days noticed anyway.", "ch6-053"),
  beat("ch6-053", stages.uniAlone, "adult-aleem",
    "Would earlier have changed anything? Would we have been a couple? I kept returning to those questions as though persistence might make them answerable. Meanwhile, the simplest fact waited without changing: I was single. I had been single beside her too. Now I had to learn how to be alone.", "ch7-001"),
] as const satisfies readonly StoryNode[];
