import type { StageSnapshot, StoryNode } from "../engine/types";
import { choice, line } from "./helpers";
import { umrahStages as stages } from "./umrahStages";

const beat = (id: string, stage: StageSnapshot, speaker: string, text: string, next: string) =>
  line(id, "chapter-10", stage, speaker, text, next);

export const chapterTenNodes = [
  beat("ch10-001", stages.madinah, "adult-aleem",
    "Madinah came after Makkah. I carried the two climbs with me, the sound of Nadiah laughing, the little hesitations I couldn't explain. I also carried the reason I had made this journey in the first place. Beneath every new possibility was the same tired part of me that had wanted somewhere to put everything down.", "ch10-002"),
  beat("ch10-002", stages.madinah, "adult-aleem",
    "Imran stayed easy company. We could walk together without giving each other a report on every thought. Sometimes he pointed something out and I realised I had stopped noticing what was around me. I would look where he was looking, answer him, and come back to the place we had travelled so far to reach.", "ch10-003"),
  beat("ch10-003", stages.prayer, "adult-aleem",
    "In Masjidil Nabawi, I found a moment alone. There were other people around, but no one was waiting for me to speak or watching for the right expression on my face. I sat and allowed myself to become still. The quiet did not arrive all at once. My mind kept trying to continue conversations that weren't happening anymore.", "ch10-004"),
  beat("ch10-004", stages.prayer, "adult-aleem",
    "I noticed my hands first. They had settled in my lap, yet I was still holding myself as if I needed to be ready for something. My shoulders were tight. I let them lower a little. Around me were small sounds of people shifting, footsteps passing and fading, the life of the mosque continuing while I sat within it.", "ch10-005"),
  beat("ch10-005", stages.prayer, "adult-aleem",
    "For so long, whenever I thought about my love life, I began explaining. What I had tried. What I had given. Why the hurt had lasted. I could tell the story in a way that made every disappointment lead neatly to the next. Sitting there, I found I had very little desire to make the account convincing.", "ch10-prayer-honesty"),
  beat("ch10-prayer-honesty", stages.prayer, "adult-aleem",
    "I looked down for a while. There was something difficult about admitting how much I still wanted to be loved, after all the times I had said I was done with it. Here I could admit it without somebody telling me to be patient or asking what had happened. I could begin with the wanting itself, and the fact that I didn't know what to do with it anymore.", "ch10-006"),
  beat("ch10-006", stages.prayer, "adult-aleem",
    "I made a small doa about love. I cannot give its exact words back to you. What I remember is wanting God to help me with this part of my life: guide me towards what was good, ease what I was carrying, help me find peace with what I could not make happen. It was simple enough to come from somewhere beneath the explanations.", "ch10-007"),
  beat("ch10-007", stages.prayer, "adult-aleem",
    "The familiar faces came to mind without lining up into an argument. People I had loved. People I had hoped would love me. The younger versions of myself who had waited beside a phone or travelled home with things they couldn't say. I felt how tired they all were. I was tired of carrying them as if none of those days had ended.", "ch10-008"),
  beat("ch10-008", stages.prayer, "adult-aleem",
    "I didn't know what the next part of my life should look like. Even here, with Nadiah close again, I couldn't turn possibility into certainty. I let that be part of what I brought to God. The wanting, the disappointment, the fear that being alone meant something had gone wrong with me. There was no need to tidy it first.", "ch10-009"),
  beat("ch10-009", stages.release, "adult-aleem",
    "Then a breath left me. A long, unplanned sigh, deeper than the ordinary breaths before it. It felt as if something had come out with it, something I had been keeping pressed inside my chest without knowing how firmly I held it. I remained still, surprised by the space it seemed to leave behind.", "ch10-010"),
  beat("ch10-010", stages.release, "adult-aleem",
    "I breathed in again. There was room. I could feel the air arrive without the familiar tightness gathering around it. My hands rested where they were. Nothing dramatic happened in the space around me; people continued with their own moments. Inside, I felt an enormous relief, so quiet that I wanted to sit carefully and let it reach the rest of me.", "ch10-release-stillness"),
  beat("ch10-release-stillness", stages.prayerAfter, "adult-aleem",
    "I waited for the ache to gather itself again out of habit. It had accompanied so many quiet moments that its absence felt unfamiliar. A thought of the past crossed my mind and passed through. I didn't need to follow it all the way back. I could remain seated here, aware of where I was, feeling the next breath come as easily as the last.", "ch10-011"),
  beat("ch10-011", stages.prayerAfter, "adult-aleem",
    "The memories were still there. I could bring one close and recognise it. But the weight that usually came with it had loosened. I no longer felt caught inside the worst part of each story, bracing for it to happen again. I sat in Masjidil Nabawi and felt free in a way I had almost forgotten was possible.", "ch10-choice-release"),
  choice("ch10-choice-release", "chapter-10", stages.prayerAfter,
    "What did I feel able to put down?", [
      { id: "release-resentment", label: "The resentment I kept bringing into today.", next: "ch10-release-resentment" },
      { id: "release-proof", label: "The need to prove I deserved to be chosen.", next: "ch10-release-proof" },
      { id: "release-fear", label: "The fear that every beginning would hurt again.", next: "ch10-release-fear" },
    ]),
  beat("ch10-release-resentment", stages.prayerAfter, "adult-aleem",
    "I had kept the hurt close because loosening my hold on it felt like letting somebody dismiss what happened. Now I could remember it without holding it against every new day. I wanted to live in this one.", "ch10-release-join"),
  beat("ch10-release-proof", stages.prayerAfter, "adult-aleem",
    "So much effort had gone into making myself impossible to overlook. I felt tired just thinking of it. Sitting here, I could stop presenting reasons someone should love me. I could let my hands be empty for a while.", "ch10-release-join"),
  beat("ch10-release-fear", stages.prayerAfter, "adult-aleem",
    "I didn't want to reach every new person already expecting the familiar ending. For once that expectation felt like something I could set beside me. I could meet the next part of my life when it actually arrived.", "ch10-release-join"),
  beat("ch10-release-join", stages.prayerAfter, "adult-aleem",
    "I stayed a little longer. There was no answer naming who I would marry, no instruction to go back to Nadiah. There was this relief, and it was enough to hold my attention. I had asked for help with love. I began to feel how much of that help could be the freedom to stop being afraid of it.", "ch10-012"),
  beat("ch10-012", stages.prayerAfter, "adult-aleem",
    "The old rule about Malay women seemed especially tired now. I had carried it from one disappointment into another life, avoiding people before I knew them. Here, I could feel the resentment beneath that habit letting go. I didn't want it choosing whom I allowed near me anymore. Someone new could be herself when I met her.", "ch10-room-ahead"),
  beat("ch10-room-ahead", stages.prayerAfter, "adult-aleem",
    "I imagined an ordinary introduction, the kind I used to step away from before it went anywhere. I could listen. I could ask a question because I wanted to know the answer. I would not have to begin by placing a stranger beside the people who had hurt me. The thought was small, but I felt how much space it opened in my life.", "ch10-013"),
  beat("ch10-013", stages.madinahRelief, "adult-aleem",
    "When I was with Imran again, he looked at me for a moment before speaking. I wondered whether something about the way I stood had changed. I certainly felt it: less effort in my chest, less urgency to resolve every thought before the day could continue. I could hear him without another conversation running underneath.", "ch10-014"),
  beat("ch10-014", stages.madinahRelief, "imran",
    "You okay?", "ch10-015"),
  beat("ch10-015", stages.madinahRelief, "aleem-adult",
    "Yeah. I feel lighter. I don't really know how to explain it yet.", "ch10-016"),
  beat("ch10-016", stages.madinahRelief, "imran",
    "No need to explain now. Come. We can walk a bit.", "ch10-017"),
  beat("ch10-017", stages.madinahTogether, "adult-aleem",
    "That lightness stayed with me when I saw Nadiah. I still liked the warmth in her greeting. I still knew how quickly one of her smiles could find the affectionate part of me. Forgiving her had not made her a stranger. It had made it possible to see her without needing every encounter to repair the past.", "ch10-018"),
  beat("ch10-018", stages.madinahTogether, "adult-aleem",
    "As we continued talking, I recognised the hesitation and longing I had noticed before. A pause, a thought she seemed to follow inward, the feeling that some part of her attention was elsewhere. I took those moments as a sign that her feelings for another man might still be there. It was an impression I formed, never a confession she gave me.", "ch10-019"),
  beat("ch10-019", stages.madinahTogether, "adult-aleem",
    "I couldn't know the whole of her heart. I could know that I was starting to lean towards a reunion while sensing she might be leaning elsewhere. That was enough to make me pause. I had lived inside that waiting before. This time I could recognise where my own hope was taking me before I built a life around it.", "ch10-020"),
  beat("ch10-020", stages.boundary, "adult-aleem",
    "I wanted us to have another chance; I could admit that quietly to myself. Yet I began to understand that we weren't meant to begin again together. I did not need to press her for a place she hadn't offered. Whatever remained unresolved for her was hers to understand. I could care about her while taking my own next step.", "ch10-choice-boundary"),
  choice("ch10-choice-boundary", "chapter-10", stages.boundary,
    "How could I understand this quiet decision?", [
      { id: "boundary-kindness", label: "I could keep the kindness and stop pursuing.", next: "ch10-boundary-kindness" },
      { id: "boundary-peace", label: "The peace I found could come with me.", next: "ch10-boundary-peace" },
      { id: "boundary-waiting", label: "I didn't need to wait for a place beside her.", next: "ch10-boundary-waiting" },
    ]),
  beat("ch10-boundary-kindness", stages.boundary, "adult-aleem",
    "I could answer her warmly, enjoy a conversation, and let it end where it ended. Affection didn't have to become pursuit. I wanted the gentleness we had found again to survive without asking it to promise me more.", "ch10-boundary-join"),
  beat("ch10-boundary-peace", stages.boundary, "adult-aleem",
    "I thought of the breath that had left me in the mosque. That relief belonged to this journey even if Nadiah and I never became a couple again. I could carry it forward without carrying another expectation for her.", "ch10-boundary-join"),
  beat("ch10-boundary-waiting", stages.boundary, "adult-aleem",
    "I knew how to make waiting look like an ordinary friendship. I had done it for years. This time I wanted to let my future stay open, instead of quietly keeping it empty until somebody else was ready.", "ch10-boundary-join"),
  beat("ch10-boundary-join", stages.boundary, "adult-aleem",
    "I made no announcement. There was no farewell conversation for her to answer. The decision belonged in the small things I would do next: stop seeking another moment alone, stop returning to each pause for a possible promise, remain kind when we met. I could step away from pursuing her without making the warmth between us something to regret.", "ch10-boundary-practice"),
  beat("ch10-boundary-practice", stages.boundary, "adult-aleem",
    "When a conversation finished, I let myself turn back towards the rest of the group. For a moment the old impulse remained: find one more thing to say, keep the opening there a little longer. I noticed it, then allowed the moment to finish. There were other people to speak to and a whole journey around me that I wanted to be present for.", "ch10-021"),
  beat("ch10-021", stages.ordinaryCompany, "adult-aleem",
    "The group still had its familiar places for me. Kak Mariam would catch my eye and ask how I was. Abang Yusuf could turn a small observation into a conversation that wandered pleasantly for a while. I joined them and found I had more attention to give. I wasn't spending every spare moment trying to interpret someone else.", "ch10-022"),
  beat("ch10-022", stages.ordinaryCompany, "mariam",
    "Aleem, come sit with us. Every time I see you standing, I feel like I'm taking your chair.", "ch10-023"),
  beat("ch10-023", stages.ordinaryCompany, "aleem-adult",
    "Kak, you already offered me a seat before I even saw the chair.", "ch10-024"),
  beat("ch10-024", stages.ordinaryCompany, "yusuf",
    "Then you had better take it. Very difficult to win this argument.", "ch10-025"),
  beat("ch10-025", stages.ordinaryCompany, "adult-aleem",
    "I sat, smiling before I had found something to say. Their company had become one of the quiet comforts of the trip. There was no particular performance needed from me. I could contribute to the conversation or listen, and remain welcome either way. I liked seeing how often they made room for other people within their ease with each other.", "ch10-couple-ease"),
  beat("ch10-couple-ease", stages.ordinaryCompany, "adult-aleem",
    "Yusuf would pause to let Mariam add something, then pick up the thread without needing to start again. Sometimes they disagreed about a small detail and laughed when neither would give way. I watched them with a feeling I couldn't have managed at home: pleasure in somebody else's companionship, without immediately measuring the empty space beside me.", "ch10-026"),
  beat("ch10-026", stages.ordinaryCompany, "adult-aleem",
    "I thought about how I had felt before leaving home, alone in my room and almost ready to stop wanting love entirely. Here I was, sitting with people whose kindness had become familiar, feeling able to imagine a future again. I hadn't planned this version of the journey. I was grateful to be inside it.", "ch10-027"),
  beat("ch10-027", stages.introduction, "adult-aleem",
    "Mariam turned towards me as our conversation found a pause. There was something she wanted to tell me; I could see it in the way she waited until she had my attention. I settled back in the chair and listened.", "epilogue-001"),
] as const satisfies readonly StoryNode[];
