import type { StoryNode } from "../engine/types";
import { choice, line } from "./helpers";
import { stages } from "./stages";

export const chapterTwoANodes = [
  line(
    "ch2-001",
    "chapter-2",
    stages.boysClassroom,
    "adult-aleem",
    "My secondary school was a boys' school. Every classroom, assembly, and crowded canteen table made that fact completely unremarkable. Girls belonged to other schools, other buses, and stories told by friends with suspicious confidence.",
    "ch2-002",
  ),
  line(
    "ch2-002",
    "chapter-2",
    stages.boysClassroom,
    "adult-aleem",
    "Most days were a familiar rhythm of lessons, jokes, and trying not to be noticed when homework was incomplete. I had grown upward so quickly that my old self felt stored in somebody else's photographs.",
    "ch2-003",
  ),
  line(
    "ch2-003",
    "chapter-2",
    stages.boysClassroom,
    "adult-aleem",
    "Then, once a week, I travelled to a mixed school for third-language class. We kept our own uniforms; the borrowed campus was only a meeting place for students arriving from different schools.",
    "ch2-004",
  ),
  line(
    "ch2-004",
    "chapter-2",
    stages.languageEstablishing,
    "adult-aleem",
    "The room felt different before anyone spoke. Navy skirts and white shirts mixed with the plain white uniforms from my school. New voices filled the spaces where routine usually sat.",
    "ch2-005",
  ),
  line(
    "ch2-005",
    "chapter-2",
    stages.languageAleem,
    "adult-aleem",
    "I became intensely aware of my arms, my glasses, and the possibility that I had forgotten how to sit naturally.",
    "ch2-006",
  ),
  line(
    "ch2-006",
    "chapter-2",
    stages.languageHana,
    "adult-aleem",
    "Hana sat a few places away. She was tall, with long straight hair and glasses that she nudged upward whenever she concentrated. She listened before speaking, then asked questions that made the teacher pause.",
    "ch2-007",
  ),
  line(
    "ch2-007",
    "chapter-2",
    stages.languageHana,
    "hana",
    "Do you know what page we are supposed to be on?",
    "ch2-008",
  ),
  line(
    "ch2-008",
    "chapter-2",
    stages.languageHana,
    "aleem-sec",
    "Page... forty-two. I think.",
    "ch2-009",
  ),
  line(
    "ch2-009",
    "chapter-2",
    stages.languageHana,
    "hana",
    "The teacher wrote fifty-four on the board.",
    "ch2-010",
  ),
  line(
    "ch2-010",
    "chapter-2",
    stages.languageHana,
    "aleem-sec",
    "Right. I was checking whether you were paying attention.",
    "ch2-011",
  ),
  line(
    "ch2-011",
    "chapter-2",
    stages.languageSmile,
    "hana",
    "Very helpful. Terima kasih—thank you, page forty-two.",
    "ch2-012",
  ),
  line(
    "ch2-012",
    "chapter-2",
    stages.languageSmile,
    "adult-aleem",
    "Her smile turned my embarrassment into a private joke. The next week she asked if I had finally found the correct page. The week after that, I saved her a seat.",
    "ch2-013",
  ),
  line(
    "ch2-013",
    "chapter-2",
    stages.languageSmile,
    "adult-aleem",
    "Conversation arrived in pieces: complaints about vocabulary lists, comparisons of long commutes, recommendations for songs. She was observant without making a show of it.",
    "ch2-014",
  ),
  line(
    "ch2-014",
    "chapter-2",
    stages.languageSmile,
    "hana",
    "You always draw boxes in the margins. Is that meant to be a building?",
    "ch2-015",
  ),
  line(
    "ch2-015",
    "chapter-2",
    stages.languageSmile,
    "aleem-sec",
    "A base. You build walls, add rooms, and make systems so everything works together.",
    "ch2-016",
  ),
  line(
    "ch2-016",
    "chapter-2",
    stages.languageSmile,
    "hana",
    "You sound happier explaining that than anything in this textbook.",
    "ch2-017",
  ),
  line(
    "ch2-017",
    "chapter-2",
    stages.languageAleem,
    "adult-aleem",
    "She was right. I loved digital spaces where effort produced visible structure. You placed one block, then another, and the empty world became somewhere people wanted to stay.",
    "ch2-018",
  ),
  line(
    "ch2-018",
    "chapter-2",
    stages.languageHana,
    "adult-aleem",
    "I also liked Hana, which was less orderly. Every good conversation made the next one feel more important. Every goodbye left me rehearsing what I should have said.",
    "ch2-019",
  ),
  line(
    "ch2-019",
    "chapter-2",
    stages.courtyardFaris,
    "adult-aleem",
    "Faris noticed before I told him. He was short and round, with fluffy hair, glasses, and the relaxed confidence of someone who considered awkwardness a problem other people had.",
    "ch2-020",
  ),
  line(
    "ch2-020",
    "chapter-2",
    stages.courtyardFaris,
    "faris",
    "You wait until Hana leaves before you walk to the gate, then somehow reach the gate at the same time. Very subtle, bro.",
    "ch2-021",
  ),
  line(
    "ch2-021",
    "chapter-2",
    stages.courtyardFaris,
    "aleem-sec",
    "It is a public walkway.",
    "ch2-022",
  ),
  line(
    "ch2-022",
    "chapter-2",
    stages.courtyardFarisConfident,
    "faris",
    "And your face is public evidence. You like her. Shall I help?",
    "ch2-023",
  ),
  line(
    "ch2-023",
    "chapter-2",
    stages.courtyardFaris,
    "aleem-sec",
    "Help how?",
    "ch2-024",
  ),
  line(
    "ch2-024",
    "chapter-2",
    stages.courtyardFarisConfident,
    "faris",
    "I can speak to her. Nothing dramatic. Just tell her you are interested and ask whether she would be comfortable talking to you about it.",
    "ch2-choice-wingman",
  ),
  choice(
    "ch2-choice-wingman",
    "chapter-2",
    stages.courtyardFarisConfident,
    "What should Faris say on Aleem's behalf?",
    [
      {
        id: "wingman-simple",
        label: "Keep it simple: “Aleem likes you.”",
        next: "ch2-wingman-simple-001",
      },
      {
        id: "wingman-sincere",
        label: "Be sincere: “He values your time together.”",
        next: "ch2-wingman-sincere-001",
      },
      {
        id: "wingman-no-pressure",
        label: "Make space: “There’s no pressure either way.”",
        next: "ch2-wingman-pressure-001",
      },
    ],
  ),
  line(
    "ch2-wingman-simple-001",
    "chapter-2",
    stages.courtyardFaris,
    "aleem-sec",
    "Just say I like her. Simple. Before I overthink it and move to another country.",
    "ch2-wingman-simple-002",
  ),
  line(
    "ch2-wingman-simple-002",
    "chapter-2",
    stages.courtyardFarisConfident,
    "faris",
    "Direct and efficient. I knew there was hope for you.",
    "ch2-025",
  ),
  line(
    "ch2-wingman-sincere-001",
    "chapter-2",
    stages.courtyardFaris,
    "aleem-sec",
    "Tell her I really value the time we spend together. And that I would like it to mean something, if she does too.",
    "ch2-wingman-sincere-002",
  ),
  line(
    "ch2-wingman-sincere-002",
    "chapter-2",
    stages.courtyardFarisConfident,
    "faris",
    "Wah. Very sincere. I will remove the part where your voice nearly disappeared.",
    "ch2-025",
  ),
  line(
    "ch2-wingman-pressure-001",
    "chapter-2",
    stages.courtyardFaris,
    "aleem-sec",
    "Make sure she knows there is no pressure. If she does not feel the same, I do not want class to become uncomfortable.",
    "ch2-wingman-pressure-002",
  ),
  line(
    "ch2-wingman-pressure-002",
    "chapter-2",
    stages.courtyardFaris,
    "faris",
    "Good. I will ask, not corner her. Wingman service with ethics.",
    "ch2-025",
  ),
  line(
    "ch2-025",
    "chapter-2",
    stages.courtyardFarisConfident,
    "adult-aleem",
    "Faris walked across the courtyard before my courage could object. He spoke to Hana briefly, without an audience. She looked surprised, glanced toward me, and asked him something I could not hear.",
    "ch2-026",
  ),
  line(
    "ch2-026",
    "chapter-2",
    stages.courtyardFaris,
    "faris",
    "She said you should tell her yourself. This is good news, by the way.",
    "ch2-027",
  ),
  line(
    "ch2-027",
    "chapter-2",
    stages.courtyardFaris,
    "aleem-sec",
    "How is that good news? Your entire job was to prevent me from doing that.",
    "ch2-028",
  ),
  line(
    "ch2-028",
    "chapter-2",
    stages.courtyardFarisConfident,
    "faris",
    "My job was to open the door. Walking through is your character development.",
    "ch2-029",
  ),
  line(
    "ch2-029",
    "chapter-2",
    stages.courtyardHana,
    "aleem-sec",
    "Hi. I assume Faris gave a very calm and accurate presentation.",
    "ch2-030",
  ),
  line(
    "ch2-030",
    "chapter-2",
    stages.courtyardHana,
    "hana",
    "He used the phrase 'important diplomatic matter.'",
    "ch2-031",
  ),
  line(
    "ch2-031",
    "chapter-2",
    stages.courtyardHana,
    "aleem-sec",
    "That sounds like him. The accurate part is that I like you.",
    "ch2-032",
  ),
  line(
    "ch2-032",
    "chapter-2",
    stages.courtyardHana,
    "hana",
    "I like you too. I was not sure whether you were interested or just always lost after class.",
    "ch2-033",
  ),
  line(
    "ch2-033",
    "chapter-2",
    stages.courtyardHappy,
    "aleem-sec",
    "Both can be true.",
    "ch2-034",
  ),
  line(
    "ch2-034",
    "chapter-2",
    stages.courtyardHappy,
    "adult-aleem",
    "We agreed to try. No grand declaration, only mutual relief and the shy happiness of discovering that hope had been shared.",
    "ch2-035",
  ),
  line(
    "ch2-035",
    "chapter-2",
    stages.languageSmile,
    "adult-aleem",
    "For a while, the weekly class became the centre of my calendar. Hana and I exchanged messages between lessons and stretched the walk to the bus stop whenever time allowed.",
    "ch2-036",
  ),
  line(
    "ch2-036",
    "chapter-2",
    stages.courtyardHappy,
    "hana",
    "You know we could walk directly to the gate.",
    "ch2-037",
  ),
  line(
    "ch2-037",
    "chapter-2",
    stages.courtyardHappy,
    "aleem-sec",
    "This route has better... trees.",
    "ch2-038",
  ),
  line(
    "ch2-038",
    "chapter-2",
    stages.courtyardHappy,
    "hana",
    "We have passed the same tree twice.",
    "ch2-039",
  ),
  line(
    "ch2-039",
    "chapter-2",
    stages.courtyardHappy,
    "adult-aleem",
    "She knew what I was doing and walked the second circle anyway. It was an ordinary kindness. I wish I had understood then how relationships are built from attention to ordinary things.",
    "ch2-040",
  ),
  line(
    "ch2-040",
    "chapter-2",
    stages.bedroomPcDay,
    "adult-aleem",
    "At home, another world was taking shape. I had started running a Minecraft server: part community, part small business, part endlessly demanding machine.",
    "ch2-041",
  ),
  line(
    "ch2-041",
    "chapter-2",
    stages.bedroomPcDay,
    "adult-aleem",
    "I learned to configure systems, settle disputes, organise volunteers, and keep strangers returning. Every solved problem revealed two more, which felt less like failure than an invitation.",
    "ch2-042",
  ),
  line(
    "ch2-042",
    "chapter-2",
    stages.serverProud,
    "adult-aleem",
    "Players joined. A community formed. Support began arriving from people who valued the place enough to contribute. I was making real money from something I had built in my bedroom.",
    "ch2-043",
  ),
  line(
    "ch2-043",
    "chapter-2",
    stages.serverProud,
    "aleem-sec",
    "Hana, someone supported the server again. They said it is the first place online where their friends all enjoy playing together.",
    "ch2-044",
  ),
  line(
    "ch2-044",
    "chapter-2",
    stages.serverProud,
    "hana",
    "That is actually amazing. You made a place people care about.",
    "ch2-045",
  ),
  line(
    "ch2-045",
    "chapter-2",
    stages.bedroomPcDay,
    "adult-aleem",
    "Her pride mattered to me. The server was not merely a distraction. It taught me leadership, technical patience, and the thrilling fact that my ideas could have value beyond school.",
    "ch2-046",
  ),
  line(
    "ch2-046",
    "chapter-2",
    stages.bedroomPcNight,
    "adult-aleem",
    "But achievement came with an alarm bell. The server did not care whether I had class the next morning. Problems arrived whenever players were awake, which seemed to be always.",
    "ch2-047",
  ),
  line(
    "ch2-047",
    "chapter-2",
    stages.serverCrisis,
    "adult-aleem",
    "One night, three demands collided: Hana was waiting for a promised call, unfinished revision lay beside the keyboard, and the server began failing under a rush of activity.",
    "ch2-choice-priority",
  ),
  choice(
    "ch2-choice-priority",
    "chapter-2",
    stages.serverCrisis,
    "What does Aleem attend to first?",
    [
      {
        id: "priority-hana",
        label: "Call Hana, even if the server has to wait.",
        next: "ch2-priority-hana-001",
      },
      {
        id: "priority-server",
        label: "Stabilise the server, then call her.",
        next: "ch2-priority-server-001",
      },
      {
        id: "priority-study",
        label: "Step away and finish the revision first.",
        next: "ch2-priority-study-001",
      },
    ],
  ),
  line(
    "ch2-priority-hana-001",
    "chapter-2",
    stages.bedroomPcNight,
    "adult-aleem",
    "I called Hana. For ten minutes, I listened properly while warning messages multiplied behind the call window. She laughed once, and the sound made the choice feel simple.",
    "ch2-priority-hana-002",
  ),
  line(
    "ch2-priority-hana-002",
    "chapter-2",
    stages.serverCrisis,
    "adult-aleem",
    "Then I rushed back to the server and worked far past midnight. Years later, I remembered that attention was possible—but without boundaries, I treated it as an exception I could not sustain.",
    "ch2-048",
  ),
  line(
    "ch2-priority-server-001",
    "chapter-2",
    stages.serverCrisis,
    "adult-aleem",
    "I told myself I needed only ten minutes to stabilise the server. Ten became forty. By the time I reached for my phone, Hana's message simply said she was going to sleep.",
    "ch2-priority-server-002",
  ),
  line(
    "ch2-priority-server-002",
    "chapter-2",
    stages.bedroomPcNight,
    "adult-aleem",
    "Years later, I remembered how reasonable every delay sounded from inside it. I never chose to neglect her in one dramatic moment. I chose 'just a little longer' again and again.",
    "ch2-048",
  ),
  line(
    "ch2-priority-study-001",
    "chapter-2",
    stages.bedroomPcNight,
    "adult-aleem",
    "I closed the dashboard and revised first. Yet my eyes kept moving between the textbook and two silent screens, absorbing little from the page and giving nothing fully to either person or server.",
    "ch2-priority-study-002",
  ),
  line(
    "ch2-priority-study-002",
    "chapter-2",
    stages.bedroomPcNight,
    "adult-aleem",
    "Years later, I remembered that choosing the responsible task was not enough if I had already built a life with no margin. The crisis was not that night; it was the pattern around it.",
    "ch2-048",
  ),
] as const satisfies readonly StoryNode[];

