import type { StoryNode } from "../engine/types";
import { choice, line } from "./helpers";
import { stages } from "./stages";

export const chapterTwoBNodes = [
  line(
    "ch2-048",
    "chapter-2",
    stages.bedroomPcNight,
    "adult-aleem",
    "The server recovered. The homework was eventually submitted. Hana and I spoke again. From the outside, nothing had broken. That made it easy to ignore what the night was showing me.",
    "ch2-049",
  ),
  line(
    "ch2-049",
    "chapter-2",
    stages.serverProud,
    "adult-aleem",
    "Success made the pattern harder to challenge. More players meant more responsibility and more income. Every late night produced evidence that the late night had been worthwhile.",
    "ch2-050",
  ),
  line(
    "ch2-050",
    "chapter-2",
    stages.bedroomPcNight,
    "adult-aleem",
    "Schoolwork was different. One neglected topic did not immediately collapse. A missed revision session created no flashing alert. The consequences waited quietly, gathering weight beyond the edge of the screen.",
    "ch2-051",
  ),
  line(
    "ch2-051",
    "chapter-2",
    stages.languageSmile,
    "adult-aleem",
    "Hana waited quietly too, at first. I still arrived at language class. I still smiled when I saw her. I mistook continued affection for proof that affection required no maintenance.",
    "ch2-052",
  ),
  line(
    "ch2-052",
    "chapter-2",
    stages.languageHana,
    "hana",
    "You disappeared last night. Everything okay?",
    "ch2-053",
  ),
  line(
    "ch2-053",
    "chapter-2",
    stages.languageHana,
    "aleem-sec",
    "Server issue. It was quite bad, but I fixed it.",
    "ch2-054",
  ),
  line(
    "ch2-054",
    "chapter-2",
    stages.languageHana,
    "hana",
    "I am glad you fixed it. I was worried because you said you would call.",
    "ch2-055",
  ),
  line(
    "ch2-055",
    "chapter-2",
    stages.languageHana,
    "aleem-sec",
    "Sorry. Next time I will message first.",
    "ch2-056",
  ),
  line(
    "ch2-056",
    "chapter-2",
    stages.languageSmile,
    "adult-aleem",
    "I meant the apology. I also meant the promise. Intentions were never the missing ingredient; I lacked the habit of turning them into action.",
    "ch2-057",
  ),
  line(
    "ch2-057",
    "chapter-2",
    stages.serverCrisis,
    "adult-aleem",
    "Next time, I remembered only after the crisis had started. The time after that, I sent a quick message so vague it asked her to wait without telling her for how long.",
    "ch2-058",
  ),
  line(
    "ch2-058",
    "chapter-2",
    stages.bedroomPcNight,
    "adult-aleem",
    "My days narrowed. At school, I thought about the server. At home, I managed it. When Hana spoke, part of me listened while another part counted unresolved tasks.",
    "ch2-059",
  ),
  line(
    "ch2-059",
    "chapter-2",
    stages.hanaConcerned,
    "hana",
    "You are here, but sometimes it feels like you are waiting to go back to your computer.",
    "ch2-060",
  ),
  line(
    "ch2-060",
    "chapter-2",
    stages.hanaConcerned,
    "aleem-sec",
    "That is not fair. I have a lot to manage right now.",
    "ch2-061",
  ),
  line(
    "ch2-061",
    "chapter-2",
    stages.hanaConcerned,
    "hana",
    "I know you do. I am not asking you to stop caring about it. I am asking whether there is still room for me.",
    "ch2-062",
  ),
  line(
    "ch2-062",
    "chapter-2",
    stages.hanaConcerned,
    "adult-aleem",
    "Her question reached the part of me that knew she was right. Another part heard criticism of the thing I was proudest of and raised its defences.",
    "ch2-063",
  ),
  line(
    "ch2-063",
    "chapter-2",
    stages.hanaConcerned,
    "aleem-sec",
    "There is room. This busy period will settle down. I just need you to be patient with me.",
    "ch2-064",
  ),
  line(
    "ch2-064",
    "chapter-2",
    stages.hanaConcerned,
    "hana",
    "I have been patient, Aleem.",
    "ch2-065",
  ),
  line(
    "ch2-065",
    "chapter-2",
    stages.bedroomPcNight,
    "adult-aleem",
    "I carried those words home, placed them beside all my other unfinished obligations, and opened the server dashboard.",
    "ch2-066",
  ),
  line(
    "ch2-066",
    "chapter-2",
    stages.boysClassroomTired,
    "adult-aleem",
    "My school results began reflecting the same imbalance. Teachers marked gaps I promised to close. Notes accumulated. I understood each warning separately and failed to see the shape they formed together.",
    "ch2-067",
  ),
  line(
    "ch2-067",
    "chapter-2",
    stages.boysClassroomTired,
    "aleem-sec",
    "I will catch up during the break.",
    "ch2-068",
  ),
  line(
    "ch2-068",
    "chapter-2",
    stages.boysClassroomTired,
    "adult-aleem",
    "The break arrived carrying server plans. Catching up moved to the following week, then the next month, always close enough to sound possible.",
    "ch2-069",
  ),
  line(
    "ch2-069",
    "chapter-2",
    stages.languageHana,
    "adult-aleem",
    "At language class, the easy rhythm between Hana and me faded. We still sat near each other, but conversation became practical. Page numbers. Assignment dates. Which bus was coming.",
    "ch2-070",
  ),
  line(
    "ch2-070",
    "chapter-2",
    stages.hanaDistant,
    "aleem-sec",
    "Are you angry with me?",
    "ch2-071",
  ),
  line(
    "ch2-071",
    "chapter-2",
    stages.hanaDistant,
    "hana",
    "I am tired of having the same conversation.",
    "ch2-072",
  ),
  line(
    "ch2-072",
    "chapter-2",
    stages.hanaDistant,
    "aleem-sec",
    "Then tell me what you want me to do.",
    "ch2-073",
  ),
  line(
    "ch2-073",
    "chapter-2",
    stages.hanaDistant,
    "hana",
    "I wanted you to want to be present. I do not know how to turn that into instructions.",
    "ch2-074",
  ),
  line(
    "ch2-074",
    "chapter-2",
    stages.hanaDistant,
    "adult-aleem",
    "I heard the sadness, but I also heard an impossible request. At sixteen, I believed effort counted only when it looked like solving. Presence did not feel measurable enough to manage.",
    "ch2-075",
  ),
  line(
    "ch2-075",
    "chapter-2",
    stages.languageEstablishing,
    "adult-aleem",
    "After that, there was no single breakup conversation. There were shorter replies and seats left unsaved. We drifted into a silence I recognised from Alya, though this time I was helping create it.",
    "ch2-076",
  ),
  line(
    "ch2-076",
    "chapter-2",
    stages.mutualFriend,
    "mutual-friend",
    "Aleem, I thought you should hear it from someone. Hana has moved on.",
    "ch2-077",
  ),
  line(
    "ch2-077",
    "chapter-2",
    stages.mutualFriendHurt,
    "adult-aleem",
    "The words landed in an ordinary courtyard after an ordinary class. For a moment, even the sounds around us seemed badly timed.",
    "ch2-choice-friend",
  ),
  choice(
    "ch2-choice-friend",
    "chapter-2",
    stages.mutualFriendHurt,
    "How does Aleem respond to the mutual friend?",
    [
      {
        id: "friend-confirm",
        label: "Ask calmly: “Did Hana say that herself?”",
        next: "ch2-friend-confirm-001",
      },
      {
        id: "friend-defend",
        label: "Push back: “You don’t know our relationship.”",
        next: "ch2-friend-defend-001",
      },
      {
        id: "friend-silent",
        label: "Say nothing and absorb the news.",
        next: "ch2-friend-silent-001",
      },
    ],
  ),
  line(
    "ch2-friend-confirm-001",
    "chapter-2",
    stages.mutualFriendHurt,
    "aleem-sec",
    "Did Hana say that herself? I need to hear it from her, not through somebody else.",
    "ch2-friend-confirm-002",
  ),
  line(
    "ch2-friend-confirm-002",
    "chapter-2",
    stages.mutualFriend,
    "mutual-friend",
    "That is fair. Please talk to her. I only told you because I thought nobody had.",
    "ch2-078",
  ),
  line(
    "ch2-friend-defend-001",
    "chapter-2",
    stages.mutualFriendHurt,
    "aleem-sec",
    "You do not know our relationship. Things have been difficult, but that does not mean you can decide what happened.",
    "ch2-friend-defend-002",
  ),
  line(
    "ch2-friend-defend-002",
    "chapter-2",
    stages.mutualFriend,
    "mutual-friend",
    "I am not deciding. I am telling you because you deserve a direct conversation. Ask her.",
    "ch2-078",
  ),
  line(
    "ch2-friend-silent-001",
    "chapter-2",
    stages.mutualFriendHurt,
    "adult-aleem",
    "I said nothing. My friend waited, then gently repeated that I should speak to Hana myself. Silence did not make the news less real.",
    "ch2-friend-silent-002",
  ),
  line(
    "ch2-friend-silent-002",
    "chapter-2",
    stages.mutualFriendHurt,
    "adult-aleem",
    "Years later, I would recognise the old reflex from Alya's message: freeze, wait, and hope somebody else carries the difficult words the rest of the way.",
    "ch2-078",
  ),
  line(
    "ch2-078",
    "chapter-2",
    stages.hanaDistant,
    "adult-aleem",
    "I asked Hana to stay after class. She agreed. For once, I closed every other task in my mind and gave the conversation my full attention.",
    "ch2-079",
  ),
  line(
    "ch2-079",
    "chapter-2",
    stages.hanaDistant,
    "aleem-sec",
    "Someone told me you have moved on. Is that true?",
    "ch2-080",
  ),
  line(
    "ch2-080",
    "chapter-2",
    stages.hanaDistant,
    "hana",
    "Yes. I should have told you directly. I kept waiting for us to feel like us again, and then I stopped believing that would happen.",
    "ch2-081",
  ),
  line(
    "ch2-081",
    "chapter-2",
    stages.hanaConcerned,
    "aleem-sec",
    "You could have said your feelings changed. Hearing it from somebody else makes me feel foolish.",
    "ch2-082",
  ),
  line(
    "ch2-082",
    "chapter-2",
    stages.hanaConcerned,
    "hana",
    "You are right. I avoided the final conversation, and I am sorry. But I did tell you I was lonely in this relationship. More than once.",
    "ch2-083",
  ),
  line(
    "ch2-083",
    "chapter-2",
    stages.hanaConcerned,
    "adult-aleem",
    "Both truths occupied the same space. She should have told me clearly when it ended. I had also taught her, through repeated absence, that my promises to change were not reliable.",
    "ch2-084",
  ),
  line(
    "ch2-084",
    "chapter-2",
    stages.hanaConcerned,
    "aleem-sec",
    "I was busy, but that is not the whole answer. I made you wait too often. I kept assuming there would be another chance to do better.",
    "ch2-085",
  ),
  line(
    "ch2-085",
    "chapter-2",
    stages.hanaConcerned,
    "hana",
    "I know the server matters to you. I never wanted you to fail at it. I just could not keep being the thing you returned to after everything urgent was finished.",
    "ch2-086",
  ),
  line(
    "ch2-086",
    "chapter-2",
    stages.hanaDistant,
    "aleem-sec",
    "I understand. Or I think I am starting to.",
    "ch2-087",
  ),
  line(
    "ch2-087",
    "chapter-2",
    stages.languageEstablishing,
    "adult-aleem",
    "We parted without cruelty. That did not make it painless. Hana had been patient until patience began costing her too much; I had noticed the cost only after she stopped paying it.",
    "ch2-088",
  ),
  line(
    "ch2-088",
    "chapter-2",
    stages.aloneGuilty,
    "adult-aleem",
    "At home, the server welcomed me with familiar notifications. For the first time, every alert sounded like evidence in a case against me.",
    "ch2-089",
  ),
  line(
    "ch2-089",
    "chapter-2",
    stages.aloneGuilty,
    "adult-aleem",
    "That was unfair too. The server had not taken control of my hands. It was a creation, an achievement, and a responsibility. I had chosen to give it boundaries only after other parts of life were damaged.",
    "ch2-090",
  ),
  line(
    "ch2-090",
    "chapter-2",
    stages.boysClassroomTired,
    "adult-aleem",
    "By 2013, the largest consequence was already waiting. O Levels were no longer a distant threat used by teachers to focus a noisy class. The examinations had dates.",
    "ch2-091",
  ),
  line(
    "ch2-091",
    "chapter-2",
    stages.boysClassroomTired,
    "adult-aleem",
    "I tried to compress years of inconsistent study into months. Topics I should have recognised looked newly introduced. Each revision session exposed how much foundation was missing beneath me.",
    "ch2-092",
  ),
  line(
    "ch2-092",
    "chapter-2",
    stages.bedroomPcNight,
    "adult-aleem",
    "I reduced my time online, but habits do not disappear when the timetable becomes frightening. Some nights I revised. Some nights I escaped into problems I still knew how to solve.",
    "ch2-093",
  ),
  line(
    "ch2-093",
    "chapter-2",
    stages.bedroomPcNight,
    "adult-aleem",
    "A server problem had a clear cause, tools, and grateful players when repaired. A page of questions could stare back without offering any clue where my understanding had first gone wrong.",
    "ch2-094",
  ),
  line(
    "ch2-094",
    "chapter-2",
    stages.examHall,
    "adult-aleem",
    "The examination hall smelled of paper and nervous stillness. Rows of desks faced the clock. When the papers turned over, the sound moved through the room like a single wave.",
    "ch2-095",
  ),
  line(
    "ch2-095",
    "chapter-2",
    stages.examHall,
    "adult-aleem",
    "Some questions opened. Others remained locked no matter how carefully I read them. I wrote what I could, crossed out what I could not defend, and watched minutes leave.",
    "ch2-096",
  ),
  line(
    "ch2-096",
    "chapter-2",
    stages.examHall,
    "aleem-sec",
    "Just keep moving. One question, then the next.",
    "ch2-097",
  ),
  line(
    "ch2-097",
    "chapter-2",
    stages.examHall,
    "adult-aleem",
    "There is dignity in continuing even when preparation has failed you. There is also no magic in it. Effort made during the paper could not replace all the effort deferred before it.",
    "ch2-098",
  ),
  line(
    "ch2-098",
    "chapter-2",
    stages.resultsHall,
    "adult-aleem",
    "Results day arrived beneath fluorescent lights. Around me, people compared expressions before they compared slips. Celebration and disappointment tried to occupy the same hall without looking at each other.",
    "ch2-099",
  ),
  line(
    "ch2-099",
    "chapter-2",
    stages.resultsHall,
    "adult-aleem",
    "I held the folded paper for a moment. Part of me still expected a rescue: some kinder arithmetic, some proof that worry had exaggerated everything.",
    "ch2-100",
  ),
  line(
    "ch2-100",
    "chapter-2",
    stages.resultsReveal,
    "adult-aleem",
    "The results were bad. Not one disappointing number, but an outcome that narrowed the paths I had imagined. I will not display the grades here. Their emotional weight mattered more than their digits.",
    "ch2-choice-results",
  ),
  choice(
    "ch2-choice-results",
    "chapter-2",
    stages.resultsReveal,
    "What thought does Aleem hold onto on results day?",
    [
      {
        id: "results-condemn",
        label: "“I ruined everything.”",
        next: "ch2-results-condemn-001",
      },
      {
        id: "results-honest",
        label: "“This is the consequence of my choices.”",
        next: "ch2-results-honest-001",
      },
      {
        id: "results-continue",
        label: "“I do not know the next path, but there must be one.”",
        next: "ch2-results-continue-001",
      },
    ],
  ),
  line(
    "ch2-results-condemn-001",
    "chapter-2",
    stages.resultsReveal,
    "aleem-sec",
    "I ruined everything. Everyone else gets to move forward, and I did this to myself.",
    "ch2-results-condemn-002",
  ),
  line(
    "ch2-results-condemn-002",
    "chapter-2",
    stages.darkBedroom,
    "adult-aleem",
    "That thought followed me home because it was absolute, and absolutes can feel simpler than uncertainty. Years later, I would learn that responsibility and permanent condemnation are not the same thing.",
    "ch2-101",
  ),
  line(
    "ch2-results-honest-001",
    "chapter-2",
    stages.resultsReveal,
    "aleem-sec",
    "This is the consequence of my choices. I cannot pretend the warnings were not there.",
    "ch2-results-honest-002",
  ),
  line(
    "ch2-results-honest-002",
    "chapter-2",
    stages.darkBedroom,
    "adult-aleem",
    "The thought was honest but incomplete. Years later, I would learn that owning a mistake should guide the next action, not become a weight carried forever as proof of unworthiness.",
    "ch2-101",
  ),
  line(
    "ch2-results-continue-001",
    "chapter-2",
    stages.resultsReveal,
    "aleem-sec",
    "I do not know what the next path is. I cannot see it from here. But there must be one.",
    "ch2-results-continue-002",
  ),
  line(
    "ch2-results-continue-002",
    "chapter-2",
    stages.darkBedroom,
    "adult-aleem",
    "It was more hope than I could consistently feel, but the sentence survived. Years later, I would understand that a path can exist before you are strong enough to see its shape.",
    "ch2-101",
  ),
  line(
    "ch2-101",
    "chapter-2",
    stages.darkBedroom,
    "adult-aleem",
    "The period after results was dark in a quiet way. I withdrew. I avoided questions about what came next because every answer seemed to expose the same failure.",
    "ch2-102",
  ),
  line(
    "ch2-102",
    "chapter-2",
    stages.darkBedroom,
    "adult-aleem",
    "My room, once alive with plans and player chatter, became a place where time passed without direction. Even the server's success felt difficult to hold beside the damage I associated with it.",
    "ch2-103",
  ),
  line(
    "ch2-103",
    "chapter-2",
    stages.darkBedroom,
    "adult-aleem",
    "I had lost Hana, disappointed myself academically, and reached the end of a road without the future I expected waiting there. Shame tried to combine those facts into one identity.",
    "ch2-104",
  ),
  line(
    "ch2-104",
    "chapter-2",
    stages.darkBedroom,
    "adult-aleem",
    "But I was not only the boy who neglected his studies. I was also the boy who had built something from nothing, earned trust from a community, and learned skills no examination measured.",
    "ch2-105",
  ),
  line(
    "ch2-105",
    "chapter-2",
    stages.darkBedroom,
    "adult-aleem",
    "And I was not only the boyfriend who became absent. I was a young person learning, painfully, that caring about someone is different from making room for them.",
    "ch2-106",
  ),
  line(
    "ch2-106",
    "chapter-2",
    stages.dawn,
    "adult-aleem",
    "Those kinder truths did not arrive all at once. First came smaller things: waking up, opening the curtains, answering one message, considering one route I had not planned.",
    "ch2-107",
  ),
  line(
    "ch2-107",
    "chapter-2",
    stages.dawn,
    "adult-aleem",
    "A bad result can close doors. It can change the route, cost time, and demand humility. What it cannot do is issue a final judgement on the life standing before it.",
    "ch2-108",
  ),
  line(
    "ch2-108",
    "chapter-2",
    stages.dawn,
    "adult-aleem",
    "I did not know that yet. I only knew morning kept arriving, annoyingly faithful, whether I felt ready for it or not.",
    "epilogue-001",
  ),
] as const satisfies readonly StoryNode[];

