import type { StoryNode } from "../engine/types";
import { choice, line } from "./helpers";
import { stages } from "./stages";

export const chapterFiveNodes = [
  line(
    "ch5-001",
    "chapter-5",
    stages.aLevelResults,
    "adult-aleem",
    "Results day in 2016 returned us to school in clothes that no longer matched the timetable. We occupied our old gathering places without belonging to the routine around them, carrying envelopes and trying to read one another's faces.",
    "ch5-002",
  ),
  line(
    "ch5-002",
    "chapter-5",
    stages.aLevelResults,
    "adult-aleem",
    "When I saw my outcome, I checked it more than once. The exact grades remain private. What matters is that I had done well—well enough to feel a future opening where I once believed every useful door had closed.",
    "ch5-003",
  ),
  line(
    "ch5-003",
    "chapter-5",
    stages.aLevelResults,
    "aleem-sec",
    "I did it. I actually did it.",
    "ch5-004",
  ),
  line(
    "ch5-004",
    "chapter-5",
    stages.aLevelResults,
    "adult-aleem",
    "Pride arrived carefully, as though it expected somebody to challenge its right to be there. I thought of the dark room after O Levels, the school label I had repeated with embarrassment, and every evening spent rebuilding habits one page at a time.",
    "ch5-005",
  ),
  line(
    "ch5-005",
    "chapter-5",
    stages.aLevelResultsMeiLin,
    "adult-aleem",
    "Then I found Mei Lin. Her paper rested in both hands. She was not crying, but the stillness around her was different from concentration. Her results had fallen below what she had worked and hoped for.",
    "ch5-006",
  ),
  line(
    "ch5-006",
    "chapter-5",
    stages.aLevelResultsMeiLin,
    "mei-lin",
    "I know this is not the end of everything. Please do not give me the speech yet. I just need a while before I can believe it.",
    "ch5-007",
  ),
  line(
    "ch5-007",
    "chapter-5",
    stages.aLevelResultsMeiLin,
    "aleem-sec",
    "No speech. I can sit here and be quiet. I have at least some experience with results feeling heavier than paper.",
    "ch5-008",
  ),
  line(
    "ch5-008",
    "chapter-5",
    stages.aLevelResultsMeiLin,
    "adult-aleem",
    "My good news and her disappointment occupied the same afternoon. Supporting her did not require me to apologise for succeeding. Celebrating myself did not require me to hurry her out of grief.",
    "ch5-009",
  ),
  line(
    "ch5-009",
    "chapter-5",
    stages.jcDawn,
    "adult-aleem",
    "In the days afterward, our class exchanged plans and consolation. Mei Lin answered messages politely but sounded compressed, as if every conversation might become another demand to explain what had gone wrong.",
    "ch5-010",
  ),
  line(
    "ch5-010",
    "chapter-5",
    stages.jcDawn,
    "adult-aleem",
    "I remembered how my room had narrowed after O Levels. Advice had reached me as pressure because everyone wanted movement before I could imagine direction. I wanted to offer her something that did not resemble another plan.",
    "ch5-011",
  ),
  line(
    "ch5-011",
    "chapter-5",
    stages.jcMeiLinInvitation,
    "aleem-sec",
    "Would you like to go to the zoo one day? No results talk unless you start it. We can just walk around and let animals have more organised lives than us.",
    "ch5-012",
  ),
  line(
    "ch5-012",
    "chapter-5",
    stages.jcMeiLinInvitation,
    "mei-lin",
    "That is a strange sales pitch. But yes. I think getting out would be good.",
    "ch5-013",
  ),
  line(
    "ch5-013",
    "chapter-5",
    stages.jcDawn,
    "adult-aleem",
    "The invitation was goodwill, not a bargain disguised as kindness. I had feelings I had never declared, but she had agreed to a day out with a friend. Anything beyond that existed only in my private hopes.",
    "ch5-014",
  ),
  line(
    "ch5-014",
    "chapter-5",
    stages.zooArrival,
    "adult-aleem",
    "The morning was warm before we reached the entrance. Families moved around us with bags, folded maps, and children already negotiating for snacks. Mei Lin arrived carrying enough water for a minor expedition.",
    "ch5-015",
  ),
  line(
    "ch5-015",
    "chapter-5",
    stages.zooTogether,
    "aleem-sec",
    "You know they sell drinks inside, right? We are not crossing a desert.",
    "ch5-016",
  ),
  line(
    "ch5-016",
    "chapter-5",
    stages.zooTogether,
    "mei-lin",
    "And pay attraction prices? My disappointing results did not remove my common sense.",
    "ch5-017",
  ),
  line(
    "ch5-017",
    "chapter-5",
    stages.zooMeiLinAnimated,
    "adult-aleem",
    "For the first part of the day, she remained careful, smiling half a second after the moment asked for it. Then an animal ignored a perfectly placed meal, and her commentary became so indignant that the old Mei Lin emerged mid-sentence.",
    "ch5-018",
  ),
  line(
    "ch5-018",
    "chapter-5",
    stages.zooMeiLinAnimated,
    "mei-lin",
    "That is excellent food being wasted. Do you know how many hours of studying I could have survived with that snack?",
    "ch5-019",
  ),
  line(
    "ch5-019",
    "chapter-5",
    stages.zooTogether,
    "adult-aleem",
    "We moved without a timetable. She stopped for whatever caught her interest. I took photographs when asked and accepted several lectures about composition from somebody whose own thumb appeared in two pictures.",
    "ch5-020",
  ),
  line(
    "ch5-020",
    "chapter-5",
    stages.zooMeiLinAnimated,
    "adult-aleem",
    "By lunch, her shoulders looked less guarded. She spoke about small future possibilities without attaching each one to what her results had removed. That was what I had hoped the day might offer.",
    "ch5-021",
  ),
  line(
    "ch5-021",
    "chapter-5",
    stages.zooMeiLinAnimated,
    "mei-lin",
    "Thank you for asking me out today. I was going to stay home and avoid everybody, which is probably not a complete recovery strategy.",
    "ch5-022",
  ),
  line(
    "ch5-022",
    "chapter-5",
    stages.zooTogether,
    "aleem-sec",
    "Avoiding everybody works for about one day. After that, your room starts winning arguments you never agreed to have.",
    "ch5-023",
  ),
  line(
    "ch5-023",
    "chapter-5",
    stages.zooMeiLinAnimated,
    "adult-aleem",
    "Somewhere across those hours, another name kept returning: Daniel—the pseudonym I use here for a guy she knew through church. I remember the pattern more clearly than the sentences, so I will not invent exact comparisons memory did not preserve.",
    "ch5-024",
  ),
  line(
    "ch5-024",
    "chapter-5",
    stages.zooMeiLinAnimated,
    "adult-aleem",
    "A place we passed reminded her of something Daniel had mentioned. A choice I made invited a comparison with how he approached things. Later, his name entered again through another association that felt effortless to her and increasingly pointed to me.",
    "ch5-025",
  ),
  line(
    "ch5-025",
    "chapter-5",
    stages.zooAleemFrustrated,
    "adult-aleem",
    "The first mention was ordinary. The next caught my attention. By the time I perceived a pattern, irritation sat underneath every new subject, waiting to hear his name before I heard what Mei Lin was actually saying.",
    "ch5-026",
  ),
  line(
    "ch5-026",
    "chapter-5",
    stages.zooAleemFrustrated,
    "aleem-sec",
    "Why does everything I do need to be placed beside this guy? I invited her here to help, not to spend the day being measured against someone who is not even present.",
    "ch5-027",
  ),
  line(
    "ch5-027",
    "chapter-5",
    stages.zooAleemFrustrated,
    "adult-aleem",
    "That reaction contained jealousy, wounded pride, and a genuine dislike of repeated comparison. It also ignored an important fact: I had never told Mei Lin how I felt, so she could not knowingly manage feelings I had chosen to hide.",
    "ch5-choice-zoo",
  ),
  choice(
    "ch5-choice-zoo",
    "chapter-5",
    stages.zooAleemFrustrated,
    "How did Aleem carry his frustration through the rest of the day?",
    [
      {
        id: "zoo-mask",
        label: "Hide it behind jokes and keep the day light.",
        next: "ch5-zoo-mask-001",
      },
      {
        id: "zoo-signal",
        label: "Treat Daniel's name as a boundary and respect it.",
        next: "ch5-zoo-signal-001",
      },
      {
        id: "zoo-name-feeling",
        label: "Admit the jealousy privately and do not confront her today.",
        next: "ch5-zoo-name-feeling-001",
      },
    ],
  ),
  line(
    "ch5-zoo-mask-001",
    "chapter-5",
    stages.zooTogether,
    "aleem-sec",
    "Come on. We still have half the place left, and you have not criticised my photography enough to meet today's quota.",
    "ch5-zoo-mask-002",
  ),
  line(
    "ch5-zoo-mask-002",
    "chapter-5",
    stages.zooAleemFrustrated,
    "adult-aleem",
    "Humour kept my irritation from becoming her burden on an already difficult week. It also helped me perform a comfort I did not feel, leaving her no opportunity to understand why I would soon become distant.",
    "ch5-zoo-join",
  ),
  line(
    "ch5-zoo-signal-001",
    "chapter-5",
    stages.zooAleemFrustrated,
    "aleem-sec",
    "She is telling me where her interest is without having to reject a question I never asked. I should listen and finish the day as her friend.",
    "ch5-zoo-signal-002",
  ),
  line(
    "ch5-zoo-signal-002",
    "chapter-5",
    stages.zooDistance,
    "adult-aleem",
    "Interpreting the name as a boundary helped me behave respectfully. But Mei Lin never confirmed that intention. A compassionate inference was still an inference, and I would later treat it as settled fact.",
    "ch5-zoo-join",
  ),
  line(
    "ch5-zoo-name-feeling-001",
    "chapter-5",
    stages.zooAleemFrustrated,
    "aleem-sec",
    "I am jealous. That is mine to manage, especially today. I can decide what to do with it after I am no longer angry.",
    "ch5-zoo-name-feeling-002",
  ),
  line(
    "ch5-zoo-name-feeling-002",
    "chapter-5",
    stages.zooDistance,
    "adult-aleem",
    "Naming the feeling prevented it from disguising itself as certainty. Waiting was wise. The missing step came afterward, when waiting quietly became withdrawing without ever returning to the conversation.",
    "ch5-zoo-join",
  ),
  line(
    "ch5-zoo-join",
    "chapter-5",
    stages.zooTogether,
    "adult-aleem",
    "I held the frustration in. We continued along shaded paths, stopped when something interested her, and let the afternoon soften toward evening. Mei Lin did not know there was a private argument taking place beside her.",
    "ch5-028",
  ),
  line(
    "ch5-028",
    "chapter-5",
    stages.zooMeiLinAnimated,
    "mei-lin",
    "Today helped. Not in a magical everything-is-fixed way. I just remembered I can have one good day while the larger problem is still there.",
    "ch5-029",
  ),
  line(
    "ch5-029",
    "chapter-5",
    stages.zooTogether,
    "aleem-sec",
    "One good day is enough for today.",
    "ch5-030",
  ),
  line(
    "ch5-030",
    "chapter-5",
    stages.zooDistance,
    "adult-aleem",
    "When we parted, I was relieved. Partly because she seemed lighter. Partly because I no longer had to keep smiling through comparisons that had made me feel unnecessary in my own act of kindness.",
    "ch5-031",
  ),
  line(
    "ch5-031",
    "chapter-5",
    stages.zooDistance,
    "adult-aleem",
    "On the journey home, I constructed an explanation: Mei Lin had sensed that I might want more, so she had raised Daniel's name repeatedly to put her walls up. It was plausible. Plausibility made it easy to stop asking questions.",
    "ch5-032",
  ),
  line(
    "ch5-032",
    "chapter-5",
    stages.zooDistance,
    "adult-aleem",
    "Perhaps Daniel mattered romantically. Perhaps he was simply present in her recent life. Perhaps comparison was her way of making conversation, or perhaps I heard more comparison than she intended because jealousy had sharpened my attention.",
    "ch5-033",
  ),
  line(
    "ch5-033",
    "chapter-5",
    stages.zooDistance,
    "adult-aleem",
    "I cannot honestly select one of those possibilities now and call it memory. Mei Lin never told me that the day was a warning, and I never gave her the chance to confirm or correct what I believed.",
    "ch5-034",
  ),
  line(
    "ch5-034",
    "chapter-5",
    stages.jcDawn,
    "adult-aleem",
    "So I gradually pulled away. Replies took longer. Invitations stopped. The friendship did not end in an argument; it thinned through absences small enough to deny individually and obvious when placed together.",
    "ch5-035",
  ),
  line(
    "ch5-035",
    "chapter-5",
    stages.jcDawn,
    "adult-aleem",
    "At the time, leaving felt respectful. If she wanted distance, I would provide it before she needed to ask. That story protected me from another explicit rejection and allowed me to call retreat consideration.",
    "ch5-036",
  ),
  line(
    "ch5-036",
    "chapter-5",
    stages.jcDawn,
    "adult-aleem",
    "Years later, I could see the irony. I had been wounded when difficult truths reached me indirectly, yet I now expected Mei Lin to understand my withdrawal without the direct words I wished others had given me.",
    "ch5-037",
  ),
  line(
    "ch5-037",
    "chapter-5",
    stages.jcDawn,
    "adult-aleem",
    "The zoo day was not a betrayal. It was a kind gesture mixed with unspoken hope, an uncomfortable pattern of comparison, and an interpretation neither person tested. Silence filled the remaining space and hardened into an answer.",
    "ch5-038",
  ),
  line(
    "ch5-038",
    "chapter-5",
    stages.jcDawn,
    "adult-aleem",
    "By then I had academic evidence that a bad result did not define me. Emotionally, I was still building rules from incomplete endings. Those rules would follow me into the relationship that came next.",
    "ns-001",
  ),
] as const satisfies readonly StoryNode[];
