import type { StageSnapshot, StoryNode } from "../engine/types";
import { choice, line } from "./helpers";
import { umrahStages as stages } from "./umrahStages";

const beat = (id: string, stage: StageSnapshot, speaker: string, text: string, next: string) =>
  line(id, "chapter-9", stage, speaker, text, next);

export const chapterNineNodes = [
  beat("ch9-001", stages.arrival, "adult-aleem",
    "I had come for Umrah with a tired heart and very little idea of how to rest it. Now that we were here, I wanted to stop rehearsing everything that had gone wrong. I wanted to pay attention, make space for worship, and understand what I had been carrying for so long.", "ch9-002"),
  beat("ch9-002", stages.arrival, "imran",
    "Come, Aleem. We can put our things down first. You're looking at everything at once.", "ch9-003"),
  beat("ch9-003", stages.common, "adult-aleem",
    "There were other people to get to know in our tour group. Faces became names, then familiar places to look when somebody called for us. I stood beside Imran and listened, still feeling the strangeness of being so far from my usual days. Then I heard a voice I already knew.", "ch9-004"),
  beat("ch9-004", stages.reunion, "nadiah",
    "Aleem? Eh. You're in this group also?", "ch9-005"),
  beat("ch9-005", stages.reunion, "adult-aleem",
    "Nadiah. For a moment I could only look at her. The same girl from my National Service years, standing among people I had expected to meet for the first time. I had travelled here with the thought of setting my hurt down. One of the people at the centre of it had arrived too.", "ch9-006"),
  beat("ch9-006", stages.reunion, "aleem-adult",
    "Nadiah. Yeah. I'm here with my friend. I didn't know you were coming.", "ch9-007"),
  beat("ch9-007", stages.reunionWarm, "adult-aleem",
    "She wore a hijab, its edge framing the face that had stayed in my memory through years of trying not to think about it. She smiled at my surprise. I remembered that smile before I could decide what expression to offer back. My body had prepared for something painful; her greeting was simply warm.", "ch9-008"),
  beat("ch9-008", stages.reunionWarm, "nadiah",
    "I didn't know either. You look so shocked. Say hello properly first, can?", "ch9-009"),
  beat("ch9-009", stages.reunionWarm, "aleem-adult",
    "Hello properly. Sorry, my brain needs a bit of time.", "ch9-010"),
  beat("ch9-010", stages.reunionWarm, "adult-aleem",
    "She laughed, and something inside me loosened enough for me to laugh too. There were people moving around us, bags in the way, another conversation waiting to include her. We had only a few ordinary minutes. Afterwards, I kept returning to how ordinary they had felt. I hadn't needed to defend myself from her voice.", "ch9-reunion-after"),
  beat("ch9-reunion-after", stages.common, "adult-aleem",
    "I sat down with the fact of it once she had moved away. The same Nadiah. I could still picture myself in camp, trying to keep the shock from showing on my face. Yet the person who had just greeted her was older. My own voice had surprised me almost as much as hers: a little awkward, but free of the accusation I had imagined it would carry.", "ch9-011"),
  beat("ch9-011", stages.couple, "adult-aleem",
    "Among the people we began spending time with were Kak Mariam and her husband, Abang Yusuf. Mariam noticed when someone was standing awkwardly at the edge of a conversation. She made space with a small shift of her chair and a wave, as though there had always been a place intended for them.", "ch9-012"),
  beat("ch9-012", stages.couple, "mariam",
    "Aleem, sit lah. There's space here. You and your friend have eaten?", "ch9-013"),
  beat("ch9-013", stages.coupleWarm, "yusuf",
    "Careful how you answer. If you hesitate, she will decide you haven't.", "ch9-014"),
  beat("ch9-014", stages.coupleWarm, "adult-aleem",
    "Mariam gave him a look that seemed to have a whole marriage behind it. He smiled and moved something off the spare seat. I liked being near them. Their kindness asked for very little in return: an answer, a bit of conversation, the chance to make sure we were all right. I stopped feeling like a stranger so quickly.", "ch9-015"),
  beat("ch9-015", stages.makkah, "adult-aleem",
    "In Makkah, I tried to let the purpose of the trip settle around me. There was room in a day for things I usually pushed aside. Sometimes I noticed how quickly I reached for my phone whenever a quiet moment opened. I began leaving it in my pocket a little longer, allowing myself to remain where I was.", "ch9-016"),
  beat("ch9-016", stages.makkah, "adult-aleem",
    "Nadiah was there too, woven into the ordinary rhythm of the group. We greeted each other. We ended up within the same conversations. Each encounter was small, but the accumulated fear I had attached to seeing her again did not match what happened. I could look up, find her nearby, and feel pleased before I felt anything else.", "ch9-017"),
  beat("ch9-017", stages.makkahTogether, "adult-aleem",
    "It was the way she listened that I recognised most. She turned towards the person speaking and waited for the rest of the sentence. When she teased me, her eyes gave the joke away before her mouth did. I began to feel that she had returned to the person I once knew, the person I had loved.", "ch9-018"),
  beat("ch9-018", stages.makkahTogether, "adult-aleem",
    "That was how it felt to me. I couldn't measure all the years between us by the sight of her hijab or a few warm conversations. Still, seeing her this way brought back a gentleness I had almost stopped allowing myself to remember. The old hurt no longer arrived every time the memory did.", "ch9-019"),
  beat("ch9-019", stages.nurAscent, "adult-aleem",
    "When we climbed Jabal Nur, there were five of us together at the beginning. I remember the company more clearly than any precise arrangement: voices close enough to answer, people checking their footing, the small negotiations of finding a pace. Nadiah was among us. At first, speaking to her was part of speaking to everyone.", "ch9-020"),
  beat("ch9-020", stages.nurAscent, "adult-aleem",
    "The climb gave our conversation a different rhythm. A few words, then breath. A glance towards the next stretch before looking back at the person beside me. I couldn't fill every silence with something clever even if I wanted to. We kept moving, and the little group gradually stopped moving as one.", "ch9-climb-rhythm"),
  beat("ch9-climb-rhythm", stages.nurAscent, "adult-aleem",
    "I watched the ground more than her face at first. It gave me something practical to concentrate on while the surprise of having her nearby settled. Then she said something I hadn't caught. I turned, asked her to repeat it, and found myself smiling at how easily we could do that. I didn't have to pretend I had heard everything perfectly.", "ch9-021"),
  beat("ch9-021", stages.nurTogether, "adult-aleem",
    "Five became fewer. Somewhere in the ordinary changes of pace and pauses, the others were no longer beside us. When I looked around, it was just Nadiah and me. Nobody had announced that we should be together. I hadn't manoeuvred to make it happen. Yet there she was, close enough to hear me speak without raising my voice.", "ch9-022"),
  beat("ch9-022", stages.nurTogether, "nadiah",
    "How did we end up just the two of us?", "ch9-023"),
  beat("ch9-023", stages.nurTogether, "aleem-adult",
    "I was going to ask you. Started with five, right? My counting still okay?", "ch9-024"),
  beat("ch9-024", stages.nurRest, "adult-aleem",
    "She laughed and caught her breath. We paused where there was room to stand comfortably. For a little while we looked out instead of at each other. I could feel the effort in my legs and hear my own breathing settle. When she asked how I had been, the question had enough space around it for an honest answer.", "ch9-025"),
  beat("ch9-025", stages.nurRest, "nadiah",
    "So, how are you now? Work, life... everything? It's been so long.", "ch9-choice-sharing"),
  choice("ch9-choice-sharing", "chapter-9", stages.nurRest,
    "What could I share with her here?", [
      { id: "sharing-tired", label: "I've been more tired than I let on.", next: "ch9-sharing-tired" },
      { id: "sharing-ordinary", label: "Start with the ordinary parts of my life.", next: "ch9-sharing-ordinary" },
      { id: "sharing-peace", label: "Tell her why I wanted this journey.", next: "ch9-sharing-peace" },
    ]),
  beat("ch9-sharing-tired", stages.nurRest, "aleem-adult",
    "I've been tired, honestly. I can do the normal things, go to work, laugh with people. But underneath that, a lot has been sitting there. I wanted some time to breathe properly.", "ch9-sharing-join"),
  beat("ch9-sharing-ordinary", stages.nurRest, "aleem-adult",
    "Working already. Some days I think I've got the routine sorted, then I get home and realise I forgot something simple again. Life is okay in many ways. I'm still figuring out the rest.", "ch9-sharing-join"),
  beat("ch9-sharing-peace", stages.nurRest, "aleem-adult",
    "I wanted peace. That's the simplest way to say it. I had things I kept going over in my head, and I wanted to come here with them. See what I could understand, or finally let go.", "ch9-sharing-join"),
  beat("ch9-sharing-join", stages.nurRest, "adult-aleem",
    "She listened without turning the answer into something I needed to defend. Then I asked about her. We exchanged the ordinary outlines of our present lives, pausing to clarify something, smiling when the years between updates became obvious. I found myself listening for what she was saying instead of rehearsing what I would say next.", "ch9-present-lives"),
  beat("ch9-present-lives", stages.nurRest, "adult-aleem",
    "There were things each of us needed to explain from the beginning. We no longer knew all the people in the other's daily life, or what an ordinary afternoon looked like. That gap could have made me sad. Instead I liked hearing her fill a little of it. The girl I remembered was here, with years of living I hadn't been there to see.", "ch9-026"),
  beat("ch9-026", stages.nurQuiet, "aleem-adult",
    "Last time you knew me, so much of my conversation was about camp. You must have been very patient.", "ch9-027"),
  beat("ch9-027", stages.nurQuiet, "nadiah",
    "You always said civilian conversation was too fast for you. Now working already. Can keep up or not?", "ch9-028"),
  beat("ch9-028", stages.nurQuiet, "aleem-adult",
    "Depends. If there are too many questions, I still need advance notice.", "ch9-029"),
  beat("ch9-029", stages.nurMemory, "adult-aleem",
    "We remembered book-ins, the strange way a short weekend used to hold so much, how much conversation we had fitted into the edges of a day. I had kept those memories shut away with the ending for years. Now one of them came back and made me smile. She remembered it too. I hadn't imagined every good thing.", "ch9-030"),
  beat("ch9-030", stages.nurMemory, "adult-aleem",
    "There was no long account of who had hurt whom. We didn't settle the past on that mountain. We talked around familiar details and allowed some of them to be tender again. The air moved against my face while she spoke. I noticed that my shoulders had dropped, and that I was no longer choosing each word to keep myself protected.", "ch9-memory-ease"),
  beat("ch9-memory-ease", stages.nurQuiet, "adult-aleem",
    "Once, we began remembering the same thing at the same time and both stopped to let the other finish. She waved for me to continue. It was such a small gesture, but I felt a sudden affection for the ease of it. For years I had remembered our ending more often than I remembered what it was like simply to talk to her.", "ch9-031"),
  beat("ch9-031", stages.nurQuiet, "adult-aleem",
    "When a silence came, I let it stay. I had once been frightened that a conversation ending meant I was becoming less important. Beside her here, I could take a breath without immediately finding a question. After a while she said something small about the climb, and we continued from there. Nothing had been lost in the pause.", "ch9-032"),
  beat("ch9-032", stages.makkah, "adult-aleem",
    "Later, I kept thinking about that change from five people to two. Out of everyone in the group, out of all the possible ways a day could unfold, we had been given that stretch of time. I knew how ordinary the explanation might be. It still felt extraordinary to be the person walking beside her again.", "ch9-033"),
  beat("ch9-033", stages.rahmah, "adult-aleem",
    "Then it happened again at Jabal Rahmah. We were there with the group, and once more I found that the conversation nearest me belonged to Nadiah. We climbed, paused, looked around. The people who had been beside us were elsewhere. I turned towards her with a half-formed question, and saw that she had noticed too.", "ch9-034"),
  beat("ch9-034", stages.rahmah, "nadiah",
    "Again ah?", "ch9-035"),
  beat("ch9-035", stages.rahmahTogether, "aleem-adult",
    "Apparently we keep choosing the same pace.", "ch9-rahmah-pause"),
  beat("ch9-rahmah-pause", stages.rahmahTogether, "adult-aleem",
    "I looked back towards where I had last noticed the others, then turned to find her doing much the same thing. We both smiled. It felt like the start of a private joke, something that would need very little explanation if one of us mentioned it later. I caught myself wanting there to be a later in which we could mention it.", "ch9-036"),
  beat("ch9-036", stages.rahmahMemory, "adult-aleem",
    "I knew the tradition associated with Jabal Rahmah: that Adam and Hawa, Adam and Eve, had met again here after coming down to earth. It was a story I carried about the place. Standing there beside someone I had loved and lost, I felt its meaning come suddenly close to my own life.", "ch9-037"),
  beat("ch9-037", stages.rahmahMemory, "adult-aleem",
    "Once could be chance. Twice, my hopeful heart whispered, surely meant something. I looked at the space around us, then at her, and wondered whether this was a sign. The thought came with such warmth that I wanted to stay inside it. I had arrived believing love might be finished for me. Now I was wondering about another beginning.", "ch9-choice-sign"),
  choice("ch9-choice-sign", "chapter-9", stages.rahmahTogether,
    "What did I hope this coincidence might hold?", [
      { id: "sign-reunion", label: "Perhaps we could begin again.", next: "ch9-sign-reunion" },
      { id: "sign-forgiveness", label: "Perhaps I could remember her without hurting.", next: "ch9-sign-forgiveness" },
      { id: "sign-open", label: "Perhaps something good was still possible.", next: "ch9-sign-open" },
    ]),
  beat("ch9-sign-reunion", stages.rahmahTogether, "adult-aleem",
    "I allowed myself to picture another beginning with her. We were older now. We could speak differently, understand more. The possibility felt lovely before any difficult questions reached it, and for that moment I let myself want it.", "ch9-sign-join"),
  beat("ch9-sign-forgiveness", stages.rahmahTogether, "adult-aleem",
    "Perhaps this was what I needed: her face without the old shock arriving behind it. I wanted to keep the ease of this conversation when we left the mountain, to remember her and still feel able to breathe.", "ch9-sign-join"),
  beat("ch9-sign-open", stages.rahmahTogether, "adult-aleem",
    "I had been so tired of hoping that I scarcely recognised how good it felt. Perhaps my life still held room for something I hadn't planned. I wanted to remain open to that feeling a little longer.", "ch9-sign-join"),
  beat("ch9-sign-join", stages.rahmahTogether, "adult-aleem",
    "I kept the thought to myself. Nadiah had made no promise by standing beside me. Around us, other people were having their own conversations, taking their own pauses. I turned back to ours. Whatever the coincidence meant, I wanted to hear the person who was actually here, rather than disappear entirely into the future I could imagine.", "ch9-038"),
  beat("ch9-038", stages.rahmahTogether, "nadiah",
    "You're very quiet suddenly. Tired?", "ch9-039"),
  beat("ch9-039", stages.rahmahTogether, "aleem-adult",
    "A bit. Also just taking it in. I'm glad we got to talk like this.", "ch9-040"),
  beat("ch9-040", stages.rahmahTogether, "adult-aleem",
    "She smiled, and we let the conversation find its own pace again. I felt peaceful in her company. That was the part I had never thought to hope for: sitting with the very person I associated with being broken, and finding that I could be at ease. I didn't have to erase her from my life to survive remembering her.", "ch9-rahmah-after"),
  beat("ch9-rahmah-after", stages.makkah, "adult-aleem",
    "Afterwards, those minutes returned while I was doing other things. I would remember a phrase, the look she gave me, the way neither of us had hurried to fill the quiet. I could feel myself making room for her again. This time, at least, I recognised the movement in my own heart. I knew how much I wanted our closeness to mean something.", "ch9-041"),
  beat("ch9-041", stages.hesitation, "adult-aleem",
    "As we spoke more during the trip, I began noticing smaller things too. Sometimes an answer would arrive after a hesitation, her expression changing before she found the words. Sometimes a conversation that had been easy would become quieter for a moment. She remained kind. Still, I could feel myself reaching towards something that didn't quite meet me.", "ch9-042"),
  beat("ch9-042", stages.longing, "adult-aleem",
    "I thought I saw longing in those pauses, an attention held somewhere beyond the conversation we were having. The more we interacted, the harder it was to ignore. I could not name what she was thinking about. I only knew the feeling it stirred in me: there might be someone else her heart was still turned towards.", "ch9-043"),
  beat("ch9-043", stages.longing, "adult-aleem",
    "That was my reading of her, unfinished and uncertain. She hadn't offered me a story about another man, and I had no hidden piece of information to examine. I had her warmth, her hesitation, and my own memories. For once I tried to leave those things separate while I worked out what they meant for me.", "ch9-uncertain-warmth"),
  beat("ch9-uncertain-warmth", stages.longing, "adult-aleem",
    "Sometimes she would come back from one of those quiet moments and ask me to continue what I had been saying. I would, grateful that she wanted to hear it, aware of how quickly gratitude could become hope. I didn't want to punish her for a thought she hadn't shared. I also didn't want to ignore the small uncertainty I felt beside the warmth.", "ch9-044"),
  beat("ch9-044", stages.makkah, "adult-aleem",
    "The hope did not disappear simply because I noticed the uncertainty. I could still remember our conversation on Jabal Nur and feel grateful for every minute. I could still think of Jabal Rahmah and wonder. But beneath that wondering, another question had begun to make itself heard: could I keep this peace even if we never became us again?", "ch10-001"),
] as const satisfies readonly StoryNode[];
