import type { StoryNode } from "../engine/types";
import { choice, line } from "./helpers";
import { stages } from "./stages";

export const chapterFourNodes = [
  line(
    "ch4-001",
    "chapter-4",
    stages.confessionMontage,
    "adult-aleem",
    "After Syafiqa, I did not become cautious in the way I imagined. I became restless. Rejection had left a question about my worth, and instead of sitting with it, I began asking new people to answer it for me.",
    "ch4-002",
  ),
  line(
    "ch4-002",
    "chapter-4",
    stages.confessionMontage,
    "adult-aleem",
    "A crush could form from a few friendly conversations. A moment of attention became possibility. Once possibility appeared, I wanted a verdict quickly, as though enough courage repeated often enough would eventually produce the answer I preferred.",
    "ch4-003",
  ),
  line(
    "ch4-003",
    "chapter-4",
    stages.jcAleemHurt,
    "aleem-sec",
    "Maybe I have been waiting too long every time. Maybe the confident guys simply ask, accept the answer, and move on.",
    "ch4-004",
  ),
  line(
    "ch4-004",
    "chapter-4",
    stages.confessionMontage,
    "adult-aleem",
    "That explanation contained one useful idea: a clear, respectful question can be healthier than months of private assumptions. It also concealed my desperation to make the next yes cancel every earlier no.",
    "ch4-choice-search",
  ),
  choice(
    "ch4-choice-search",
    "chapter-4",
    stages.confessionMontage,
    "What was Aleem really searching for?",
    [
      {
        id: "search-love",
        label: "Someone who might genuinely choose me.",
        next: "ch4-search-love-001",
      },
      {
        id: "search-proof",
        label: "Proof that the earlier rejections were not about my worth.",
        next: "ch4-search-proof-001",
      },
      {
        id: "search-control",
        label: "A quick answer, so uncertainty cannot surprise me again.",
        next: "ch4-search-control-001",
      },
    ],
  ),
  line(
    "ch4-search-love-001",
    "chapter-4",
    stages.confessionMontage,
    "aleem-sec",
    "I am not trying to replace anyone. I just want to meet someone who sees me clearly and still wants to stay.",
    "ch4-search-love-002",
  ),
  line(
    "ch4-search-love-002",
    "chapter-4",
    stages.jcDawn,
    "adult-aleem",
    "The longing was sincere. The problem was the speed at which I assigned that hope to people I barely knew. Wanting love did not make every new attraction capable of carrying it.",
    "ch4-search-join",
  ),
  line(
    "ch4-search-proof-001",
    "chapter-4",
    stages.confessionMontage,
    "aleem-sec",
    "One person saying yes would prove I am not the problem everyone eventually discovers. I need to know I can be chosen.",
    "ch4-search-proof-002",
  ),
  line(
    "ch4-search-proof-002",
    "chapter-4",
    stages.jcDawn,
    "adult-aleem",
    "No person could safely provide that proof. A yes would have soothed me for a while, then become something I feared losing. Self-worth borrowed from another person's answer always arrives with a repayment date.",
    "ch4-search-join",
  ),
  line(
    "ch4-search-control-001",
    "chapter-4",
    stages.confessionMontage,
    "aleem-sec",
    "If I ask early, there is no hidden story to discover later. Yes or no, at least I control when the truth arrives.",
    "ch4-search-control-002",
  ),
  line(
    "ch4-search-control-002",
    "chapter-4",
    stages.jcDawn,
    "adult-aleem",
    "Early questions reduced uncertainty but did not create control. Other people still had private histories, changing feelings, and the right to choose what they shared. Clarity was a conversation, not an interrogation timed for my comfort.",
    "ch4-search-join",
  ),
  line(
    "ch4-search-join",
    "chapter-4",
    stages.confessionMontage,
    "adult-aleem",
    "There were three confessions in that restless stretch: to an Indian girl, a Chinese girl, and another Malay girl. I identify them that way because teenage me was already sorting experience into categories, searching for a pattern large enough to explain me.",
    "ch4-005",
  ),
  line(
    "ch4-005",
    "chapter-4",
    stages.confessionMontage,
    "adult-aleem",
    "They were not a sequence of conquests or failed auditions. Each was a person with a life outside my question. Their names and private reasons are not needed here; none chose a relationship with me, and their answers were enough.",
    "ch4-006",
  ),
  line(
    "ch4-006",
    "chapter-4",
    stages.confessionMontage,
    "adult-aleem",
    "I did not argue or continue pursuing them. I accepted the boundary in front of me. Respecting a no was important, even while the frequency of my asking revealed that I was not truly ready for a yes.",
    "ch4-007",
  ),
  line(
    "ch4-007",
    "chapter-4",
    stages.jcAleemHurt,
    "adult-aleem",
    "After each attempt, I performed recovery: never mind, all good, no worries. Then I carried the rejection home and stacked it beside the others until individual disappointments became a theory about myself.",
    "ch4-008",
  ),
  line(
    "ch4-008",
    "chapter-4",
    stages.jcDawn,
    "adult-aleem",
    "Desperation is not always loud. Mine looked organised. Ask clearly. Receive answer. Withdraw politely. Try again elsewhere. The motion kept me from noticing I was treating connection like a locked door that enough keys might open.",
    "ch4-009",
  ),
  line(
    "ch4-009",
    "chapter-4",
    stages.jcClassroom,
    "adult-aleem",
    "By J2, the pace of school left less room for that cycle. The calendar filled with timed practices, consultations, and teachers reminding us how quickly A Levels would stop being a distant phrase.",
    "ch4-010",
  ),
  line(
    "ch4-010",
    "chapter-4",
    stages.jcClassroom,
    "adult-aleem",
    "I had spent a year beside classmates without knowing them deeply. Pressure changed that. People who once exchanged jokes began exchanging notes, food, and the small encouragements that help somebody survive a bad test.",
    "ch4-011",
  ),
  line(
    "ch4-011",
    "chapter-4",
    stages.jcMeiLin,
    "adult-aleem",
    "Mei Lin had been in my class from the beginning. She was Chinese, wore glasses, and was so much shorter than me that our conversations looked as though one of us had chosen the wrong camera angle.",
    "ch4-012",
  ),
  line(
    "ch4-012",
    "chapter-4",
    stages.jcMeiLinAmused,
    "mei-lin",
    "Could you stop standing directly in front of the board? Some of us are educationally disadvantaged by your height.",
    "ch4-013",
  ),
  line(
    "ch4-013",
    "chapter-4",
    stages.jcMeiLinAmused,
    "aleem-sec",
    "I am contributing shade and perspective. Both are valuable classroom services.",
    "ch4-014",
  ),
  line(
    "ch4-014",
    "chapter-4",
    stages.jcMeiLinAmused,
    "mei-lin",
    "Your perspective is blocking the entire question.",
    "ch4-015",
  ),
  line(
    "ch4-015",
    "chapter-4",
    stages.jcMeiLin,
    "adult-aleem",
    "At first, her height and cuteness caught my attention. What kept it was her steadiness. Mei Lin was diligent without advertising it and funny in a quiet way that sometimes reached me several seconds late.",
    "ch4-016",
  ),
  line(
    "ch4-016",
    "chapter-4",
    stages.jcStudyTogether,
    "adult-aleem",
    "We began studying at the same table after lessons. She organised papers into neat sections. I brought explanations from whichever topic had finally made sense to me and snacks selected with no academic discipline at all.",
    "ch4-017",
  ),
  line(
    "ch4-017",
    "chapter-4",
    stages.jcStudyTogether,
    "mei-lin",
    "You solved the difficult part correctly, then lost a mark because your final line looks like it escaped during an emergency.",
    "ch4-018",
  ),
  line(
    "ch4-018",
    "chapter-4",
    stages.jcStudyTogether,
    "aleem-sec",
    "The examiner should reward creativity under pressure.",
    "ch4-019",
  ),
  line(
    "ch4-019",
    "chapter-4",
    stages.jcStudyTogether,
    "mei-lin",
    "The examiner would reward legible working. Start there.",
    "ch4-020",
  ),
  line(
    "ch4-020",
    "chapter-4",
    stages.jcStudySupportive,
    "adult-aleem",
    "She noticed when frustration made me rush. I noticed when one poor practice paper made her unusually quiet. Support moved in both directions, practical and unannounced.",
    "ch4-021",
  ),
  line(
    "ch4-021",
    "chapter-4",
    stages.jcStudySupportive,
    "aleem-sec",
    "One paper does not cancel all the work you have done. You told me that last week, so unfortunately it applies to you too.",
    "ch4-022",
  ),
  line(
    "ch4-022",
    "chapter-4",
    stages.jcStudySupportive,
    "mei-lin",
    "I regret giving you reusable advice.",
    "ch4-023",
  ),
  line(
    "ch4-023",
    "chapter-4",
    stages.jcStudyTogether,
    "adult-aleem",
    "For the first time since the server years, discipline began to feel like something I could build rather than something other people possessed. A completed topic led to the next. Questions became less threatening when I returned to them daily.",
    "ch4-024",
  ),
  line(
    "ch4-024",
    "chapter-4",
    stages.jcDawn,
    "adult-aleem",
    "Family expectations did not disappear. School prestige did not stop mattering to people. What changed was the evidence I could offer myself: I was no longer waiting for shame to become motivation. I was practising different choices.",
    "ch4-025",
  ),
  line(
    "ch4-025",
    "chapter-4",
    stages.jcMeiLin,
    "adult-aleem",
    "My feelings for Mei Lin grew inside that ordinary partnership. They were less frantic than the confession spree and therefore, in some ways, more frightening. I knew her well enough for losing the friendship to mean something real.",
    "ch4-026",
  ),
  line(
    "ch4-026",
    "chapter-4",
    stages.jcStudyTogether,
    "adult-aleem",
    "I also knew there was a barrier neither cuteness nor good study sessions could responsibly ignore. I was Muslim. Mei Lin was Christian. Faith was not a decorative difference that affection could politely place to one side.",
    "ch4-027",
  ),
  line(
    "ch4-027",
    "chapter-4",
    stages.jcStudyTogether,
    "adult-aleem",
    "It touched family, marriage, community, and the shape each of us imagined for an adult life. We never negotiated those questions because I never confessed. I could not see a future I was prepared to ask her to enter.",
    "ch4-028",
  ),
  line(
    "ch4-028",
    "chapter-4",
    stages.jcMeiLin,
    "aleem-sec",
    "She has been good to me. That does not mean I should hand her a problem just because keeping it private is difficult.",
    "ch4-029",
  ),
  line(
    "ch4-029",
    "chapter-4",
    stages.jcDawn,
    "adult-aleem",
    "There was care in that restraint and fear inside it too. I stayed beside her without asking for more, telling myself the friendship was enough and trying not to inspect the word enough too closely.",
    "ch4-030",
  ),
  line(
    "ch4-030",
    "chapter-4",
    stages.jcStudyTogether,
    "adult-aleem",
    "The weeks tightened around us. We reviewed until closing time, compared mistakes, and learned when to abandon one impossible question before it consumed an entire evening.",
    "ch4-031",
  ),
  line(
    "ch4-031",
    "chapter-4",
    stages.jcStudyTogether,
    "mei-lin",
    "After exams, I am going to sleep for a week. If anyone asks, I have left the country.",
    "ch4-032",
  ),
  line(
    "ch4-032",
    "chapter-4",
    stages.jcStudyTogether,
    "aleem-sec",
    "You need a more convincing plan. I will tell them you joined a travelling mathematics society.",
    "ch4-033",
  ),
  line(
    "ch4-033",
    "chapter-4",
    stages.aLevelExam,
    "adult-aleem",
    "Then A Levels arrived. The exam hall resembled the one I remembered from 2013, but I did not. I was still afraid. This time, fear sat beside months of completed work instead of an empty space where preparation should have been.",
    "ch4-034",
  ),
  line(
    "ch4-034",
    "chapter-4",
    stages.aLevelExamTired,
    "adult-aleem",
    "No paper felt perfect. Some questions opened cleanly; others resisted until time forced me onward. I wrote the final line, placed my pen down, and understood that uncertainty after effort feels different from uncertainty after avoidance.",
    "ch4-035",
  ),
  line(
    "ch4-035",
    "chapter-4",
    stages.jcDawn,
    "adult-aleem",
    "The long wait for results began. Without tutorials to organise our days, classmates scattered into temporary jobs, obligations, and plans they discussed with varying confidence. Mei Lin and I messaged less often but did not disappear entirely.",
    "ch4-036",
  ),
  line(
    "ch4-036",
    "chapter-4",
    stages.jcDawn,
    "adult-aleem",
    "I did not know whether the outcome would redeem anything. I only knew I had kept going after O Levels, entered the school I once dismissed, and allowed it to become a place where I learned how to work again.",
    "ch5-001",
  ),
] as const satisfies readonly StoryNode[];
