import type { StoryNode } from "../engine/types";
import { ending, line } from "./helpers";
import { stages } from "./stages";

export const epilogueNodes = [
  line(
    "epilogue-001",
    "epilogue",
    stages.jcDawn,
    "adult-aleem",
    "Looking backward makes a life appear designed: one failure teaches discipline, one rejection teaches caution, one friendship prepares the heart for whatever comes next. Real time was never that tidy.",
    "epilogue-002",
  ),
  line(
    "epilogue-002",
    "epilogue",
    stages.jcDawn,
    "adult-aleem",
    "My A-Level result changed what I believed was academically possible. It proved the O-Level setback was not a final verdict. It did not erase those earlier consequences, settle every family expectation, or quietly repair the way I handled uncertainty.",
    "epilogue-003",
  ),
  line(
    "epilogue-003",
    "epilogue",
    stages.prologue,
    "adult-aleem",
    "Syafiqa and Mei Lin were not lessons placed in my path for my improvement. They were complete people making decisions inside lives I could only partly see. Remembering my hurt does not grant me ownership of their private reasons.",
    "epilogue-004",
  ),
  line(
    "epilogue-004",
    "epilogue",
    stages.prologue,
    "adult-aleem",
    "Syafiqa gave me a real no. Her explanation may have softened another truth, or it may have been true alongside her feelings for somebody else. Wanting directness was fair. Deciding that her privacy proved something about Malay girls was not.",
    "epilogue-005",
  ),
  line(
    "epilogue-005",
    "epilogue",
    stages.prologue,
    "adult-aleem",
    "Mei Lin gave me friendship, study hours, humour, and one honest yes to a day at the zoo. She spoke often about Daniel. Everything beyond those facts—her intention, her walls, what she suspected about me—was interpretation.",
    "epilogue-006",
  ),
  line(
    "epilogue-006",
    "epilogue",
    stages.jcDawn,
    "adult-aleem",
    "Dishonesty, privacy, softened rejection, and a signal perceived by someone who is already afraid can feel identical from inside the wound. They are not identical. Learning the difference requires questions, boundaries, and the humility to leave some uncertainty unresolved.",
    "epilogue-007",
  ),
  line(
    "epilogue-007",
    "epilogue",
    stages.jcDawn,
    "adult-aleem",
    "I wanted others to tell me difficult truths plainly. Yet when I feared the answer, I also withdrew, guessed, and allowed silence to speak on my behalf. The standard I longed for was one I had not yet learned to meet consistently.",
    "epilogue-008",
  ),
  line(
    "epilogue-008",
    "epilogue",
    stages.dawn,
    "adult-aleem",
    "By 2016, I was moving forward: academically recovered, more capable of discipline, and still carrying fault lines beneath the visible progress. Each untested assumption made suspicion feel a little more like wisdom.",
    "epilogue-009",
  ),
  line(
    "epilogue-009",
    "epilogue",
    stages.dawn,
    "adult-aleem",
    "The next relationship would press directly against those fault lines. My defensiveness would shape what I noticed, what I feared, and how I responded. What happened there would leave wounds I carried for years.",
    "epilogue-010",
  ),
  line(
    "epilogue-010",
    "epilogue",
    stages.prologue,
    "adult-aleem",
    "That girl remains outside this chapter: unnamed, unseen, and not judged in advance by the ending I now know. A painful outcome does not make one person the villain before her story has even begun.",
    "epilogue-011",
  ),
  line(
    "epilogue-011",
    "epilogue",
    stages.prologue,
    "adult-aleem",
    "I still had not met Nurul. She was not waiting at the end of these years as a cure, a prize, or proof that every earlier hurt had been necessary. No person should be assigned the work of redeeming somebody else's past.",
    "epilogue-012",
  ),
  line(
    "epilogue-012",
    "epilogue",
    stages.jcDawn,
    "adult-aleem",
    "Before Nurul, there would be another chapter—one about trust tested badly, choices with long shadows, and the difference between surviving an experience and understanding it.",
    "epilogue-013",
  ),
  line(
    "epilogue-013",
    "epilogue",
    stages.dawn,
    "adult-aleem",
    "For now, dawn reaches another window. Aleem has learned that a route can be rebuilt. He has not yet learned how easily an old fear can redraw the map.",
    "epilogue-end",
  ),
  ending(
    "epilogue-end",
    "epilogue",
    stages.dawn,
    "Continue?",
    "Aleem has not met Nurul yet. His story continues.",
  ),
] as const satisfies readonly StoryNode[];
