import type { StoryNode } from "../engine/types";
import { ending, line } from "./helpers";
import { stages } from "./stages";

export const epilogueNodes = [
  line(
    "epilogue-001",
    "epilogue",
    stages.dawn,
    "adult-aleem",
    "Looking backward makes a life appear designed. This heartbreak taught that lesson; that failure prepared this strength. Real time never felt so tidy.",
    "epilogue-002",
  ),
  line(
    "epilogue-002",
    "epilogue",
    stages.dawn,
    "adult-aleem",
    "Alya and Hana were not practice rounds placed in my story for my benefit. They were young people living stories of their own. We cared, we changed, and we sometimes failed one another.",
    "epilogue-003",
  ),
  line(
    "epilogue-003",
    "epilogue",
    stages.prologue,
    "adult-aleem",
    "From Alya, I learned that an ending delayed does not become kinder. From Hana, I learned the other side: promises without presence can make someone feel alone while the relationship still has a name.",
    "epilogue-004",
  ),
  line(
    "epilogue-004",
    "epilogue",
    stages.prologue,
    "adult-aleem",
    "The server was not a monster that stole my future. It was evidence of initiative, imagination, and discipline applied unevenly. The mistake was not loving what I built; it was believing one success could excuse every neglected responsibility.",
    "epilogue-005",
  ),
  line(
    "epilogue-005",
    "epilogue",
    stages.darkBedroom,
    "adult-aleem",
    "For a time, my O-Level results felt like the last page. I treated the route I had expected as the only route that counted, so every alternative looked like empty space.",
    "epilogue-006",
  ),
  line(
    "epilogue-006",
    "epilogue",
    stages.dawn,
    "adult-aleem",
    "It was not the last page. It was a hard turn—one I had helped create, one that carried real consequences, and one that still led somewhere.",
    "epilogue-007",
  ),
  line(
    "epilogue-007",
    "epilogue",
    stages.dawn,
    "adult-aleem",
    "Growing up did not mean finding a version of myself who never made mistakes. It meant learning to name them without making them my entire name.",
    "epilogue-008",
  ),
  line(
    "epilogue-008",
    "epilogue",
    stages.dawn,
    "adult-aleem",
    "It meant understanding that affection needs time made visible. That difficult truths deserve direct words. That talent can open a door, while balance determines whether you can walk through it.",
    "epilogue-009",
  ),
  line(
    "epilogue-009",
    "epilogue",
    stages.dawn,
    "adult-aleem",
    "I wish I could say I understood all of that in 2013. I did not. The boy by the window only knew that the expected future had disappeared.",
    "epilogue-010",
  ),
  line(
    "epilogue-010",
    "epilogue",
    stages.prologue,
    "adult-aleem",
    "He had not met Nurul. He did not know her laugh, the shape of her kindness, or the ordinary circumstances that would one day place them in the same chapter.",
    "epilogue-011",
  ),
  line(
    "epilogue-011",
    "epilogue",
    stages.prologue,
    "adult-aleem",
    "Nurul would not arrive as a cure for his shame, nor as a reward for suffering. No person should carry the job of rescuing somebody else's unfinished life.",
    "epilogue-012",
  ),
  line(
    "epilogue-012",
    "epilogue",
    stages.prologue,
    "adult-aleem",
    "Before they met, Aleem would need to keep moving: to rebuild, to accept help, to discover what he could offer and what he still needed to learn.",
    "epilogue-013",
  ),
  line(
    "epilogue-013",
    "epilogue",
    stages.dawn,
    "adult-aleem",
    "That part of the journey belongs to another chapter. For now, morning waits beyond the glass, and the road continues outside the frame.",
    "epilogue-end",
  ),
  ending(
    "epilogue-end",
    "epilogue",
    stages.dawn,
    "Continue?",
    "Aleem has not met Nurul yet. His story continues.",
  ),
] as const satisfies readonly StoryNode[];

