import type { StoryNode } from "../engine/types";
import { choice, ending, line } from "./helpers";
import { stages } from "./stages";

export const epilogueNodes = [
  line(
    "epilogue-001",
    "epilogue",
    stages.universityArrival,
    "adult-aleem",
    "University began in 2018 with orientation names I was still learning and routes I pretended to understand. The campus promised reinvention, as though a new timetable could separate me from everything that had happened before it.",
    "epilogue-002",
  ),
  line(
    "epilogue-002",
    "epilogue",
    stages.universityArrival,
    "adult-aleem",
    "Hakim—a pseudonym for a friend I made during orientation—had the easy confidence of somebody who could enter an unfamiliar room and assume he was welcome. During the first club recruitment week, he asked me to visit the Muslim Society.",
    "epilogue-003",
  ),
  line(
    "epilogue-003",
    "epilogue",
    stages.universityArrival,
    "hakim",
    "Come and look around. You don't have to join today. There are seniors, activities, and probably food if we arrive before everybody discovers it.",
    "epilogue-004",
  ),
  line(
    "epilogue-004",
    "epilogue",
    stages.universityArrival,
    "aleem-young-adult",
    "I don't know. Muslim Society sounds like a room where someone will make me volunteer for three committees before I find the exit.",
    "epilogue-005",
  ),
  line(
    "epilogue-005",
    "epilogue",
    stages.msocEntrance,
    "adult-aleem",
    "I sighed, then followed because I did not want to disappoint a new friend over one brief visit. A lecture theatre had been reserved for the club. Voices and ordinary laughter reached us through the open door.",
    "epilogue-006",
  ),
  line(
    "epilogue-006",
    "epilogue",
    stages.msocEntrance,
    "hakim",
    "See? No ambush. We walk in, say hello, and leave whenever you want.",
    "epilogue-007",
  ),
  line(
    "epilogue-007",
    "epilogue",
    stages.msocNeutral,
    "adult-aleem",
    "Inside, volunteers arranged sign-up sheets and shifted chairs. Freshmen stood in uncertain clusters. Several Malay women, some wearing hijab and some not, talked with friends or waited for the programme to begin.",
    "epilogue-008",
  ),
  line(
    "epilogue-008",
    "epilogue",
    stages.msocNeutral,
    "adult-aleem",
    "Nothing in the room was directed at me. Nobody had accused, cornered, or even approached me. Still, as I crossed the threshold, my body stopped with such force that Hakim took another step before noticing I was behind him.",
    "epilogue-009",
  ),
  line(
    "epilogue-009",
    "epilogue",
    stages.msocThreatScan,
    "adult-aleem",
    "My eyes moved rapidly from face to face. In my perception, red markers seemed to appear above the women, converting strangers into warnings before any of them had spoken.",
    "epilogue-010",
  ),
  line(
    "epilogue-010",
    "epilogue",
    stages.msocThreatScan,
    "aleem-young-adult",
    "She will turn out the same. That one looks suspicious. Don't be fooled because she seems kind. You know how this ends.",
    "epilogue-011",
  ),
  line(
    "epilogue-011",
    "epilogue",
    stages.msocThreatScan,
    "adult-aleem",
    "Those thoughts were the old prejudice moving at the speed of alarm. They revealed what heartbreak had trained me to expect; they revealed nothing about the women whose faces I was judging.",
    "epilogue-choice-threat-scan",
  ),
  choice(
    "epilogue-choice-threat-scan",
    "epilogue",
    stages.msocThreatScan,
    "How did Aleem try to interrupt the threat scan?",
    [
      {
        id: "threat-scan-details",
        label: "Count physical details in the room.",
        next: "epilogue-threat-scan-details-001",
      },
      {
        id: "threat-scan-exit",
        label: "Force his gaze toward the exit.",
        next: "epilogue-threat-scan-exit-001",
      },
      {
        id: "threat-scan-air",
        label: "Tell Hakim he needs some air.",
        next: "epilogue-threat-scan-air-001",
      },
    ],
  ),
  line(
    "epilogue-threat-scan-details-001",
    "epilogue",
    stages.msocNeutral,
    "aleem-young-adult",
    "Blue chairs. Two doors. Three ceiling lights in this row. One table near the aisle. Keep counting what is actually here.",
    "epilogue-threat-scan-details-002",
  ),
  line(
    "epilogue-threat-scan-details-002",
    "epilogue",
    stages.msocNeutral,
    "adult-aleem",
    "Concrete details briefly competed with the imagined markers. They did not make me comfortable, but they gave my attention a path that did not pass through somebody else's identity.",
    "epilogue-threat-scan-join",
  ),
  line(
    "epilogue-threat-scan-exit-001",
    "epilogue",
    stages.msocThreatScan,
    "aleem-young-adult",
    "Look at the door. Not at them. Find the corridor, move your feet, and deal with everything else outside.",
    "epilogue-threat-scan-exit-002",
  ),
  line(
    "epilogue-threat-scan-exit-002",
    "epilogue",
    stages.msocEntrance,
    "adult-aleem",
    "The exit became a fixed point in a room my attention had made unstable. Looking away interrupted the judgements, though it also made immediate escape feel like the only available answer.",
    "epilogue-threat-scan-join",
  ),
  line(
    "epilogue-threat-scan-air-001",
    "epilogue",
    stages.msocNeutral,
    "aleem-young-adult",
    "Hakim, sorry. I need some air. I thought I could stay, but I need to step outside now.",
    "epilogue-threat-scan-air-002",
  ),
  line(
    "epilogue-threat-scan-air-002",
    "epilogue",
    stages.msocNeutral,
    "hakim",
    "Okay. No problem. I'll come with you, or I can give you space—just tell me what you need.",
    "epilogue-threat-scan-join",
  ),
  line(
    "epilogue-threat-scan-join",
    "epilogue",
    stages.msocEntrance,
    "adult-aleem",
    "With effort, I broke my gaze from the crowd. I told Hakim I had something else to do and moved toward the door, concentrating on each step until the lecture theatre released me.",
    "epilogue-012",
  ),
  line(
    "epilogue-012",
    "epilogue",
    stages.universityCorridorBreathless,
    "adult-aleem",
    "In the corridor, I breathed hard. Sweat gathered across my face and beneath my shirt. I leaned away from the doorway, confused by the distance between the ordinary room I had entered and the danger my body had announced.",
    "epilogue-013",
  ),
  line(
    "epilogue-013",
    "epilogue",
    stages.universityCorridorBreathless,
    "aleem-young-adult",
    "Slow down. You are outside. Nobody followed you. Just breathe until your hands stop feeling like this.",
    "epilogue-014",
  ),
  line(
    "epilogue-014",
    "epilogue",
    stages.universityCorridorReflection,
    "adult-aleem",
    "The physical response was real: the heat, the frozen attention, the urgent need to leave. I will not invent a diagnosis for my younger self from a remembered scene.",
    "epilogue-015",
  ),
  line(
    "epilogue-015",
    "epilogue",
    stages.universityCorridorReflection,
    "adult-aleem",
    "What I can say is that none of those women had harmed me. Nadiah's choices were not theirs. A room of Malay and hijabi women was not evidence that betrayal had gathered in one place.",
    "epilogue-016",
  ),
  line(
    "epilogue-016",
    "epilogue",
    stages.universityCorridorReflection,
    "adult-aleem",
    "My alarm deserved attention because I was suffering. Its verdict did not deserve obedience because it accused strangers. Learning to hold both truths would become part of the wild ride ahead.",
    "epilogue-017",
  ),
  line(
    "epilogue-017",
    "epilogue",
    stages.universityCorridorBreathless,
    "aleem-young-adult",
    "What was that?",
    "epilogue-end",
  ),
  ending(
    "epilogue-end",
    "epilogue",
    stages.universityCorridorReflection,
    "The Doorway",
    "University had barely begun.",
  ),
] as const satisfies readonly StoryNode[];
