// Generated by scripts/mobile-art.py from the individually reviewed inventory.
// Desktop image URLs and bytes remain unchanged. All coordinates are normalized.
import type { AssetFocalPoint, AssetProtectedBounds, MobileAssetVariant } from "../engine/types";
import { appPathname } from "../pwa/basePath";

export interface MobileArtOverride {
  readonly mobile?: MobileAssetVariant;
  readonly protectedBounds?: AssetProtectedBounds;
  readonly focalPoint?: AssetFocalPoint;
}

interface ReviewedScene {
  readonly originalBounds: AssetProtectedBounds;
  readonly mobilePath: string;
  readonly width: number;
  readonly height: number;
  readonly focus: AssetFocalPoint;
  readonly bounds: AssetProtectedBounds;
}

const reviewedScenes: Readonly<Record<string, ReviewedScene>> = {
  "bg-uni-orientation": {
    "originalBounds": {
      "x": 0.34,
      "y": 0.3,
      "width": 0.34,
      "height": 0.4
    },
    "mobilePath": "assets/art/backgrounds/bg-uni-orientation.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.51,
      "y": 0.5
    },
    "bounds": {
      "x": 0.34,
      "y": 0.3,
      "width": 0.34,
      "height": 0.4
    }
  },
  "bg-uni-study": {
    "originalBounds": {
      "x": 0.3,
      "y": 0.3,
      "width": 0.4,
      "height": 0.44
    },
    "mobilePath": "assets/art/backgrounds/bg-uni-study.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.5,
      "y": 0.52
    },
    "bounds": {
      "x": 0.3,
      "y": 0.3,
      "width": 0.4,
      "height": 0.44
    }
  },
  "bg-uni-dorm": {
    "originalBounds": {
      "x": 0.47,
      "y": 0.18,
      "width": 0.36,
      "height": 0.52
    },
    "mobilePath": "assets/art/backgrounds/bg-uni-dorm.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.65,
      "y": 0.44
    },
    "bounds": {
      "x": 0.47,
      "y": 0.18,
      "width": 0.36,
      "height": 0.52
    }
  },
  "bg-uni-dropoff": {
    "originalBounds": {
      "x": 0.42,
      "y": 0.27,
      "width": 0.35,
      "height": 0.39
    },
    "mobilePath": "assets/art/backgrounds/bg-uni-dropoff.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.595,
      "y": 0.465
    },
    "bounds": {
      "x": 0.42,
      "y": 0.27,
      "width": 0.35,
      "height": 0.39
    }
  },
  "bg-uss-evening": {
    "originalBounds": {
      "x": 0.34,
      "y": 0.23,
      "width": 0.35,
      "height": 0.42
    },
    "mobilePath": "assets/art/backgrounds/bg-uss-evening.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.515,
      "y": 0.44
    },
    "bounds": {
      "x": 0.34,
      "y": 0.23,
      "width": 0.35,
      "height": 0.42
    }
  },
  "bg-office-pantry": {
    "originalBounds": {
      "x": 0.43,
      "y": 0.27,
      "width": 0.37,
      "height": 0.48
    },
    "mobilePath": "assets/art/backgrounds/bg-office-pantry.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.615,
      "y": 0.51
    },
    "bounds": {
      "x": 0.43,
      "y": 0.27,
      "width": 0.37,
      "height": 0.48
    }
  },
  "bg-city-cafe": {
    "originalBounds": {
      "x": 0.35,
      "y": 0.31,
      "width": 0.36,
      "height": 0.43
    },
    "mobilePath": "assets/art/backgrounds/bg-city-cafe.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.53,
      "y": 0.525
    },
    "bounds": {
      "x": 0.35,
      "y": 0.31,
      "width": 0.36,
      "height": 0.43
    }
  },
  "bg-waterfront-night": {
    "originalBounds": {
      "x": 0.4,
      "y": 0.34,
      "width": 0.34,
      "height": 0.37
    },
    "mobilePath": "assets/art/backgrounds/bg-waterfront-night.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.57,
      "y": 0.525
    },
    "bounds": {
      "x": 0.4,
      "y": 0.34,
      "width": 0.34,
      "height": 0.37
    }
  },
  "bg-adult-bedroom": {
    "originalBounds": {
      "x": 0.4,
      "y": 0.26,
      "width": 0.36,
      "height": 0.47
    },
    "mobilePath": "assets/art/backgrounds/bg-adult-bedroom.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.58,
      "y": 0.495
    },
    "bounds": {
      "x": 0.4,
      "y": 0.26,
      "width": 0.36,
      "height": 0.47
    }
  },
  "bg-airport-departure": {
    "originalBounds": {
      "x": 0.33,
      "y": 0.22,
      "width": 0.4,
      "height": 0.41
    },
    "mobilePath": "assets/art/backgrounds/bg-airport-departure.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.53,
      "y": 0.425
    },
    "bounds": {
      "x": 0.33,
      "y": 0.22,
      "width": 0.4,
      "height": 0.41
    }
  },
  "bg-holy-land-arrival": {
    "originalBounds": {
      "x": 0.32,
      "y": 0.18,
      "width": 0.36,
      "height": 0.55
    },
    "mobilePath": "assets/art/backgrounds/bg-holy-land-arrival.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.5,
      "y": 0.455
    },
    "bounds": {
      "x": 0.32,
      "y": 0.18,
      "width": 0.36,
      "height": 0.55
    }
  },
  "cg-jia-wen-boyfriend": {
    "originalBounds": {
      "x": 0.16,
      "y": 0.02,
      "width": 0.66,
      "height": 0.74
    },
    "mobilePath": "assets/art/portrait/cg-jia-wen-boyfriend.webp",
    "width": 960,
    "height": 1200,
    "focus": {
      "x": 0.48,
      "y": 0.405
    },
    "bounds": {
      "x": 0.14,
      "y": 0.15,
      "width": 0.68,
      "height": 0.51
    }
  },
  "cg-uss-confession": {
    "originalBounds": {
      "x": 0.31,
      "y": 0.025,
      "width": 0.39,
      "height": 0.95
    },
    "mobilePath": "assets/art/cg/cg-uss-confession.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.505,
      "y": 0.5
    },
    "bounds": {
      "x": 0.31,
      "y": 0.025,
      "width": 0.39,
      "height": 0.95
    }
  },
  "bg-umrah-common-area": {
    "originalBounds": {
      "x": 0.34,
      "y": 0.28,
      "width": 0.36,
      "height": 0.42
    },
    "mobilePath": "assets/art/backgrounds/bg-umrah-common-area.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.52,
      "y": 0.49
    },
    "bounds": {
      "x": 0.34,
      "y": 0.28,
      "width": 0.36,
      "height": 0.42
    }
  },
  "bg-makkah-courtyard": {
    "originalBounds": {
      "x": 0.3,
      "y": 0.005,
      "width": 0.39,
      "height": 0.72
    },
    "mobilePath": "assets/art/backgrounds/bg-makkah-courtyard.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.495,
      "y": 0.365
    },
    "bounds": {
      "x": 0.3,
      "y": 0.005,
      "width": 0.39,
      "height": 0.72
    }
  },
  "bg-jabal-nur-ascent": {
    "originalBounds": {
      "x": 0.37,
      "y": 0.13,
      "width": 0.35,
      "height": 0.58
    },
    "mobilePath": "assets/art/backgrounds/bg-jabal-nur-ascent.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.545,
      "y": 0.42
    },
    "bounds": {
      "x": 0.37,
      "y": 0.13,
      "width": 0.35,
      "height": 0.58
    }
  },
  "bg-jabal-nur-rest": {
    "originalBounds": {
      "x": 0.32,
      "y": 0.35,
      "width": 0.38,
      "height": 0.4
    },
    "mobilePath": "assets/art/backgrounds/bg-jabal-nur-rest.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.51,
      "y": 0.55
    },
    "bounds": {
      "x": 0.32,
      "y": 0.35,
      "width": 0.38,
      "height": 0.4
    }
  },
  "bg-jabal-rahmah": {
    "originalBounds": {
      "x": 0.27,
      "y": 0.1,
      "width": 0.38,
      "height": 0.59
    },
    "mobilePath": "assets/art/backgrounds/bg-jabal-rahmah.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.46,
      "y": 0.395
    },
    "bounds": {
      "x": 0.27,
      "y": 0.1,
      "width": 0.38,
      "height": 0.59
    }
  },
  "bg-madinah-courtyard": {
    "originalBounds": {
      "x": 0.33,
      "y": 0.2,
      "width": 0.37,
      "height": 0.53
    },
    "mobilePath": "assets/art/backgrounds/bg-madinah-courtyard.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.515,
      "y": 0.465
    },
    "bounds": {
      "x": 0.33,
      "y": 0.2,
      "width": 0.37,
      "height": 0.53
    }
  },
  "bg-nabawi-interior": {
    "originalBounds": {
      "x": 0.34,
      "y": 0.22,
      "width": 0.33,
      "height": 0.5
    },
    "mobilePath": "assets/art/backgrounds/bg-nabawi-interior.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.505,
      "y": 0.47
    },
    "bounds": {
      "x": 0.34,
      "y": 0.22,
      "width": 0.33,
      "height": 0.5
    }
  },
  "cg-umrah-jabal-nur": {
    "originalBounds": {
      "x": 0.21,
      "y": 0.04,
      "width": 0.58,
      "height": 0.73
    },
    "mobilePath": "assets/art/cg/cg-umrah-jabal-nur.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.5,
      "y": 0.405
    },
    "bounds": {
      "x": 0.21,
      "y": 0.04,
      "width": 0.58,
      "height": 0.73
    }
  },
  "cg-umrah-jabal-rahmah": {
    "originalBounds": {
      "x": 0.21,
      "y": 0.06,
      "width": 0.47,
      "height": 0.73
    },
    "mobilePath": "assets/art/cg/cg-umrah-jabal-rahmah.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.445,
      "y": 0.425
    },
    "bounds": {
      "x": 0.21,
      "y": 0.06,
      "width": 0.47,
      "height": 0.73
    }
  },
  "cg-nabawi-release": {
    "originalBounds": {
      "x": 0.24,
      "y": 0.045,
      "width": 0.39,
      "height": 0.88
    },
    "mobilePath": "assets/art/cg/cg-nabawi-release.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.435,
      "y": 0.485
    },
    "bounds": {
      "x": 0.24,
      "y": 0.045,
      "width": 0.39,
      "height": 0.88
    }
  },
  "bg-yakiniku-date": {
    "originalBounds": {
      "x": 0.3,
      "y": 0.35,
      "width": 0.4,
      "height": 0.38
    },
    "mobilePath": "assets/art/backgrounds/bg-yakiniku-date.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.5,
      "y": 0.54
    },
    "bounds": {
      "x": 0.3,
      "y": 0.35,
      "width": 0.4,
      "height": 0.38
    }
  },
  "bg-kazakhstan-stay": {
    "originalBounds": {
      "x": 0.33,
      "y": 0.26,
      "width": 0.39,
      "height": 0.43
    },
    "mobilePath": "assets/art/backgrounds/bg-kazakhstan-stay.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.525,
      "y": 0.475
    },
    "bounds": {
      "x": 0.33,
      "y": 0.26,
      "width": 0.39,
      "height": 0.43
    }
  },
  "bg-parents-restaurant": {
    "originalBounds": {
      "x": 0.32,
      "y": 0.3,
      "width": 0.36,
      "height": 0.43
    },
    "mobilePath": "assets/art/backgrounds/bg-parents-restaurant.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.5,
      "y": 0.515
    },
    "bounds": {
      "x": 0.32,
      "y": 0.3,
      "width": 0.36,
      "height": 0.43
    }
  },
  "bg-kallang-pier-sunset": {
    "originalBounds": {
      "x": 0.3,
      "y": 0.24,
      "width": 0.4,
      "height": 0.44
    },
    "mobilePath": "assets/art/backgrounds/bg-kallang-pier-sunset.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.5,
      "y": 0.46
    },
    "bounds": {
      "x": 0.3,
      "y": 0.24,
      "width": 0.4,
      "height": 0.44
    }
  },
  "cg-parents-meeting": {
    "originalBounds": {
      "x": 0.13,
      "y": 0.06,
      "width": 0.76,
      "height": 0.55
    },
    "mobilePath": "assets/art/portrait/cg-parents-meeting.webp",
    "width": 960,
    "height": 1200,
    "focus": {
      "x": 0.52,
      "y": 0.39
    },
    "bounds": {
      "x": 0.095,
      "y": 0.22,
      "width": 0.85,
      "height": 0.34
    }
  },
  "cg-kallang-confession": {
    "originalBounds": {
      "x": 0.29,
      "y": 0.055,
      "width": 0.43,
      "height": 0.77
    },
    "mobilePath": "assets/art/portrait/cg-kallang-confession.webp",
    "width": 960,
    "height": 1200,
    "focus": {
      "x": 0.52,
      "y": 0.435
    },
    "bounds": {
      "x": 0.26,
      "y": 0.22,
      "width": 0.52,
      "height": 0.43
    }
  },
  "cg-wedding-planning": {
    "originalBounds": {
      "x": 0.23,
      "y": 0.01,
      "width": 0.5,
      "height": 0.73
    },
    "mobilePath": "assets/art/portrait/cg-wedding-planning.webp",
    "width": 960,
    "height": 1200,
    "focus": {
      "x": 0.49,
      "y": 0.45
    },
    "bounds": {
      "x": 0.19,
      "y": 0.22,
      "width": 0.6,
      "height": 0.46
    }
  },
  "bg-primary-classroom": {
    "originalBounds": {
      "x": 0.34,
      "y": 0.23,
      "width": 0.38,
      "height": 0.5
    },
    "mobilePath": "assets/art/backgrounds/bg-primary-classroom.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.53,
      "y": 0.48
    },
    "bounds": {
      "x": 0.34,
      "y": 0.23,
      "width": 0.38,
      "height": 0.5
    }
  },
  "bg-primary-corridor": {
    "originalBounds": {
      "x": 0.31,
      "y": 0.33,
      "width": 0.37,
      "height": 0.49
    },
    "mobilePath": "assets/art/backgrounds/bg-primary-corridor.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.495,
      "y": 0.575
    },
    "bounds": {
      "x": 0.31,
      "y": 0.33,
      "width": 0.37,
      "height": 0.49
    }
  },
  "bg-primary-canteen": {
    "originalBounds": {
      "x": 0.28,
      "y": 0.37,
      "width": 0.39,
      "height": 0.37
    },
    "mobilePath": "assets/art/backgrounds/bg-primary-canteen.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.475,
      "y": 0.555
    },
    "bounds": {
      "x": 0.28,
      "y": 0.37,
      "width": 0.39,
      "height": 0.37
    }
  },
  "bg-graduation-gate": {
    "originalBounds": {
      "x": 0.36,
      "y": 0.31,
      "width": 0.35,
      "height": 0.39
    },
    "mobilePath": "assets/art/backgrounds/bg-graduation-gate.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.535,
      "y": 0.505
    },
    "bounds": {
      "x": 0.36,
      "y": 0.31,
      "width": 0.35,
      "height": 0.39
    }
  },
  "bg-bus-stop": {
    "originalBounds": {
      "x": 0.08,
      "y": 0.22,
      "width": 0.37,
      "height": 0.62
    },
    "mobilePath": "assets/art/backgrounds/bg-bus-stop.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.265,
      "y": 0.53
    },
    "bounds": {
      "x": 0.08,
      "y": 0.22,
      "width": 0.37,
      "height": 0.62
    }
  },
  "bg-bedroom-2009": {
    "originalBounds": {
      "x": 0.24,
      "y": 0.38,
      "width": 0.36,
      "height": 0.38
    },
    "mobilePath": "assets/art/backgrounds/bg-bedroom-2009.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.42,
      "y": 0.57
    },
    "bounds": {
      "x": 0.24,
      "y": 0.38,
      "width": 0.36,
      "height": 0.38
    }
  },
  "bg-bedroom-2009-warm": {
    "originalBounds": {
      "x": 0.24,
      "y": 0.38,
      "width": 0.36,
      "height": 0.38
    },
    "mobilePath": "assets/art/backgrounds/bg-bedroom-2009-warm.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.42,
      "y": 0.57
    },
    "bounds": {
      "x": 0.24,
      "y": 0.38,
      "width": 0.36,
      "height": 0.38
    }
  },
  "bg-alya-bedroom-2010": {
    "originalBounds": {
      "x": 0.12,
      "y": 0.3,
      "width": 0.38,
      "height": 0.44
    },
    "mobilePath": "assets/art/backgrounds/bg-alya-bedroom-2010.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.31,
      "y": 0.52
    },
    "bounds": {
      "x": 0.12,
      "y": 0.3,
      "width": 0.38,
      "height": 0.44
    }
  },
  "bg-boys-classroom": {
    "originalBounds": {
      "x": 0.34,
      "y": 0.26,
      "width": 0.36,
      "height": 0.48
    },
    "mobilePath": "assets/art/backgrounds/bg-boys-classroom.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.52,
      "y": 0.5
    },
    "bounds": {
      "x": 0.34,
      "y": 0.26,
      "width": 0.36,
      "height": 0.48
    }
  },
  "bg-boys-school-corridor": {
    "originalBounds": {
      "x": 0.34,
      "y": 0.33,
      "width": 0.34,
      "height": 0.44
    },
    "mobilePath": "assets/art/backgrounds/bg-boys-school-corridor.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.51,
      "y": 0.55
    },
    "bounds": {
      "x": 0.34,
      "y": 0.33,
      "width": 0.34,
      "height": 0.44
    }
  },
  "bg-boys-classroom-overcast": {
    "originalBounds": {
      "x": 0.34,
      "y": 0.26,
      "width": 0.36,
      "height": 0.48
    },
    "mobilePath": "assets/art/backgrounds/bg-boys-classroom-overcast.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.52,
      "y": 0.5
    },
    "bounds": {
      "x": 0.34,
      "y": 0.26,
      "width": 0.36,
      "height": 0.48
    }
  },
  "bg-language-classroom": {
    "originalBounds": {
      "x": 0.29,
      "y": 0.26,
      "width": 0.38,
      "height": 0.49
    },
    "mobilePath": "assets/art/backgrounds/bg-language-classroom.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.48,
      "y": 0.505
    },
    "bounds": {
      "x": 0.29,
      "y": 0.26,
      "width": 0.38,
      "height": 0.49
    }
  },
  "bg-language-classroom-late": {
    "originalBounds": {
      "x": 0.29,
      "y": 0.26,
      "width": 0.38,
      "height": 0.49
    },
    "mobilePath": "assets/art/backgrounds/bg-language-classroom-late.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.48,
      "y": 0.505
    },
    "bounds": {
      "x": 0.29,
      "y": 0.26,
      "width": 0.38,
      "height": 0.49
    }
  },
  "bg-language-courtyard": {
    "originalBounds": {
      "x": 0.42,
      "y": 0.29,
      "width": 0.35,
      "height": 0.48
    },
    "mobilePath": "assets/art/backgrounds/bg-language-courtyard.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.595,
      "y": 0.53
    },
    "bounds": {
      "x": 0.42,
      "y": 0.29,
      "width": 0.35,
      "height": 0.48
    }
  },
  "bg-language-corridor-rain": {
    "originalBounds": {
      "x": 0.27,
      "y": 0.25,
      "width": 0.38,
      "height": 0.58
    },
    "mobilePath": "assets/art/backgrounds/bg-language-corridor-rain.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.46,
      "y": 0.54
    },
    "bounds": {
      "x": 0.27,
      "y": 0.25,
      "width": 0.38,
      "height": 0.58
    }
  },
  "bg-bedroom-pc-day": {
    "originalBounds": {
      "x": 0.24,
      "y": 0.31,
      "width": 0.33,
      "height": 0.48
    },
    "mobilePath": "assets/art/backgrounds/bg-bedroom-pc-day.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.405,
      "y": 0.55
    },
    "bounds": {
      "x": 0.24,
      "y": 0.31,
      "width": 0.33,
      "height": 0.48
    }
  },
  "bg-bedroom-pc-night": {
    "originalBounds": {
      "x": 0.24,
      "y": 0.31,
      "width": 0.33,
      "height": 0.48
    },
    "mobilePath": "assets/art/backgrounds/bg-bedroom-pc-night.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.405,
      "y": 0.55
    },
    "bounds": {
      "x": 0.24,
      "y": 0.31,
      "width": 0.33,
      "height": 0.48
    }
  },
  "bg-exam-hall": {
    "originalBounds": {
      "x": 0.32,
      "y": 0.35,
      "width": 0.36,
      "height": 0.43
    },
    "mobilePath": "assets/art/backgrounds/bg-exam-hall.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.5,
      "y": 0.565
    },
    "bounds": {
      "x": 0.32,
      "y": 0.35,
      "width": 0.36,
      "height": 0.43
    }
  },
  "bg-results-hall": {
    "originalBounds": {
      "x": 0.34,
      "y": 0.3,
      "width": 0.34,
      "height": 0.46
    },
    "mobilePath": "assets/art/backgrounds/bg-results-hall.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.51,
      "y": 0.53
    },
    "bounds": {
      "x": 0.34,
      "y": 0.3,
      "width": 0.34,
      "height": 0.46
    }
  },
  "bg-dark-bedroom": {
    "originalBounds": {
      "x": 0.26,
      "y": 0.29,
      "width": 0.35,
      "height": 0.5
    },
    "mobilePath": "assets/art/backgrounds/bg-dark-bedroom.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.435,
      "y": 0.54
    },
    "bounds": {
      "x": 0.26,
      "y": 0.29,
      "width": 0.35,
      "height": 0.5
    }
  },
  "bg-dawn-window": {
    "originalBounds": {
      "x": 0.43,
      "y": 0.08,
      "width": 0.38,
      "height": 0.49
    },
    "mobilePath": "assets/art/backgrounds/bg-dawn-window.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.62,
      "y": 0.325
    },
    "bounds": {
      "x": 0.43,
      "y": 0.08,
      "width": 0.38,
      "height": 0.49
    }
  },
  "cg-wrong-message": {
    "originalBounds": {
      "x": 0.36,
      "y": 0.13,
      "width": 0.29,
      "height": 0.59
    },
    "mobilePath": "assets/art/cg/cg-wrong-message.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.505,
      "y": 0.425
    },
    "bounds": {
      "x": 0.36,
      "y": 0.13,
      "width": 0.29,
      "height": 0.59
    }
  },
  "cg-first-confession": {
    "originalBounds": {
      "x": 0.26,
      "y": 0.045,
      "width": 0.51,
      "height": 0.8
    },
    "mobilePath": "assets/art/portrait/cg-first-confession.webp",
    "width": 960,
    "height": 1200,
    "focus": {
      "x": 0.5,
      "y": 0.425
    },
    "bounds": {
      "x": 0.2,
      "y": 0.16,
      "width": 0.6,
      "height": 0.53
    }
  },
  "cg-graduation-promise": {
    "originalBounds": {
      "x": 0.29,
      "y": 0.14,
      "width": 0.4,
      "height": 0.83
    },
    "mobilePath": "assets/art/cg/cg-graduation-promise.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.49,
      "y": 0.555
    },
    "bounds": {
      "x": 0.29,
      "y": 0.14,
      "width": 0.4,
      "height": 0.83
    }
  },
  "cg-server-night": {
    "originalBounds": {
      "x": 0.13,
      "y": 0.14,
      "width": 0.49,
      "height": 0.74
    },
    "mobilePath": "assets/art/cg/cg-server-night.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.375,
      "y": 0.51
    },
    "bounds": {
      "x": 0.13,
      "y": 0.14,
      "width": 0.49,
      "height": 0.74
    }
  },
  "cg-results": {
    "originalBounds": {
      "x": 0.32,
      "y": 0.08,
      "width": 0.3,
      "height": 0.7
    },
    "mobilePath": "assets/art/cg/cg-results.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.47,
      "y": 0.43
    },
    "bounds": {
      "x": 0.32,
      "y": 0.08,
      "width": 0.3,
      "height": 0.7
    }
  },
  "cg-faris-wingman": {
    "originalBounds": {
      "x": 0.21,
      "y": 0.105,
      "width": 0.57,
      "height": 0.56
    },
    "mobilePath": "assets/art/portrait/cg-faris-wingman.webp",
    "width": 960,
    "height": 1200,
    "focus": {
      "x": 0.475,
      "y": 0.355
    },
    "bounds": {
      "x": 0.14,
      "y": 0.14,
      "width": 0.67,
      "height": 0.43
    }
  },
  "cg-hana-breakup": {
    "originalBounds": {
      "x": 0.2,
      "y": 0.07,
      "width": 0.6,
      "height": 0.73
    },
    "mobilePath": "assets/art/portrait/cg-hana-breakup.webp",
    "width": 960,
    "height": 1200,
    "focus": {
      "x": 0.535,
      "y": 0.465
    },
    "bounds": {
      "x": 0.15,
      "y": 0.22,
      "width": 0.77,
      "height": 0.49
    }
  },
  "cg-o-level-exam": {
    "originalBounds": {
      "x": 0.25,
      "y": 0.07,
      "width": 0.41,
      "height": 0.82
    },
    "mobilePath": "assets/art/cg/cg-o-level-exam.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.455,
      "y": 0.48
    },
    "bounds": {
      "x": 0.25,
      "y": 0.07,
      "width": 0.41,
      "height": 0.82
    }
  },
  "bg-hdb-dining": {
    "originalBounds": {
      "x": 0.36,
      "y": 0.42,
      "width": 0.4,
      "height": 0.48
    },
    "mobilePath": "assets/art/backgrounds/bg-hdb-dining.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.56,
      "y": 0.66
    },
    "bounds": {
      "x": 0.36,
      "y": 0.42,
      "width": 0.4,
      "height": 0.48
    }
  },
  "bg-jc-walkway": {
    "originalBounds": {
      "x": 0.34,
      "y": 0.25,
      "width": 0.35,
      "height": 0.56
    },
    "mobilePath": "assets/art/backgrounds/bg-jc-walkway.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.515,
      "y": 0.53
    },
    "bounds": {
      "x": 0.34,
      "y": 0.25,
      "width": 0.35,
      "height": 0.56
    }
  },
  "bg-jc-classroom": {
    "originalBounds": {
      "x": 0.3,
      "y": 0.26,
      "width": 0.38,
      "height": 0.52
    },
    "mobilePath": "assets/art/backgrounds/bg-jc-classroom.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.49,
      "y": 0.52
    },
    "bounds": {
      "x": 0.3,
      "y": 0.26,
      "width": 0.38,
      "height": 0.52
    }
  },
  "bg-bus-interior-morning": {
    "originalBounds": {
      "x": 0.27,
      "y": 0.28,
      "width": 0.45,
      "height": 0.59
    },
    "mobilePath": "assets/art/backgrounds/bg-bus-interior-morning.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.495,
      "y": 0.575
    },
    "bounds": {
      "x": 0.27,
      "y": 0.28,
      "width": 0.45,
      "height": 0.59
    }
  },
  "bg-bus-interior-evening": {
    "originalBounds": {
      "x": 0.27,
      "y": 0.28,
      "width": 0.45,
      "height": 0.59
    },
    "mobilePath": "assets/art/backgrounds/bg-bus-interior-evening.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.495,
      "y": 0.575
    },
    "bounds": {
      "x": 0.27,
      "y": 0.28,
      "width": 0.45,
      "height": 0.59
    }
  },
  "bg-jc-study-area": {
    "originalBounds": {
      "x": 0.27,
      "y": 0.44,
      "width": 0.42,
      "height": 0.37
    },
    "mobilePath": "assets/art/backgrounds/bg-jc-study-area.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.48,
      "y": 0.625
    },
    "bounds": {
      "x": 0.27,
      "y": 0.44,
      "width": 0.42,
      "height": 0.37
    }
  },
  "bg-a-level-results": {
    "originalBounds": {
      "x": 0.31,
      "y": 0.23,
      "width": 0.4,
      "height": 0.56
    },
    "mobilePath": "assets/art/backgrounds/bg-a-level-results.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.51,
      "y": 0.51
    },
    "bounds": {
      "x": 0.31,
      "y": 0.23,
      "width": 0.4,
      "height": 0.56
    }
  },
  "bg-zoo-path": {
    "originalBounds": {
      "x": 0.32,
      "y": 0.28,
      "width": 0.36,
      "height": 0.47
    },
    "mobilePath": "assets/art/backgrounds/bg-zoo-path.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.5,
      "y": 0.515
    },
    "bounds": {
      "x": 0.32,
      "y": 0.28,
      "width": 0.36,
      "height": 0.47
    }
  },
  "bg-zoo-shelter": {
    "originalBounds": {
      "x": 0.36,
      "y": 0.18,
      "width": 0.39,
      "height": 0.56
    },
    "mobilePath": "assets/art/backgrounds/bg-zoo-shelter.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.555,
      "y": 0.46
    },
    "bounds": {
      "x": 0.36,
      "y": 0.18,
      "width": 0.39,
      "height": 0.56
    }
  },
  "cg-shared-earpiece": {
    "originalBounds": {
      "x": 0.36,
      "y": 0.065,
      "width": 0.47,
      "height": 0.9
    },
    "mobilePath": "assets/art/cg/cg-shared-earpiece.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.595,
      "y": 0.515
    },
    "bounds": {
      "x": 0.36,
      "y": 0.065,
      "width": 0.47,
      "height": 0.9
    }
  },
  "cg-syafiqa-sighting": {
    "originalBounds": {
      "x": 0.13,
      "y": 0.02,
      "width": 0.67,
      "height": 0.72
    },
    "mobilePath": "assets/art/portrait/cg-syafiqa-sighting.webp",
    "width": 960,
    "height": 1200,
    "focus": {
      "x": 0.505,
      "y": 0.35
    },
    "bounds": {
      "x": 0.12,
      "y": 0.12,
      "width": 0.77,
      "height": 0.46
    }
  },
  "cg-zoo-distance": {
    "originalBounds": {
      "x": 0.18,
      "y": 0.015,
      "width": 0.68,
      "height": 0.77
    },
    "mobilePath": "assets/art/portrait/cg-zoo-distance.webp",
    "width": 960,
    "height": 1200,
    "focus": {
      "x": 0.52,
      "y": 0.395
    },
    "bounds": {
      "x": 0.15,
      "y": 0.14,
      "width": 0.74,
      "height": 0.51
    }
  },
  "bg-raya-living-room-2016": {
    "originalBounds": {
      "x": 0.3,
      "y": 0.06,
      "width": 0.38,
      "height": 0.74
    },
    "mobilePath": "assets/art/backgrounds/bg-raya-living-room-2016.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.49,
      "y": 0.43
    },
    "bounds": {
      "x": 0.3,
      "y": 0.06,
      "width": 0.38,
      "height": 0.74
    }
  },
  "bg-ns-camp-gate": {
    "originalBounds": {
      "x": 0.32,
      "y": 0.3,
      "width": 0.38,
      "height": 0.45
    },
    "mobilePath": "assets/art/backgrounds/bg-ns-camp-gate.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.51,
      "y": 0.525
    },
    "bounds": {
      "x": 0.32,
      "y": 0.3,
      "width": 0.38,
      "height": 0.45
    }
  },
  "bg-ns-bunk-night": {
    "originalBounds": {
      "x": 0.38,
      "y": 0.38,
      "width": 0.39,
      "height": 0.42
    },
    "mobilePath": "assets/art/backgrounds/bg-ns-bunk-night.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.575,
      "y": 0.59
    },
    "bounds": {
      "x": 0.38,
      "y": 0.38,
      "width": 0.39,
      "height": 0.42
    }
  },
  "bg-university-lecture-theatre": {
    "originalBounds": {
      "x": 0.31,
      "y": 0.24,
      "width": 0.36,
      "height": 0.56
    },
    "mobilePath": "assets/art/backgrounds/bg-university-lecture-theatre.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.49,
      "y": 0.52
    },
    "bounds": {
      "x": 0.31,
      "y": 0.24,
      "width": 0.36,
      "height": 0.56
    }
  },
  "bg-university-corridor": {
    "originalBounds": {
      "x": 0.32,
      "y": 0.3,
      "width": 0.39,
      "height": 0.44
    },
    "mobilePath": "assets/art/backgrounds/bg-university-corridor.webp",
    "width": 1600,
    "height": 900,
    "focus": {
      "x": 0.515,
      "y": 0.52
    },
    "bounds": {
      "x": 0.32,
      "y": 0.3,
      "width": 0.39,
      "height": 0.44
    }
  },
  "cg-raya-first-sight": {
    "originalBounds": {
      "x": 0.17,
      "y": 0.05,
      "width": 0.69,
      "height": 0.87
    },
    "mobilePath": "assets/art/portrait/cg-raya-first-sight.webp",
    "width": 960,
    "height": 1200,
    "focus": {
      "x": 0.49,
      "y": 0.405
    },
    "bounds": {
      "x": 0.11,
      "y": 0.08,
      "width": 0.76,
      "height": 0.65
    }
  },
  "cg-relationship-montage": {
    "originalBounds": {
      "x": 0.05,
      "y": 0.03,
      "width": 0.94,
      "height": 0.77
    },
    "mobilePath": "assets/art/portrait/cg-relationship-montage.webp",
    "width": 960,
    "height": 1200,
    "focus": {
      "x": 0.53,
      "y": 0.47
    },
    "bounds": {
      "x": 0.06,
      "y": 0.025,
      "width": 0.94,
      "height": 0.89
    }
  },
  "cg-close-friends-reveal": {
    "originalBounds": {
      "x": 0.11,
      "y": 0.01,
      "width": 0.74,
      "height": 0.98
    },
    "mobilePath": "assets/art/portrait/cg-close-friends-reveal.webp",
    "width": 960,
    "height": 1200,
    "focus": {
      "x": 0.6,
      "y": 0.5
    },
    "bounds": {
      "x": 0.25,
      "y": 0.13,
      "width": 0.7,
      "height": 0.74
    }
  }
};

const defaultBaseUrl = (): string =>
  (import.meta as ImportMeta & { readonly env?: { readonly BASE_URL?: string } }).env?.BASE_URL || "/";

export const createMobileArtOverrides = (baseUrl = defaultBaseUrl()): Readonly<Record<string, MobileArtOverride>> =>
  Object.fromEntries(Object.entries(reviewedScenes).map(([id, scene]) => [id, {
    protectedBounds: scene.originalBounds,
    mobile: { url: appPathname(scene.mobilePath, baseUrl), width: scene.width, height: scene.height,
      focalPoint: scene.focus, protectedBounds: scene.bounds },
  }]));

export const mobileArtOverrides = createMobileArtOverrides();
