// Generated by scripts/generate-art-content.ts. Do not edit.
export const generatedArtFiles = [
  {
    "url": "assets/art/backgrounds/bg-a-level-results.webp",
    "sha256": "5a6778b77516b492d957ca7119e32ae584d8ad06601486f8d9ec8240651f8efb",
    "bytes": 141414
  },
  {
    "url": "assets/art/backgrounds/bg-adult-bedroom.webp",
    "sha256": "390f59df1510b3b396f13d595bf8915448ba8a441a99277fb9ce71f92dd74214",
    "bytes": 83430
  },
  {
    "url": "assets/art/backgrounds/bg-airport-departure.webp",
    "sha256": "53ced8c42729b7707b550342a1be3a8edac54fcd7084ecc57469d271b3a12bbf",
    "bytes": 200978
  },
  {
    "url": "assets/art/backgrounds/bg-alya-bedroom-2010.webp",
    "sha256": "7e0dc8964a82b35c850d530c2a9a23d4b31c6529384e641c74927d3537af8684",
    "bytes": 50742
  },
  {
    "url": "assets/art/backgrounds/bg-bedroom-2009-warm.webp",
    "sha256": "40551b0c7a2d2cddc6e16a5a688ecc3d4a228bb257ae295a99e29755ba920763",
    "bytes": 86432
  },
  {
    "url": "assets/art/backgrounds/bg-bedroom-2009.webp",
    "sha256": "34fe5c95f8d2885d416a18361e60e18dcdea32af8c9676102d3a7aec262f2c17",
    "bytes": 58854
  },
  {
    "url": "assets/art/backgrounds/bg-bedroom-pc-day.webp",
    "sha256": "b219d13af55601ff1b88241e49fd46118af5b5eda334094fabea7049ab0df257",
    "bytes": 130838
  },
  {
    "url": "assets/art/backgrounds/bg-bedroom-pc-night.webp",
    "sha256": "5db704b568777613edac8d914a1a2b562c5aa5da85351c061b130a416854048a",
    "bytes": 101402
  },
  {
    "url": "assets/art/backgrounds/bg-boys-classroom-overcast.webp",
    "sha256": "c04dad0ee1d69cc2d17815b0a34f17c2dab0899b02a1f2d0947eea94da2f0ffb",
    "bytes": 116000
  },
  {
    "url": "assets/art/backgrounds/bg-boys-classroom.webp",
    "sha256": "a389bfe7427fa3eaec8ef9022ae13b352d14c4e356f006b9526015a183c9bfc1",
    "bytes": 158992
  },
  {
    "url": "assets/art/backgrounds/bg-boys-school-corridor.webp",
    "sha256": "f6f5525f02e80ba69393e656f1148e8c855d6387615bbc35cb1d3dd3a6ddb6c6",
    "bytes": 84948
  },
  {
    "url": "assets/art/backgrounds/bg-bus-interior-evening.webp",
    "sha256": "aa2f0d318b8a65d2770f7bfe37a0391009295f2d052c8fd528951632003e20b3",
    "bytes": 181628
  },
  {
    "url": "assets/art/backgrounds/bg-bus-interior-morning.webp",
    "sha256": "85bf4432b1ff44e879c3e6e72e2f9a24af7131936eca946fb36264278ef382a8",
    "bytes": 193160
  },
  {
    "url": "assets/art/backgrounds/bg-bus-stop.webp",
    "sha256": "e4b0d998ca1ca2cfb44877ebbbc91694f0b0c9eccd692044a59d02575bc120b9",
    "bytes": 306828
  },
  {
    "url": "assets/art/backgrounds/bg-city-cafe.webp",
    "sha256": "990cf98ee0987c2fe49b46dbdebb16d45a6a8cc6bd8a8737b9eb3bc7d1e7208c",
    "bytes": 213842
  },
  {
    "url": "assets/art/backgrounds/bg-dark-bedroom.webp",
    "sha256": "9fc7e026b66c9e33507b81e159e876ece1d0c7685ab97ffa8fef33460dc2f8b4",
    "bytes": 64130
  },
  {
    "url": "assets/art/backgrounds/bg-dawn-window.webp",
    "sha256": "52f2fe4263a3bfffd2aa2a2a961032bd484d552431aac25cc4a787bb97c23791",
    "bytes": 97204
  },
  {
    "url": "assets/art/backgrounds/bg-exam-hall.webp",
    "sha256": "a08f572c519479ba5aae52dde4abff98e7826e5aa4a35ca44c277225679ec880",
    "bytes": 149572
  },
  {
    "url": "assets/art/backgrounds/bg-graduation-gate.webp",
    "sha256": "a6cc768eb9af2468a3317a512e242c9830c5cdfcebfeea84e856dd9d3803cd42",
    "bytes": 271592
  },
  {
    "url": "assets/art/backgrounds/bg-hdb-dining.webp",
    "sha256": "1fc938bb912a861f9a0150b9f22b415fbcaf11031a1346d93da9cce5ae1311b9",
    "bytes": 71570
  },
  {
    "url": "assets/art/backgrounds/bg-holy-land-arrival.webp",
    "sha256": "882a3352169ef2777b0552f813d7033a14654e96d35595b348c0ec989bf981e2",
    "bytes": 172680
  },
  {
    "url": "assets/art/backgrounds/bg-jabal-nur-ascent.webp",
    "sha256": "50147e165d8eff1296a61705ad144096b5d91f95faed6b4534282b1552ba9256",
    "bytes": 284090
  },
  {
    "url": "assets/art/backgrounds/bg-jabal-nur-rest.webp",
    "sha256": "0384819c46ed78e04284a5a033d14dab8dbb7687005230ee2915f29b66cde9b9",
    "bytes": 271586
  },
  {
    "url": "assets/art/backgrounds/bg-jabal-rahmah.webp",
    "sha256": "82c71a65996fd495894940481460bb87445890854167f71a88086e56b431eb07",
    "bytes": 235760
  },
  {
    "url": "assets/art/backgrounds/bg-jc-classroom.webp",
    "sha256": "d9a2735a5b93ed65acc00b89238618903f17d566d1f0969a305db2c0bbbbc71b",
    "bytes": 147962
  },
  {
    "url": "assets/art/backgrounds/bg-jc-study-area.webp",
    "sha256": "90df64650abfa4a968b78158cd8483bff941dcdfb1f17d6834546fce305f96fe",
    "bytes": 120146
  },
  {
    "url": "assets/art/backgrounds/bg-jc-walkway.webp",
    "sha256": "4505c6acb1678afce39a36ffafac5147f20bd23315b803d0a19b5ed8e22a0fba",
    "bytes": 206690
  },
  {
    "url": "assets/art/backgrounds/bg-kallang-pier-sunset.webp",
    "sha256": "4a34e01423746b74b2d3f464e18dc562958cf7837536c32fbc1a500f3c598f0a",
    "bytes": 236870
  },
  {
    "url": "assets/art/backgrounds/bg-kazakhstan-stay.webp",
    "sha256": "513ea347e3710ba87c75f83347943dd165497b5adc9eef6583fdff15023c65ea",
    "bytes": 131554
  },
  {
    "url": "assets/art/backgrounds/bg-language-classroom-late.webp",
    "sha256": "23c154ca199edfed55828acf7738a4b2c6d1539d9136f365c9ecce92d3c669d1",
    "bytes": 101668
  },
  {
    "url": "assets/art/backgrounds/bg-language-classroom.webp",
    "sha256": "faf774a165b53b8c2ae785a744c101dc7acf43b4a7cbaa46b726a1eae7298abd",
    "bytes": 153628
  },
  {
    "url": "assets/art/backgrounds/bg-language-corridor-rain.webp",
    "sha256": "9576261558d395d0797cfd65a8834fe1fd0aa46a8a2fc6992a481ff17edad12e",
    "bytes": 140486
  },
  {
    "url": "assets/art/backgrounds/bg-language-courtyard.webp",
    "sha256": "a694cede1ead8e94452556e160faf0bf5f860d8615f5e802e9d32ce91c5be66b",
    "bytes": 279872
  },
  {
    "url": "assets/art/backgrounds/bg-madinah-courtyard.webp",
    "sha256": "667b5ecc4b138e7cd7d84e0444cd7bdf4222e63c833d8c4a11ea27a5c3acc036",
    "bytes": 176222
  },
  {
    "url": "assets/art/backgrounds/bg-makkah-courtyard.webp",
    "sha256": "b2cd290b48c9398c8ec5be3d325b7468b719ed0db9f0dc03b0ca9dbc5560260a",
    "bytes": 188932
  },
  {
    "url": "assets/art/backgrounds/bg-nabawi-interior.webp",
    "sha256": "6665d77218d852db5d0c277538e39644f85150d8e1a39078216e7eb24cb43de2",
    "bytes": 225082
  },
  {
    "url": "assets/art/backgrounds/bg-ns-bunk-night.webp",
    "sha256": "a330f5112269583b0a304e8beb256ed4f7e2f16ea4bf5c1222ab97793cf80700",
    "bytes": 51714
  },
  {
    "url": "assets/art/backgrounds/bg-ns-camp-gate.webp",
    "sha256": "bb0ddcaba6f23288504c8a15484961e92bbabfaec76733ec132f7478ff716e9a",
    "bytes": 241660
  },
  {
    "url": "assets/art/backgrounds/bg-office-pantry.webp",
    "sha256": "8a50e2cac55d6c92d0f36d97aa402fff2f2f62819a2aee9f128b494359b4e413",
    "bytes": 148944
  },
  {
    "url": "assets/art/backgrounds/bg-parents-restaurant.webp",
    "sha256": "1a66ec2f8c6b40d8e7d801e5713ddf1f7ac33ca3327acf997b509ac964c2673e",
    "bytes": 147954
  },
  {
    "url": "assets/art/backgrounds/bg-primary-canteen.webp",
    "sha256": "ff93e7ff580721900e6a37d71362f794639ebf6c091a2f18e9f73692f0b18c45",
    "bytes": 108980
  },
  {
    "url": "assets/art/backgrounds/bg-primary-classroom.webp",
    "sha256": "1aab9578bd9015dc0118682ef1c90cd81b64ed3170f4107fba3432f476eecad7",
    "bytes": 156958
  },
  {
    "url": "assets/art/backgrounds/bg-primary-corridor.webp",
    "sha256": "98ebaf0f6555f3bbf3214ed8d5116ede804dab3f6cb7c772e129bb94a86ea71a",
    "bytes": 160626
  },
  {
    "url": "assets/art/backgrounds/bg-raya-living-room-2016.webp",
    "sha256": "c114793b2b2b4272293c21d7eaf101575c9da2d8f0237214d0995820675cfa52",
    "bytes": 178694
  },
  {
    "url": "assets/art/backgrounds/bg-results-hall.webp",
    "sha256": "1a60e84422437cd472dff7929c17be2df8efe81bc5b0f5c8b8f0a8abc9acf593",
    "bytes": 99108
  },
  {
    "url": "assets/art/backgrounds/bg-umrah-common-area.webp",
    "sha256": "8d94d184138b627d42c3b4270af3eb71820f62a44c3ab6f07ea88c7ef39af674",
    "bytes": 138664
  },
  {
    "url": "assets/art/backgrounds/bg-uni-dorm.webp",
    "sha256": "f426654c3e17732f3804aeb84339e99b809b51254d8f1c646b27e13a7488eaad",
    "bytes": 147572
  },
  {
    "url": "assets/art/backgrounds/bg-uni-dropoff.webp",
    "sha256": "d496cb1b15243b7eddf74708234146065348b81d1f5d5fcede6480f4192fd2d8",
    "bytes": 250210
  },
  {
    "url": "assets/art/backgrounds/bg-uni-orientation.webp",
    "sha256": "fba543d12a5f2c9f78bbeb9ac36deb92a0a8cd43444bb942d834091931a0c07f",
    "bytes": 292794
  },
  {
    "url": "assets/art/backgrounds/bg-uni-study.webp",
    "sha256": "06aab8b5d5fcd14903702a51a3c99e247b8e223f0b7a6b44540b820931474b7d",
    "bytes": 193626
  },
  {
    "url": "assets/art/backgrounds/bg-university-corridor.webp",
    "sha256": "4d3ab69bb32375d929d5605ec844f26476e3d5f208b3b5f3329fc7883dad4940",
    "bytes": 103520
  },
  {
    "url": "assets/art/backgrounds/bg-university-lecture-theatre.webp",
    "sha256": "7302b1c5a865410fdd9d562bbd4ed0459aa558b5df78df3d51cad3f046033137",
    "bytes": 122544
  },
  {
    "url": "assets/art/backgrounds/bg-uss-evening.webp",
    "sha256": "37525cac904a238cf9b0b766f341809192d8f8ebed028438dd050c19bd1425f3",
    "bytes": 266618
  },
  {
    "url": "assets/art/backgrounds/bg-waterfront-night.webp",
    "sha256": "a8c72051148e0cb5efcf53f8900c4803aad973b5daa9263eee4e1b527daed6dd",
    "bytes": 156444
  },
  {
    "url": "assets/art/backgrounds/bg-yakiniku-date.webp",
    "sha256": "1364364a61e45baf76779e1e3efcbe21f90683c57ddeba6c7928cbe37654770c",
    "bytes": 117784
  },
  {
    "url": "assets/art/backgrounds/bg-zoo-path.webp",
    "sha256": "c4d232e286b916a389a83765f9d0d9c5f6dd878b11cc6b260b56396ba6450230",
    "bytes": 286116
  },
  {
    "url": "assets/art/backgrounds/bg-zoo-shelter.webp",
    "sha256": "ba94037903435372e306aee4eb70a902c5e7b25f24e39432195235ed7d110f8d",
    "bytes": 255358
  },
  {
    "url": "assets/art/cg/cg-close-friends-reveal.webp",
    "sha256": "0b9336b87ceffef1bbf5d739043c655f2d5716dae6b12beb7d48edf03f94a3ad",
    "bytes": 100050
  },
  {
    "url": "assets/art/cg/cg-faris-wingman.webp",
    "sha256": "95aecf851cd2cdf448ae5a30a66cef7eb07f90840dde4367f5d19cdeb49de2ee",
    "bytes": 223760
  },
  {
    "url": "assets/art/cg/cg-first-confession.webp",
    "sha256": "347bf8845e8cec01563b65d8196cb0085e28ee57cad30afcda81e2069632935b",
    "bytes": 128058
  },
  {
    "url": "assets/art/cg/cg-graduation-promise.webp",
    "sha256": "ce60c7b1d618df6a4a38f6a6c62cf01c6eeaf1ca69bae4ddec2986784dd927de",
    "bytes": 241628
  },
  {
    "url": "assets/art/cg/cg-hana-breakup.webp",
    "sha256": "046726666a03ca982e73e7fe15a6fff9320397d24c91988faa00b70347bcecc2",
    "bytes": 109864
  },
  {
    "url": "assets/art/cg/cg-jia-wen-boyfriend.webp",
    "sha256": "f4b89defd40f7c08602e6b5cb33a90c91ce2e308286cbc1ed923f28a406becc3",
    "bytes": 172326
  },
  {
    "url": "assets/art/cg/cg-kallang-confession.webp",
    "sha256": "e79da0ec9a41e111175236f5ec028707594a0a4cd4c3f56772b3b68842e37bfd",
    "bytes": 223126
  },
  {
    "url": "assets/art/cg/cg-nabawi-release.webp",
    "sha256": "b93abe31a86c3bf440ed1be2f3dd1e6e4c0f6ee536fd92b678d25412af094159",
    "bytes": 189952
  },
  {
    "url": "assets/art/cg/cg-o-level-exam.webp",
    "sha256": "1fdaf1fe53e84bd4d9b20449c72f5a703707bc6657b6b7e36cb3e4ee61ea7972",
    "bytes": 113398
  },
  {
    "url": "assets/art/cg/cg-parents-meeting.webp",
    "sha256": "bb6543a702f58fbc35a7317624d01177adf9fc9ab9e31a42b6ff15927a1203b2",
    "bytes": 192944
  },
  {
    "url": "assets/art/cg/cg-raya-first-sight.webp",
    "sha256": "680848cd4d91a9f1f88d07309f487e9474b28896869200a17f54d415536b9062",
    "bytes": 177844
  },
  {
    "url": "assets/art/cg/cg-relationship-montage.webp",
    "sha256": "71391b5412eacd9f153f0bf196b8ea08ff514deab62d5a77b1621290631d2ce2",
    "bytes": 141912
  },
  {
    "url": "assets/art/cg/cg-results.webp",
    "sha256": "b851018234a0ad8704b96c579c38ed91f0f16244b25a8c759934ca1662f78948",
    "bytes": 90712
  },
  {
    "url": "assets/art/cg/cg-server-night.webp",
    "sha256": "431304c2127ea77c375aaaee4d4485bd47166bfad8f80ebfe21551d101929e3d",
    "bytes": 115016
  },
  {
    "url": "assets/art/cg/cg-shared-earpiece.webp",
    "sha256": "feed576e0b1b133807cf3d10c10170da9f3209722b1cea21a2b1a828854df610",
    "bytes": 161914
  },
  {
    "url": "assets/art/cg/cg-syafiqa-sighting.webp",
    "sha256": "5c63d2d2c337cb86db122132e3dcab09d1ea26f445f36e8b9858e360c5850279",
    "bytes": 185526
  },
  {
    "url": "assets/art/cg/cg-umrah-jabal-nur.webp",
    "sha256": "39959c76b0bbbdd34d7c0f98f85a6e734c9b525ba38d5fcdc6cbadac3d98c8e2",
    "bytes": 274108
  },
  {
    "url": "assets/art/cg/cg-umrah-jabal-rahmah.webp",
    "sha256": "62e9cecdbeb2693212855b2eb25bbea12ec427e9f19cf4c4d1a27891dd91757d",
    "bytes": 233614
  },
  {
    "url": "assets/art/cg/cg-uss-confession.webp",
    "sha256": "bc21fcf27850e33ed06fd7a069803e51e2b06990b16f1d4a1887694d3c124634",
    "bytes": 230438
  },
  {
    "url": "assets/art/cg/cg-wedding-planning.webp",
    "sha256": "3f4d74f04356c111cd33c2bd27c8d127bce2b792057ef730764d8ea7ff4b494b",
    "bytes": 153380
  },
  {
    "url": "assets/art/cg/cg-wrong-message.webp",
    "sha256": "cdcd7a1aee24c2117c6ef46de74771da192eccc94c5c47922a99f913f8b19daa",
    "bytes": 70172
  },
  {
    "url": "assets/art/cg/cg-zoo-distance.webp",
    "sha256": "140a85d6e93c14770b14c670101d3c55ab54f1331115286ffb763bdd9055ed81",
    "bytes": 207010
  },
  {
    "url": "assets/art/characters/aleem-casual/frustrated.webp",
    "sha256": "9210bb34a3b3af0e498ae98fd41a946431a42b74a13e85565ef34894862ac05e",
    "bytes": 336128
  },
  {
    "url": "assets/art/characters/aleem-casual/neutral.webp",
    "sha256": "49ff7d51b3d6df029eacab54ea7096f013eda4891653d2656c45b5bc3fdfa2aa",
    "bytes": 339134
  },
  {
    "url": "assets/art/characters/aleem-casual/patient.webp",
    "sha256": "46895b300a0fd9902d4882fc568c5307992f4b3386476552784b3a94132873a3",
    "bytes": 337320
  },
  {
    "url": "assets/art/characters/aleem-casual/smile.webp",
    "sha256": "f1a2c06de045795ce68cc304f923e56e64d955d27615cbe80d0079d090a7db64",
    "bytes": 345758
  },
  {
    "url": "assets/art/characters/aleem-home/distracted.webp",
    "sha256": "289bb2909d13e09c98ed876d0a5294cd55212eeb15554ef0aa900de44fff83f2",
    "bytes": 286046
  },
  {
    "url": "assets/art/characters/aleem-home/focused.webp",
    "sha256": "3a7f73ae79babf1b26952cf2a55bb33808c10239c31791f4e046ab80ec8b97cd",
    "bytes": 284174
  },
  {
    "url": "assets/art/characters/aleem-home/numb.webp",
    "sha256": "d715af67889c0cd0e5bf04f0394d903d5670e4dc8a342a192170a8334337136e",
    "bytes": 284294
  },
  {
    "url": "assets/art/characters/aleem-home/overwhelmed.webp",
    "sha256": "4ca2f2369a76e95c32491272aad5a3586604aae2dc90d2c2444d278b63739200",
    "bytes": 282626
  },
  {
    "url": "assets/art/characters/aleem-home/proud.webp",
    "sha256": "99665bcc40844d1724d487433e0b91ddd4deaf64a13c0a561535a591be9cd8d2",
    "bytes": 283316
  },
  {
    "url": "assets/art/characters/aleem-home/regretful.webp",
    "sha256": "a4538b0b1dd13b58c0ff403011ff6cd959c6522f77478b2a94c10e1750318858",
    "bytes": 284728
  },
  {
    "url": "assets/art/characters/aleem-jc/focused.webp",
    "sha256": "63551e40b4ddd082336ce8d9696e0ba954d561725e505de322f4c4f30efc1fed",
    "bytes": 304272
  },
  {
    "url": "assets/art/characters/aleem-jc/hurt.webp",
    "sha256": "574a11e65db1a815e1172f0ea26ea0c3ab16ea772514455475c96317b78cdebf",
    "bytes": 301940
  },
  {
    "url": "assets/art/characters/aleem-jc/nervous.webp",
    "sha256": "8d154a94fb3e5de4b986511cae9c6498cdc76f0d64b84dd9397bf3d4af171019",
    "bytes": 304828
  },
  {
    "url": "assets/art/characters/aleem-jc/neutral.webp",
    "sha256": "452fabdc0c55444f9199eb0e3491c6a8305a11d96929c5d76364123ee0052cd5",
    "bytes": 305374
  },
  {
    "url": "assets/art/characters/aleem-jc/relieved.webp",
    "sha256": "fb45f0bf1ca09b31945cf0e84c95a46778aa15d9875c65cbc08f6426f9b1f263",
    "bytes": 303370
  },
  {
    "url": "assets/art/characters/aleem-jc/smile.webp",
    "sha256": "ac7c0dfa6f19fa4b569e9eb1a1233a6315a7c043a132b66235a8f3b091394609",
    "bytes": 307366
  },
  {
    "url": "assets/art/characters/aleem-jc/tired.webp",
    "sha256": "9112e9a60b67427791ca670c0fa7afb69065befe4d3b12ec7def2e5df157aa2c",
    "bytes": 303508
  },
  {
    "url": "assets/art/characters/aleem-jc/uncertain.webp",
    "sha256": "fe9708df6f8cc0b891d65c089b30452737fd7d89d70baa1b2fe8f5741bf16f80",
    "bytes": 304244
  },
  {
    "url": "assets/art/characters/aleem-ns/hurt.webp",
    "sha256": "dafcb1c5561cb20277786e4b2c6f3399fb81a80f30eb2754a2264cf9f14072cb",
    "bytes": 359320
  },
  {
    "url": "assets/art/characters/aleem-ns/neutral.webp",
    "sha256": "5f2c1119b8023f8d3831364662840daa7c5832571db161e400b04ddd599379d9",
    "bytes": 345962
  },
  {
    "url": "assets/art/characters/aleem-ns/numb.webp",
    "sha256": "03b71fb0aa04e8ade32b374bd5cbfd4eab5b07c9c8d50b578c883b2bd2399e73",
    "bytes": 355508
  },
  {
    "url": "assets/art/characters/aleem-ns/proud.webp",
    "sha256": "c1c75f980fa5d9077a8325985fccfcc7bce5b90cd9c0f05910bb92146d7665c7",
    "bytes": 347950
  },
  {
    "url": "assets/art/characters/aleem-ns/stunned.webp",
    "sha256": "cafec1ea2aff89098c59c257937e9b5bcd93cdc3569a8dbd08b8e744dfa5b1fc",
    "bytes": 354592
  },
  {
    "url": "assets/art/characters/aleem-ns/warm.webp",
    "sha256": "51ac393fa8e5ad277da5f0f3b105ce7f48f3facb365e151cb3cf5f1631c59b76",
    "bytes": 351398
  },
  {
    "url": "assets/art/characters/aleem-p6/cheerful.webp",
    "sha256": "8334d99f9f651e96e9afdc35f79bf18c0911512136695435fdaa9dfe2fd766c7",
    "bytes": 235276
  },
  {
    "url": "assets/art/characters/aleem-p6/nervous.webp",
    "sha256": "9a6e905208aa4ebcfcc447f71c6fd389a2bfa0f1748e097e1bb9b901f80333d6",
    "bytes": 255066
  },
  {
    "url": "assets/art/characters/aleem-p6/neutral.webp",
    "sha256": "d58dd19d1292768209c994f8aec4da138a5016dafe7ba0f54af653dbdcc6de9c",
    "bytes": 250460
  },
  {
    "url": "assets/art/characters/aleem-p6/reflective.webp",
    "sha256": "15aa45945a98c88501c92b2100090e5487f3100b2326407918b6a2bfccdbbd4c",
    "bytes": 251198
  },
  {
    "url": "assets/art/characters/aleem-p6/smile.webp",
    "sha256": "0c13031a6ef0f7c57b67bc2ca7622b6b16ce9692e1d56fd4bbb93d0a83689faa",
    "bytes": 257148
  },
  {
    "url": "assets/art/characters/aleem-p6/surprised.webp",
    "sha256": "e1906f14c66b148297f63c2cafaf6a643800ef5d3ac1f050056dc11b7ff60132",
    "bytes": 258110
  },
  {
    "url": "assets/art/characters/aleem-raya/awed.webp",
    "sha256": "8d590ae9732f2e4013abd9da91977dec4885c543a090cfd0a97262acc7126843",
    "bytes": 436750
  },
  {
    "url": "assets/art/characters/aleem-raya/shy-smile.webp",
    "sha256": "a9b484756395f7824923f02bc32dd11cd2eec71dd420091ed410b4f0e4285d45",
    "bytes": 451330
  },
  {
    "url": "assets/art/characters/aleem-sec/confused.webp",
    "sha256": "e7a2a7c29916dfbb938f8bceb50df7efab4b18d7249fc71d6402ba13b42e0586",
    "bytes": 278010
  },
  {
    "url": "assets/art/characters/aleem-sec/defensive.webp",
    "sha256": "31ea09556830742deb3382a9e6e096148e9651efeb76054fb7f41181ed3ec37d",
    "bytes": 270140
  },
  {
    "url": "assets/art/characters/aleem-sec/devastated.webp",
    "sha256": "4f41e6b1fe78f9ac0d5441c5bf38d910602afa69f3f4448d3c3d9524cf8a97ee",
    "bytes": 287478
  },
  {
    "url": "assets/art/characters/aleem-sec/embarrassed.webp",
    "sha256": "e8121c18aaa6caf579495ca3edb75ad0fd3aba7a3620f037cc9039e9093e3b8c",
    "bytes": 294136
  },
  {
    "url": "assets/art/characters/aleem-sec/guilty.webp",
    "sha256": "4721ab788de371d258d4722a2afd2c86ecf2e7a3e3c9c24a1fad3a7cada65e6e",
    "bytes": 269002
  },
  {
    "url": "assets/art/characters/aleem-sec/nervous.webp",
    "sha256": "18a6b9a1baa48455715fc32b91b0a6fa62ccb4deb081b59ad7c4eb984f30be9d",
    "bytes": 263816
  },
  {
    "url": "assets/art/characters/aleem-sec/neutral.webp",
    "sha256": "6f2a9a794c4ff1b4f99b6d6b85b46cd155b22e5f1ffac318842cf67c8f82d741",
    "bytes": 283594
  },
  {
    "url": "assets/art/characters/aleem-sec/smile.webp",
    "sha256": "df246d8eb8f86f8eb00e8709248c180cb18835553b912c746d6ab4a3c9515f38",
    "bytes": 286308
  },
  {
    "url": "assets/art/characters/aleem-sec/tired.webp",
    "sha256": "030418e978a9763bc093678733962b8dca4c1cdd6d7b18253d3485b2ce1bf38d",
    "bytes": 281260
  },
  {
    "url": "assets/art/characters/aleem-travel/hopeful.webp",
    "sha256": "e108aebeb91213570c6583cc9d15d53761dc7885445ca4190ea7f0fd17b29a4b",
    "bytes": 325618
  },
  {
    "url": "assets/art/characters/aleem-travel/tentative.webp",
    "sha256": "30b79d86833905150fa4762dd398364ecf359c4b51e8c0bb0589623c53854b45",
    "bytes": 326078
  },
  {
    "url": "assets/art/characters/aleem-travel/tired.webp",
    "sha256": "7e98c83cc91ede0d8944e71a856cfdd9b1abd806d8ec0115793aa7637a4b7ff8",
    "bytes": 328922
  },
  {
    "url": "assets/art/characters/aleem-umrah/neutral.webp",
    "sha256": "299708809f7256a0ca76eeff248375cdd58df23fcb56d45fea9f99ba8d1458c7",
    "bytes": 327646
  },
  {
    "url": "assets/art/characters/aleem-umrah/reflective.webp",
    "sha256": "5024d6cb8bdd524d72e02ae2a25d2abfe38aa86a63151926f6d40bd7829cf96b",
    "bytes": 338096
  },
  {
    "url": "assets/art/characters/aleem-umrah/relieved.webp",
    "sha256": "57dc391584497c55eb92d7d6bda3ff12d25eaaec4d34e2f01ad03d16befad0c6",
    "bytes": 327186
  },
  {
    "url": "assets/art/characters/aleem-umrah/resolved.webp",
    "sha256": "55087e3e4abda0703c5e117e7009b69dbba279b4fd7427ba6beb8685ac7c732c",
    "bytes": 336426
  },
  {
    "url": "assets/art/characters/aleem-umrah/surprised.webp",
    "sha256": "fd6b800f45f66dc444b9accbc148d97d1f0a5323ccbaa5c62740d0d97f873e67",
    "bytes": 327120
  },
  {
    "url": "assets/art/characters/aleem-umrah/warm.webp",
    "sha256": "9bccc151a0528bed07cf81e6b96f0e6f0046d08ea0f4e6c10bc12d6e11d29b2c",
    "bytes": 333234
  },
  {
    "url": "assets/art/characters/aleem-uni-arrival/breathless.webp",
    "sha256": "5fbecfe13d4fa9164bd3bdd94dda6c105e91bfda6c2fe229fc8d217ae41d04a2",
    "bytes": 382896
  },
  {
    "url": "assets/art/characters/aleem-uni-arrival/frozen.webp",
    "sha256": "17a74124874d9b28fc86cab772ff59039759f3476c74e6abfae1ecda5db019dd",
    "bytes": 368216
  },
  {
    "url": "assets/art/characters/aleem-uni-arrival/guarded.webp",
    "sha256": "d837f60027e9db6719240d56e65e1498ec45d3f54353d6591bc9a0bbc464b998",
    "bytes": 353620
  },
  {
    "url": "assets/art/characters/aleem-uni-arrival/neutral.webp",
    "sha256": "d2d1ef26411fbfa11f01b8dd4e5cd7825994e015e68db1684bd600503382c1fb",
    "bytes": 359680
  },
  {
    "url": "assets/art/characters/aleem-uni-arrival/overwhelmed.webp",
    "sha256": "08c5022aef15f9f1c4bb30d92c58cbae4ecb186d0bc202cf3366e627ea5da381",
    "bytes": 390462
  },
  {
    "url": "assets/art/characters/aleem-uni/amused.webp",
    "sha256": "aa51d237bc8965557b7c9fce40d8bd1e1710dee549e2a3dd02aacbebe2ccfae9",
    "bytes": 303244
  },
  {
    "url": "assets/art/characters/aleem-uni/hurt.webp",
    "sha256": "27ecd4bfe6f5b40f6933f695bec876aa5c0627d0f35e685f701dad7267ece9aa",
    "bytes": 294644
  },
  {
    "url": "assets/art/characters/aleem-uni/jealous.webp",
    "sha256": "6a53d9f4c52ef98a96d03f0cdb12a20c52e328f4024449eeaf7adf4cafb1d813",
    "bytes": 297814
  },
  {
    "url": "assets/art/characters/aleem-uni/nervous.webp",
    "sha256": "ac9cbda92dfee52ac7247c8541289bb1d6f529a3a4febef26161429fe318b594",
    "bytes": 291092
  },
  {
    "url": "assets/art/characters/aleem-uni/neutral.webp",
    "sha256": "2c42743c45be53e192e40c0e86bb7aae4f52c88adbe3f16a666f1dac07102d90",
    "bytes": 300504
  },
  {
    "url": "assets/art/characters/aleem-uni/smile.webp",
    "sha256": "ac56cd07e0a8e9af5a3774bf3fa5d4b8b2f69ba4264521e67fe3e7199439f81f",
    "bytes": 307252
  },
  {
    "url": "assets/art/characters/aleem-work/drained.webp",
    "sha256": "3aa4b78b625d6ec2d64431ee68d33780c606e773ecbfd7d9c383777ee9a6a9da",
    "bytes": 314786
  },
  {
    "url": "assets/art/characters/aleem-work/hurt.webp",
    "sha256": "844118818fa57082143f027bfb5491d7e78cc1c8a2511f3e252f8af934e28150",
    "bytes": 317234
  },
  {
    "url": "assets/art/characters/aleem-work/nervous.webp",
    "sha256": "246ae3c4863be96db7c54c811d9d23e742a73e02e945e2d3c3a8273792507f0a",
    "bytes": 288496
  },
  {
    "url": "assets/art/characters/aleem-work/neutral.webp",
    "sha256": "269f910b5ca9b5f45042a68ab641963b9a91d881b75e5a83afbc13e9c8250f58",
    "bytes": 315612
  },
  {
    "url": "assets/art/characters/aleem-work/smile.webp",
    "sha256": "1a402089948b0662bc305cf3afb928863ddafa68e8eca2158f6af899b6e667c1",
    "bytes": 311310
  },
  {
    "url": "assets/art/characters/aleem-young-home/hurt.webp",
    "sha256": "09f80b800829a65527cc4e29f79e76cbf168f9758b25b3de32275ea492231a71",
    "bytes": 239742
  },
  {
    "url": "assets/art/characters/aleem-young-home/neutral.webp",
    "sha256": "60d10da158cf7810f1b4f7923b4d28073a7ba5a99c07798ff3eca85a3ae641c3",
    "bytes": 252258
  },
  {
    "url": "assets/art/characters/aleem-young-home/smile.webp",
    "sha256": "cb4a0c6ae1a3f2fc10aa6a3955e62d5c7d8ecb33ae3072d862558e77efa78575",
    "bytes": 242134
  },
  {
    "url": "assets/art/characters/aleem-young-home/startled.webp",
    "sha256": "580b1dad667f61b53f6b541e62ec9a184fac617fc132fbf01121bc58e3cdca24",
    "bytes": 263076
  },
  {
    "url": "assets/art/characters/aleem-young-home/waiting.webp",
    "sha256": "d0e6fea0bc9b09cdfb35350354e3452656328330c3d3264c7ae552efd4beef50",
    "bytes": 241944
  },
  {
    "url": "assets/art/characters/alya-young-home/apologetic.webp",
    "sha256": "8bf507fea1f22fa25a325284008bf099cb4d75763634a7cf5ae41de6bfded363",
    "bytes": 171846
  },
  {
    "url": "assets/art/characters/alya-young-home/sad.webp",
    "sha256": "bdbc4ba3c7adffdfd2f3646e52ab87338cf2c8efc11cd53d2d581d3dc61711d8",
    "bytes": 172576
  },
  {
    "url": "assets/art/characters/alya-young-home/startled.webp",
    "sha256": "6a5181a6994f3d04dc044c810db4d4132206ac7f0c3e510eaa1399f198cd9d3c",
    "bytes": 175904
  },
  {
    "url": "assets/art/characters/alya/hopeful.webp",
    "sha256": "710d71bed5472c26df7960c290b5e84fe1abb5dca1bc178708becb02151678aa",
    "bytes": 176906
  },
  {
    "url": "assets/art/characters/alya/neutral.webp",
    "sha256": "3dc1ec4cb4fdbb4f8f422b627c5554a97352542a0b095cdbbd0e59ed9b763f07",
    "bytes": 178966
  },
  {
    "url": "assets/art/characters/alya/playful.webp",
    "sha256": "1c6f96de60a4e533e779dcd734138f973cdaad648f6c0c4c389841daf2e844ea",
    "bytes": 184000
  },
  {
    "url": "assets/art/characters/alya/shy.webp",
    "sha256": "c26cad6d6e773a513af073d35748bce75389aff75e563b36180fa6fa0a37cf09",
    "bytes": 172986
  },
  {
    "url": "assets/art/characters/alya/smile.webp",
    "sha256": "a0a5868f3128b65f354e94452b9b98d587918e465539d5140368a52014b71cf3",
    "bytes": 174546
  },
  {
    "url": "assets/art/characters/claire/amused.webp",
    "sha256": "30c0451f3b414f2f4f50c57294130b1ec489252d958dfa79f8c4a4fb597a11d0",
    "bytes": 295110
  },
  {
    "url": "assets/art/characters/claire/firm.webp",
    "sha256": "a9bceb32aa242c559ac951d2e4e12801d5be5bcffd6b1f657572fb34abf34d80",
    "bytes": 287686
  },
  {
    "url": "assets/art/characters/claire/neutral.webp",
    "sha256": "d183ba982cb8d8744820171fa9b65c27867ed0cc0b9476cb31df2b6ec5cd862a",
    "bytes": 293250
  },
  {
    "url": "assets/art/characters/claire/reflective.webp",
    "sha256": "322614e810691011ce31460cb455d201252058bb0f67054470da4cc793ccacb1",
    "bytes": 289644
  },
  {
    "url": "assets/art/characters/claire/smile.webp",
    "sha256": "2f3d21223162ee83febc030b226fbcf192b6751185db714e945e57a97b1c3808",
    "bytes": 287280
  },
  {
    "url": "assets/art/characters/faris/confident.webp",
    "sha256": "41e0e7fa488193e0b990de255db7d8be2e7baa7c5d4e58b8e03c4c66b28e8228",
    "bytes": 208666
  },
  {
    "url": "assets/art/characters/faris/encouraging.webp",
    "sha256": "5f475a075e88f99dc7e76f9aa21ccc70093fe1e2d0e57d3dfb6d899c39edb4ad",
    "bytes": 207506
  },
  {
    "url": "assets/art/characters/faris/neutral.webp",
    "sha256": "8faaab53419b06569a80762412774a717063da85493434204de40e52444873e1",
    "bytes": 211242
  },
  {
    "url": "assets/art/characters/faris/teasing.webp",
    "sha256": "f3df786a3c7de8fe9f08f204dc04e9d72ee7acfac00ff7b09bf13cf9bb3be70e",
    "bytes": 218016
  },
  {
    "url": "assets/art/characters/hana/apologetic.webp",
    "sha256": "ba5b220160ffe0bfa60e66ead5613517e9e2e03f22744c0704c236c34ac19a96",
    "bytes": 222738
  },
  {
    "url": "assets/art/characters/hana/concerned.webp",
    "sha256": "3f0ecf58c97d64eca40773371e0f0a5692f7702336ff307d7fec6fe353005b1b",
    "bytes": 218194
  },
  {
    "url": "assets/art/characters/hana/curious.webp",
    "sha256": "79d7da3cfb8db63d3d447da949c8a631ff607113e8cc45e6274581ee1d1e53a1",
    "bytes": 229886
  },
  {
    "url": "assets/art/characters/hana/disappointed.webp",
    "sha256": "0ceaa1ed977b5bfb2fe8f32fe684f4df43b74f0abdd6b6a6f2892b24d704668d",
    "bytes": 225188
  },
  {
    "url": "assets/art/characters/hana/distant.webp",
    "sha256": "dcf9c3ce248d06270d047ce0b1dbb993312110fa750bf5eb9633faa6fcf09ed3",
    "bytes": 214542
  },
  {
    "url": "assets/art/characters/hana/neutral.webp",
    "sha256": "fed7e996ad21ffeb25aba79cdc1537cade749808bee12ed0607971143b716cfe",
    "bytes": 226708
  },
  {
    "url": "assets/art/characters/hana/shy.webp",
    "sha256": "44268dfe2543325e01a5873c83e7360461b3e34fb09a70e25be2c710d9d56034",
    "bytes": 223676
  },
  {
    "url": "assets/art/characters/hana/smile.webp",
    "sha256": "6c1410dfeb2ec9492961c85f91d7392f4a5997905c1ff374ea8bc6e4c984313c",
    "bytes": 229770
  },
  {
    "url": "assets/art/characters/hana/supportive.webp",
    "sha256": "e08a0676b0233ed9a9c0a6af64a375a7402d7fef205fdef30c85ddc4465d3fc9",
    "bytes": 236370
  },
  {
    "url": "assets/art/characters/imran/encouraging.webp",
    "sha256": "c84ea7313169b344c59b1f077b262f97bb104be1689ea7e17482ae1521b43edf",
    "bytes": 346618
  },
  {
    "url": "assets/art/characters/imran/neutral.webp",
    "sha256": "45e94008d94448ed9293cdaf1a60ebf226066e48c56dc372e718cbcfbba6bf26",
    "bytes": 345096
  },
  {
    "url": "assets/art/characters/jia-wen/amused.webp",
    "sha256": "7f85e50546dd8ba8cd922fb9e230d77489b907d310b5271fc5ee4c6558b47e45",
    "bytes": 235432
  },
  {
    "url": "assets/art/characters/jia-wen/concerned.webp",
    "sha256": "cc4da6c5497391644bde041769a4cbb1cf0dc7b68506ccc5a1146a74449886ea",
    "bytes": 233646
  },
  {
    "url": "assets/art/characters/jia-wen/neutral.webp",
    "sha256": "19b1a8397cd60c716cdef9ed7e93d463cf672500d10feee4b003d73d77067bad",
    "bytes": 233740
  },
  {
    "url": "assets/art/characters/jia-wen/smile.webp",
    "sha256": "873c673e8d3710490a21bbdc38131acbf74e9c4491f2ee774ef5b4c8842aba5a",
    "bytes": 229700
  },
  {
    "url": "assets/art/characters/jia-wen/surprised.webp",
    "sha256": "859051f12132c932c9ac328bd399badd5ae99e2ca698bd090a106f61a162c453",
    "bytes": 230776
  },
  {
    "url": "assets/art/characters/mariam/encouraging.webp",
    "sha256": "0410661cc7597cbf69f0b2148cdf06fc417969e41d82ffba1a78db5bf462c7f0",
    "bytes": 277442
  },
  {
    "url": "assets/art/characters/mariam/neutral.webp",
    "sha256": "56c3a0383baa4b27861e3bc466f2fca442df40ff8ca7eab23f2e0dfff0d43ec5",
    "bytes": 280644
  },
  {
    "url": "assets/art/characters/mariam/warm.webp",
    "sha256": "769aa487680faaf3657f3a2899b15f23d6306f3f4a30f01e6d3277a3fc383cb9",
    "bytes": 274582
  },
  {
    "url": "assets/art/characters/mei-lin-casual/animated.webp",
    "sha256": "708e9e3e540f120bd7c9b2d2bcd22229136e72d6c28ed40e4ed34b49f42f9447",
    "bytes": 274854
  },
  {
    "url": "assets/art/characters/mei-lin-casual/guarded.webp",
    "sha256": "999769d56d62612502322b6247222ff8ab94bf39c5784a0eab354ac0ff5001cb",
    "bytes": 260032
  },
  {
    "url": "assets/art/characters/mei-lin-casual/neutral.webp",
    "sha256": "4b97e0c4cfd39e42a3b56c8647a1f35b69c348addd1c10b343caede3544bc51c",
    "bytes": 255796
  },
  {
    "url": "assets/art/characters/mei-lin-casual/smile.webp",
    "sha256": "09b276860756548531a2382b5d207c94b0eb24866a6a67a853fffebeb54ad060",
    "bytes": 295312
  },
  {
    "url": "assets/art/characters/mei-lin-jc/amused.webp",
    "sha256": "05bc302436a20b1358d578686b2da98e395b5bda4e03106b6afd82bfdad5d74e",
    "bytes": 243764
  },
  {
    "url": "assets/art/characters/mei-lin-jc/disappointed.webp",
    "sha256": "264d59948975c1df96d29452450b109ffa1cdcd8c4150164e4b7bd86faa2c470",
    "bytes": 240160
  },
  {
    "url": "assets/art/characters/mei-lin-jc/focused.webp",
    "sha256": "50f1c6724cbcd1f9257762821472545e8aecb6e14949737f6eb55d51d28561c2",
    "bytes": 249714
  },
  {
    "url": "assets/art/characters/mei-lin-jc/neutral.webp",
    "sha256": "068041be256a730c1e150245ca66c483215d83fcb0d2e24d24fc9e3adbfba61d",
    "bytes": 257086
  },
  {
    "url": "assets/art/characters/mei-lin-jc/supportive.webp",
    "sha256": "7df92d7f71f7417b140a552cf477f63ccb962a3fecf7fbcb2084fbadcece3dea",
    "bytes": 250542
  },
  {
    "url": "assets/art/characters/nadiah-umrah/amused.webp",
    "sha256": "c8ca1ee64f80f49134eafc01ffc28a3ed988bd31fbe5d3426516a411dc288a6f",
    "bytes": 261330
  },
  {
    "url": "assets/art/characters/nadiah-umrah/hesitant.webp",
    "sha256": "2f5832c0b75e0f5e4bc676b327da9221993c9f97bed5e864376532df19bfa512",
    "bytes": 261124
  },
  {
    "url": "assets/art/characters/nadiah-umrah/neutral.webp",
    "sha256": "0a67be9a9cebedca763bf689bb28daedabe92fdfa71df482ac5b3a1cd4d1a9a0",
    "bytes": 258422
  },
  {
    "url": "assets/art/characters/nadiah-umrah/warm.webp",
    "sha256": "2b3a42518e252910ff7eddc24fb569796d2941bc4d1ac77e3a460260fa2b9407",
    "bytes": 265916
  },
  {
    "url": "assets/art/characters/nadiah-umrah/wistful.webp",
    "sha256": "665db545570676c9840b9d654f4aa8c0a6582bbaa2cb87e089713cf9d533ad34",
    "bytes": 258034
  },
  {
    "url": "assets/art/characters/nadiah/amused.webp",
    "sha256": "d7f51485bfc37009b486566e79030952c5e44fd71e60b3a99d1f880cd36276fd",
    "bytes": 343624
  },
  {
    "url": "assets/art/characters/nadiah/guarded.webp",
    "sha256": "5ff49dcb7f89059dee5a95ce2892b0bf26598639b9856feb495d6a68236f2673",
    "bytes": 351134
  },
  {
    "url": "assets/art/characters/nadiah/neutral.webp",
    "sha256": "c349898cf3b33c05428470ec5476ea5c86e1c87efaaf483826995a8e761b8267",
    "bytes": 346916
  },
  {
    "url": "assets/art/characters/nadiah/thoughtful.webp",
    "sha256": "3f152e24cf4bcd598c6819a8d6f51537008cab2c2be5645b11723c5b5a7e4bfa",
    "bytes": 348460
  },
  {
    "url": "assets/art/characters/nadiah/warm.webp",
    "sha256": "edb109e9dec22c32279fcceeabd65c67e07d58ee84bb7556ab51fcc1e2d371dd",
    "bytes": 342564
  },
  {
    "url": "assets/art/characters/nurulain/amused.webp",
    "sha256": "f09128156a787305ff339c15b86d1039539a48be22db6dcedd0ea460e1bf752f",
    "bytes": 240354
  },
  {
    "url": "assets/art/characters/nurulain/anxious.webp",
    "sha256": "2b3ff541d55df05f440d929ff339a3cce8e3320a60f3f88eb65f915d12fe4fe7",
    "bytes": 236266
  },
  {
    "url": "assets/art/characters/nurulain/curious.webp",
    "sha256": "59c988ed179502c5f3b1e636803fb39d5c83d907c55c2fb3d91541b9b9f37f77",
    "bytes": 232544
  },
  {
    "url": "assets/art/characters/nurulain/guarded.webp",
    "sha256": "6881859dad4b3ca8a513208fef5641c0a4ecd035449a255216be041356dc779e",
    "bytes": 236722
  },
  {
    "url": "assets/art/characters/nurulain/moved.webp",
    "sha256": "88efb2ab9f50b46760d13c9fe74423177ccf3e088d84f4acaf1b171863305fb2",
    "bytes": 237848
  },
  {
    "url": "assets/art/characters/nurulain/neutral.webp",
    "sha256": "b1e634033c7ea1fed53ac4daafe5836190ea766ac593eac292b5871ff1be4917",
    "bytes": 232688
  },
  {
    "url": "assets/art/characters/nurulain/warm.webp",
    "sha256": "819948709882e3b8a3bda163b99f116ab912b8d6e7bad839e1e5ffee0d88d14b",
    "bytes": 233750
  },
  {
    "url": "assets/art/characters/syafiqa/amused.webp",
    "sha256": "f3c048e7d0fde3536c7ad350d146b88886a54e8d723fc51a80e8b402f136dcdd",
    "bytes": 306546
  },
  {
    "url": "assets/art/characters/syafiqa/attentive.webp",
    "sha256": "acdc66e542773812c48b021b83b7580aae1c0f3a5db1f8e0cf16eeaf30698d2c",
    "bytes": 306852
  },
  {
    "url": "assets/art/characters/syafiqa/gentle-firm.webp",
    "sha256": "7d6f4e918abd0e172e96a504ea7b7f4e695dcd1ba55b1750180c61be6e0602ed",
    "bytes": 290184
  },
  {
    "url": "assets/art/characters/syafiqa/neutral.webp",
    "sha256": "cb5b4669ab8e44b07eb58224a1e3964d505b4e887cc2a375cc5579de80395000",
    "bytes": 304460
  },
  {
    "url": "assets/art/characters/syafiqa/sleepy.webp",
    "sha256": "2052050c60654723de2d107a528d80bcc3c4b273bf930ac5966692e6dd052a5c",
    "bytes": 286792
  },
  {
    "url": "assets/art/characters/syafiqa/smile.webp",
    "sha256": "4376d969e8688589da36433095b8a8b3a197a5c37310dd8f3c4d6e0920c82832",
    "bytes": 298200
  },
  {
    "url": "assets/art/characters/yusuf/neutral.webp",
    "sha256": "a116f4e2c18d59ecc6ac66075f4a2588fd862bcf9d3d18e73a6ff3398926a0c8",
    "bytes": 357042
  },
  {
    "url": "assets/art/characters/yusuf/warm.webp",
    "sha256": "4b5647874a9d675eeb5180ba59e89ec979b087879d1332f655b40dfaf877e26a",
    "bytes": 348896
  },
  {
    "url": "assets/art/portrait/cg-close-friends-reveal.webp",
    "sha256": "c4f7ffd566bfbc3133a1a65ede5833331b1dee18ea20863d9a26a470b44463ce",
    "bytes": 101614
  },
  {
    "url": "assets/art/portrait/cg-faris-wingman.webp",
    "sha256": "288e6034b6de3c77ec8463e37dfd30d32ec111a44c49dcff9c0ad2241cb1e07a",
    "bytes": 208148
  },
  {
    "url": "assets/art/portrait/cg-first-confession.webp",
    "sha256": "5e187d74397524fd997dc495ace9f3f578ca03814ddf069680d0d5a1d0c5be4a",
    "bytes": 124716
  },
  {
    "url": "assets/art/portrait/cg-hana-breakup.webp",
    "sha256": "f7f025e3cb6caaada816b9b8080cd3483291073808a7fa22332e9eeb0af9116c",
    "bytes": 117276
  },
  {
    "url": "assets/art/portrait/cg-jia-wen-boyfriend.webp",
    "sha256": "447bbf6f5f923d34a1f72f24294e589193186a91592cb24c4ce5d07ac094f679",
    "bytes": 154962
  },
  {
    "url": "assets/art/portrait/cg-kallang-confession.webp",
    "sha256": "a8fe7e5808715c94120ead806d526161482d088a44d126c23e94e65e4ca6ab58",
    "bytes": 229174
  },
  {
    "url": "assets/art/portrait/cg-parents-meeting.webp",
    "sha256": "8e9ef3a0480ebb82cb992f85567960250ae88cac940ce7c251f23530ce205008",
    "bytes": 165084
  },
  {
    "url": "assets/art/portrait/cg-raya-first-sight.webp",
    "sha256": "b25de8ee6e16f9da90f954bcc4f0360ab0e623be37092ea90df5cbbac16a59f1",
    "bytes": 162714
  },
  {
    "url": "assets/art/portrait/cg-relationship-montage.webp",
    "sha256": "3aad924e675be44e8b2d53aea07a391af070f497a9065a94247356c204ad0101",
    "bytes": 158910
  },
  {
    "url": "assets/art/portrait/cg-syafiqa-sighting.webp",
    "sha256": "08406a47bbf68bb6e35c1a634196ab27a088bda3dd23f1ab5341f8c1e59cdd03",
    "bytes": 162070
  },
  {
    "url": "assets/art/portrait/cg-wedding-planning.webp",
    "sha256": "c69451cf2c31625766d4459bd2d9b7e96a7b74b22fad25b07e2f631103063e87",
    "bytes": 143770
  },
  {
    "url": "assets/art/portrait/cg-zoo-distance.webp",
    "sha256": "4f782b7822bf82b5922d04f1873b605a739abaafdf34470ae450758417721e18",
    "bytes": 249276
  }
] as const;

export const generatedArtPacks = [
  {
    "id": "art-prologue",
    "chapterId": "prologue",
    "title": "Before Nurul",
    "urls": [
      "assets/art/backgrounds/bg-dawn-window.webp"
    ],
    "expectedBytes": 97204,
    "revision": "4f5be0fa3bc7b74aa3285d3ce71aefb2bbd13f861745f2364af664fcd5273007"
  },
  {
    "id": "art-chapter-1",
    "chapterId": "chapter-1",
    "title": "The Wrong Message",
    "urls": [
      "assets/art/backgrounds/bg-alya-bedroom-2010.webp",
      "assets/art/backgrounds/bg-bedroom-2009-warm.webp",
      "assets/art/backgrounds/bg-bedroom-2009.webp",
      "assets/art/backgrounds/bg-bus-stop.webp",
      "assets/art/backgrounds/bg-dawn-window.webp",
      "assets/art/backgrounds/bg-graduation-gate.webp",
      "assets/art/backgrounds/bg-primary-canteen.webp",
      "assets/art/backgrounds/bg-primary-classroom.webp",
      "assets/art/backgrounds/bg-primary-corridor.webp",
      "assets/art/cg/cg-first-confession.webp",
      "assets/art/cg/cg-graduation-promise.webp",
      "assets/art/cg/cg-wrong-message.webp",
      "assets/art/characters/aleem-p6/cheerful.webp",
      "assets/art/characters/aleem-p6/nervous.webp",
      "assets/art/characters/aleem-p6/neutral.webp",
      "assets/art/characters/aleem-p6/reflective.webp",
      "assets/art/characters/aleem-p6/smile.webp",
      "assets/art/characters/aleem-p6/surprised.webp",
      "assets/art/characters/aleem-young-home/hurt.webp",
      "assets/art/characters/aleem-young-home/neutral.webp",
      "assets/art/characters/aleem-young-home/smile.webp",
      "assets/art/characters/aleem-young-home/startled.webp",
      "assets/art/characters/aleem-young-home/waiting.webp",
      "assets/art/characters/alya-young-home/apologetic.webp",
      "assets/art/characters/alya-young-home/sad.webp",
      "assets/art/characters/alya-young-home/startled.webp",
      "assets/art/characters/alya/hopeful.webp",
      "assets/art/characters/alya/neutral.webp",
      "assets/art/characters/alya/playful.webp",
      "assets/art/characters/alya/shy.webp",
      "assets/art/characters/alya/smile.webp",
      "assets/art/portrait/cg-first-confession.webp"
    ],
    "expectedBytes": 6016932,
    "revision": "8f50a541122e3144a50a78afa9d4e9cf4c4007952b7c33aa00eeb0497cf92346"
  },
  {
    "id": "art-chapter-2",
    "chapterId": "chapter-2",
    "title": "A Different Classroom",
    "urls": [
      "assets/art/backgrounds/bg-bedroom-pc-day.webp",
      "assets/art/backgrounds/bg-bedroom-pc-night.webp",
      "assets/art/backgrounds/bg-boys-classroom-overcast.webp",
      "assets/art/backgrounds/bg-boys-classroom.webp",
      "assets/art/backgrounds/bg-boys-school-corridor.webp",
      "assets/art/backgrounds/bg-dark-bedroom.webp",
      "assets/art/backgrounds/bg-dawn-window.webp",
      "assets/art/backgrounds/bg-exam-hall.webp",
      "assets/art/backgrounds/bg-language-classroom-late.webp",
      "assets/art/backgrounds/bg-language-classroom.webp",
      "assets/art/backgrounds/bg-language-corridor-rain.webp",
      "assets/art/backgrounds/bg-language-courtyard.webp",
      "assets/art/backgrounds/bg-results-hall.webp",
      "assets/art/cg/cg-faris-wingman.webp",
      "assets/art/cg/cg-hana-breakup.webp",
      "assets/art/cg/cg-o-level-exam.webp",
      "assets/art/cg/cg-results.webp",
      "assets/art/cg/cg-server-night.webp",
      "assets/art/characters/aleem-home/distracted.webp",
      "assets/art/characters/aleem-home/focused.webp",
      "assets/art/characters/aleem-home/numb.webp",
      "assets/art/characters/aleem-home/overwhelmed.webp",
      "assets/art/characters/aleem-home/proud.webp",
      "assets/art/characters/aleem-home/regretful.webp",
      "assets/art/characters/aleem-sec/confused.webp",
      "assets/art/characters/aleem-sec/defensive.webp",
      "assets/art/characters/aleem-sec/devastated.webp",
      "assets/art/characters/aleem-sec/embarrassed.webp",
      "assets/art/characters/aleem-sec/guilty.webp",
      "assets/art/characters/aleem-sec/nervous.webp",
      "assets/art/characters/aleem-sec/neutral.webp",
      "assets/art/characters/aleem-sec/smile.webp",
      "assets/art/characters/aleem-sec/tired.webp",
      "assets/art/characters/faris/confident.webp",
      "assets/art/characters/faris/encouraging.webp",
      "assets/art/characters/faris/neutral.webp",
      "assets/art/characters/faris/teasing.webp",
      "assets/art/characters/hana/apologetic.webp",
      "assets/art/characters/hana/concerned.webp",
      "assets/art/characters/hana/curious.webp",
      "assets/art/characters/hana/disappointed.webp",
      "assets/art/characters/hana/distant.webp",
      "assets/art/characters/hana/neutral.webp",
      "assets/art/characters/hana/shy.webp",
      "assets/art/characters/hana/smile.webp",
      "assets/art/characters/hana/supportive.webp",
      "assets/art/portrait/cg-faris-wingman.webp",
      "assets/art/portrait/cg-hana-breakup.webp"
    ],
    "expectedBytes": 9747452,
    "revision": "b0296eedf9bf6075563181743f2db7c96890ecaea4fa34f4ff5c2bc1927b3e06"
  },
  {
    "id": "art-chapter-3",
    "chapterId": "chapter-3",
    "title": "The Bus We Waited For",
    "urls": [
      "assets/art/backgrounds/bg-bus-interior-evening.webp",
      "assets/art/backgrounds/bg-bus-interior-morning.webp",
      "assets/art/backgrounds/bg-bus-stop.webp",
      "assets/art/backgrounds/bg-dark-bedroom.webp",
      "assets/art/backgrounds/bg-dawn-window.webp",
      "assets/art/backgrounds/bg-hdb-dining.webp",
      "assets/art/backgrounds/bg-jc-classroom.webp",
      "assets/art/backgrounds/bg-jc-walkway.webp",
      "assets/art/backgrounds/bg-language-classroom.webp",
      "assets/art/cg/cg-shared-earpiece.webp",
      "assets/art/cg/cg-syafiqa-sighting.webp",
      "assets/art/characters/aleem-home/numb.webp",
      "assets/art/characters/aleem-jc/hurt.webp",
      "assets/art/characters/aleem-jc/nervous.webp",
      "assets/art/characters/aleem-jc/neutral.webp",
      "assets/art/characters/aleem-jc/smile.webp",
      "assets/art/characters/aleem-jc/uncertain.webp",
      "assets/art/characters/syafiqa/amused.webp",
      "assets/art/characters/syafiqa/attentive.webp",
      "assets/art/characters/syafiqa/gentle-firm.webp",
      "assets/art/characters/syafiqa/neutral.webp",
      "assets/art/characters/syafiqa/sleepy.webp",
      "assets/art/characters/syafiqa/smile.webp",
      "assets/art/portrait/cg-syafiqa-sighting.webp"
    ],
    "expectedBytes": 5533390,
    "revision": "198b74e5796470df5086cd364b43d4f309e438a9dd290838f6f0453b96f7271b"
  },
  {
    "id": "art-chapter-4",
    "chapterId": "chapter-4",
    "title": "Looking for an Answer",
    "urls": [
      "assets/art/backgrounds/bg-dark-bedroom.webp",
      "assets/art/backgrounds/bg-dawn-window.webp",
      "assets/art/backgrounds/bg-exam-hall.webp",
      "assets/art/backgrounds/bg-jc-classroom.webp",
      "assets/art/backgrounds/bg-jc-study-area.webp",
      "assets/art/backgrounds/bg-jc-walkway.webp",
      "assets/art/characters/aleem-jc/focused.webp",
      "assets/art/characters/aleem-jc/hurt.webp",
      "assets/art/characters/aleem-jc/neutral.webp",
      "assets/art/characters/aleem-jc/smile.webp",
      "assets/art/characters/aleem-jc/tired.webp",
      "assets/art/characters/aleem-jc/uncertain.webp",
      "assets/art/characters/mei-lin-jc/amused.webp",
      "assets/art/characters/mei-lin-jc/focused.webp",
      "assets/art/characters/mei-lin-jc/neutral.webp",
      "assets/art/characters/mei-lin-jc/supportive.webp"
    ],
    "expectedBytes": 3613514,
    "revision": "05fe94f2fdbfa5b6d6b093438273f00057ca5b959880e678d768b34968d7e578"
  },
  {
    "id": "art-chapter-5",
    "chapterId": "chapter-5",
    "title": "The Zoo After Results",
    "urls": [
      "assets/art/backgrounds/bg-a-level-results.webp",
      "assets/art/backgrounds/bg-dawn-window.webp",
      "assets/art/backgrounds/bg-jc-walkway.webp",
      "assets/art/backgrounds/bg-zoo-path.webp",
      "assets/art/backgrounds/bg-zoo-shelter.webp",
      "assets/art/cg/cg-zoo-distance.webp",
      "assets/art/characters/aleem-casual/frustrated.webp",
      "assets/art/characters/aleem-casual/neutral.webp",
      "assets/art/characters/aleem-casual/patient.webp",
      "assets/art/characters/aleem-casual/smile.webp",
      "assets/art/characters/aleem-jc/neutral.webp",
      "assets/art/characters/aleem-jc/relieved.webp",
      "assets/art/characters/mei-lin-casual/animated.webp",
      "assets/art/characters/mei-lin-casual/guarded.webp",
      "assets/art/characters/mei-lin-casual/neutral.webp",
      "assets/art/characters/mei-lin-casual/smile.webp",
      "assets/art/characters/mei-lin-jc/disappointed.webp",
      "assets/art/portrait/cg-zoo-distance.webp"
    ],
    "expectedBytes": 4736306,
    "revision": "7dc9a7441aec90184a643bef1336a9ac8f3af74b09c85c0114ddf0cf1d78c9ca"
  },
  {
    "id": "art-chapter-ns",
    "chapterId": "chapter-ns",
    "title": "The Story I Wasn’t In",
    "urls": [
      "assets/art/backgrounds/bg-dark-bedroom.webp",
      "assets/art/backgrounds/bg-dawn-window.webp",
      "assets/art/backgrounds/bg-hdb-dining.webp",
      "assets/art/backgrounds/bg-ns-bunk-night.webp",
      "assets/art/backgrounds/bg-ns-camp-gate.webp",
      "assets/art/backgrounds/bg-raya-living-room-2016.webp",
      "assets/art/backgrounds/bg-university-corridor.webp",
      "assets/art/backgrounds/bg-university-lecture-theatre.webp",
      "assets/art/cg/cg-close-friends-reveal.webp",
      "assets/art/cg/cg-raya-first-sight.webp",
      "assets/art/cg/cg-relationship-montage.webp",
      "assets/art/characters/aleem-ns/hurt.webp",
      "assets/art/characters/aleem-ns/neutral.webp",
      "assets/art/characters/aleem-ns/numb.webp",
      "assets/art/characters/aleem-ns/proud.webp",
      "assets/art/characters/aleem-ns/stunned.webp",
      "assets/art/characters/aleem-ns/warm.webp",
      "assets/art/characters/aleem-raya/awed.webp",
      "assets/art/characters/aleem-raya/shy-smile.webp",
      "assets/art/characters/aleem-uni-arrival/breathless.webp",
      "assets/art/characters/aleem-uni-arrival/frozen.webp",
      "assets/art/characters/aleem-uni-arrival/guarded.webp",
      "assets/art/characters/aleem-uni-arrival/neutral.webp",
      "assets/art/characters/aleem-uni-arrival/overwhelmed.webp",
      "assets/art/characters/nadiah/warm.webp",
      "assets/art/portrait/cg-close-friends-reveal.webp",
      "assets/art/portrait/cg-raya-first-sight.webp",
      "assets/art/portrait/cg-relationship-montage.webp"
    ],
    "expectedBytes": 6974328,
    "revision": "d8f24b8fa952a83a32a70f8b24a369da5fe7cfd484cc7a13eed61bfde502e92d"
  },
  {
    "id": "art-chapter-6",
    "chapterId": "chapter-6",
    "title": "Almost Us",
    "urls": [
      "assets/art/backgrounds/bg-adult-bedroom.webp",
      "assets/art/backgrounds/bg-uni-dorm.webp",
      "assets/art/backgrounds/bg-uni-dropoff.webp",
      "assets/art/backgrounds/bg-uni-orientation.webp",
      "assets/art/backgrounds/bg-uni-study.webp",
      "assets/art/backgrounds/bg-uss-evening.webp",
      "assets/art/cg/cg-jia-wen-boyfriend.webp",
      "assets/art/cg/cg-uss-confession.webp",
      "assets/art/characters/aleem-uni/amused.webp",
      "assets/art/characters/aleem-uni/hurt.webp",
      "assets/art/characters/aleem-uni/jealous.webp",
      "assets/art/characters/aleem-uni/nervous.webp",
      "assets/art/characters/aleem-uni/neutral.webp",
      "assets/art/characters/aleem-uni/smile.webp",
      "assets/art/characters/jia-wen/amused.webp",
      "assets/art/characters/jia-wen/concerned.webp",
      "assets/art/characters/jia-wen/neutral.webp",
      "assets/art/characters/jia-wen/smile.webp",
      "assets/art/characters/jia-wen/surprised.webp",
      "assets/art/portrait/cg-jia-wen-boyfriend.webp"
    ],
    "expectedBytes": 4749820,
    "revision": "11dadacfc50e9686f2ce33fa21b19b77232d3a0334f1dad3938b960b508028d2"
  },
  {
    "id": "art-chapter-7",
    "chapterId": "chapter-7",
    "title": "Just Friends",
    "urls": [
      "assets/art/backgrounds/bg-adult-bedroom.webp",
      "assets/art/backgrounds/bg-city-cafe.webp",
      "assets/art/backgrounds/bg-office-pantry.webp",
      "assets/art/backgrounds/bg-waterfront-night.webp",
      "assets/art/characters/aleem-work/drained.webp",
      "assets/art/characters/aleem-work/hurt.webp",
      "assets/art/characters/aleem-work/nervous.webp",
      "assets/art/characters/aleem-work/neutral.webp",
      "assets/art/characters/aleem-work/smile.webp",
      "assets/art/characters/claire/amused.webp",
      "assets/art/characters/claire/firm.webp",
      "assets/art/characters/claire/neutral.webp",
      "assets/art/characters/claire/reflective.webp",
      "assets/art/characters/claire/smile.webp"
    ],
    "expectedBytes": 3603068,
    "revision": "57b47096cc2de65189caeee3cefa2dab846829db76a853e9b66684242388fe50"
  },
  {
    "id": "art-chapter-8",
    "chapterId": "chapter-8",
    "title": "A Different Journey",
    "urls": [
      "assets/art/backgrounds/bg-adult-bedroom.webp",
      "assets/art/backgrounds/bg-airport-departure.webp",
      "assets/art/backgrounds/bg-holy-land-arrival.webp",
      "assets/art/characters/aleem-travel/hopeful.webp",
      "assets/art/characters/aleem-travel/tentative.webp",
      "assets/art/characters/aleem-travel/tired.webp",
      "assets/art/characters/imran/encouraging.webp",
      "assets/art/characters/imran/neutral.webp"
    ],
    "expectedBytes": 2129420,
    "revision": "1cf48f7d2b639024ae2afdd2942d8c8f608a65ee7092f7911a08521ec40b35ab"
  },
  {
    "id": "art-chapter-9",
    "chapterId": "chapter-9",
    "title": "The Same Girl",
    "urls": [
      "assets/art/backgrounds/bg-holy-land-arrival.webp",
      "assets/art/backgrounds/bg-jabal-nur-ascent.webp",
      "assets/art/backgrounds/bg-jabal-nur-rest.webp",
      "assets/art/backgrounds/bg-jabal-rahmah.webp",
      "assets/art/backgrounds/bg-makkah-courtyard.webp",
      "assets/art/backgrounds/bg-umrah-common-area.webp",
      "assets/art/cg/cg-umrah-jabal-nur.webp",
      "assets/art/cg/cg-umrah-jabal-rahmah.webp",
      "assets/art/characters/aleem-umrah/neutral.webp",
      "assets/art/characters/aleem-umrah/reflective.webp",
      "assets/art/characters/aleem-umrah/surprised.webp",
      "assets/art/characters/aleem-umrah/warm.webp",
      "assets/art/characters/imran/neutral.webp",
      "assets/art/characters/mariam/neutral.webp",
      "assets/art/characters/mariam/warm.webp",
      "assets/art/characters/nadiah-umrah/amused.webp",
      "assets/art/characters/nadiah-umrah/hesitant.webp",
      "assets/art/characters/nadiah-umrah/neutral.webp",
      "assets/art/characters/nadiah-umrah/warm.webp",
      "assets/art/characters/nadiah-umrah/wistful.webp",
      "assets/art/characters/yusuf/neutral.webp",
      "assets/art/characters/yusuf/warm.webp"
    ],
    "expectedBytes": 6036616,
    "revision": "5f4036a3a3f65af82d784cae63e334dbdd4f8d4b4ed175fc084d0c9dd6c69f23"
  },
  {
    "id": "art-chapter-10",
    "chapterId": "chapter-10",
    "title": "What I Could Finally Put Down",
    "urls": [
      "assets/art/backgrounds/bg-madinah-courtyard.webp",
      "assets/art/backgrounds/bg-nabawi-interior.webp",
      "assets/art/backgrounds/bg-umrah-common-area.webp",
      "assets/art/cg/cg-nabawi-release.webp",
      "assets/art/characters/aleem-umrah/neutral.webp",
      "assets/art/characters/aleem-umrah/reflective.webp",
      "assets/art/characters/aleem-umrah/relieved.webp",
      "assets/art/characters/aleem-umrah/resolved.webp",
      "assets/art/characters/aleem-umrah/warm.webp",
      "assets/art/characters/imran/encouraging.webp",
      "assets/art/characters/imran/neutral.webp",
      "assets/art/characters/mariam/encouraging.webp",
      "assets/art/characters/mariam/warm.webp",
      "assets/art/characters/nadiah-umrah/wistful.webp",
      "assets/art/characters/yusuf/neutral.webp",
      "assets/art/characters/yusuf/warm.webp"
    ],
    "expectedBytes": 4600218,
    "revision": "93359534b183d12510b34cebc02efbe146f530ca65f4b67c467105a27c8c9187"
  },
  {
    "id": "art-chapter-11",
    "chapterId": "chapter-11",
    "title": "A New Book",
    "urls": [
      "assets/art/backgrounds/bg-adult-bedroom.webp",
      "assets/art/backgrounds/bg-airport-departure.webp",
      "assets/art/backgrounds/bg-city-cafe.webp",
      "assets/art/backgrounds/bg-kallang-pier-sunset.webp",
      "assets/art/backgrounds/bg-kazakhstan-stay.webp",
      "assets/art/backgrounds/bg-parents-restaurant.webp",
      "assets/art/backgrounds/bg-umrah-common-area.webp",
      "assets/art/backgrounds/bg-waterfront-night.webp",
      "assets/art/backgrounds/bg-yakiniku-date.webp",
      "assets/art/cg/cg-kallang-confession.webp",
      "assets/art/cg/cg-parents-meeting.webp",
      "assets/art/characters/aleem-umrah/neutral.webp",
      "assets/art/characters/aleem-umrah/reflective.webp",
      "assets/art/characters/aleem-umrah/relieved.webp",
      "assets/art/characters/aleem-umrah/resolved.webp",
      "assets/art/characters/aleem-umrah/warm.webp",
      "assets/art/characters/aleem-work/neutral.webp",
      "assets/art/characters/aleem-work/smile.webp",
      "assets/art/characters/mariam/encouraging.webp",
      "assets/art/characters/nurulain/amused.webp",
      "assets/art/characters/nurulain/anxious.webp",
      "assets/art/characters/nurulain/curious.webp",
      "assets/art/characters/nurulain/guarded.webp",
      "assets/art/characters/nurulain/moved.webp",
      "assets/art/characters/nurulain/neutral.webp",
      "assets/art/characters/nurulain/warm.webp",
      "assets/art/characters/yusuf/neutral.webp",
      "assets/art/portrait/cg-kallang-confession.webp",
      "assets/art/portrait/cg-parents-meeting.webp"
    ],
    "expectedBytes": 6812014,
    "revision": "a6e1a17dd9d98c490ef651a3fd913ed1886786bce7f7eaf194bfbf31bb2ee783"
  },
  {
    "id": "art-epilogue",
    "chapterId": "epilogue",
    "title": "Still Being Written",
    "urls": [
      "assets/art/backgrounds/bg-city-cafe.webp",
      "assets/art/cg/cg-wedding-planning.webp",
      "assets/art/characters/aleem-umrah/warm.webp",
      "assets/art/characters/nurulain/amused.webp",
      "assets/art/portrait/cg-wedding-planning.webp"
    ],
    "expectedBytes": 1084580,
    "revision": "f03958bee3b15793e6752f8eadb6a6f8598cd2a226a121449d939520906c71de"
  }
] as const;
