import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { story } from '../src/story/index';
import { createArtAssetManifest } from '../src/story/artManifest';

const assets = createArtAssetManifest('/');
const files = new Map<string, { url: string; sha256: string; bytes: number }>();
for (const asset of assets) {
  for (const source of [asset.url, asset.mobile?.url].filter((url): url is string => Boolean(url))) {
    const url = source.replace(/^\//, '');
    if (files.has(url)) continue;
    if (!url.startsWith('assets/art/') || url.includes('..')) throw new Error(`Unsafe art path: ${url}`);
    const bytes = await readFile(resolve('public', url));
    files.set(url, { url, sha256: createHash('sha256').update(bytes).digest('hex'), bytes: bytes.length });
  }
}
const byId = new Map(assets.map((asset) => [asset.id, asset]));
const packs = story.chapters.map((chapter) => {
  const urls = new Set<string>();
  for (const node of story.nodes.filter((node) => node.chapterId === chapter.id)) {
    for (const id of [node.stage.backgroundId, ...node.stage.sprites.map((sprite) => sprite.assetId)]) {
      const asset = byId.get(id);
      if (!asset) throw new Error(`Missing artwork ${id} in ${node.id}`);
      urls.add(asset.url.replace(/^\//, ''));
      if (asset.mobile) urls.add(asset.mobile.url.replace(/^\//, ''));
    }
  }
  const entries = [...urls].sort().map((url) => files.get(url)!);
  return {
    id: `art-${chapter.id}`, chapterId: chapter.id, title: chapter.title,
    urls: entries.map((entry) => entry.url),
    expectedBytes: entries.reduce((total, entry) => total + entry.bytes, 0),
    revision: createHash('sha256').update(JSON.stringify(entries)).digest('hex'),
  };
});
const output = `// Generated by scripts/generate-art-content.ts. Do not edit.\nexport const generatedArtFiles = ${JSON.stringify([...files.values()].sort((a, b) => a.url.localeCompare(b.url)), null, 2)} as const;\n\nexport const generatedArtPacks = ${JSON.stringify(packs, null, 2)} as const;\n`;
const target = resolve('src/pwa/artContent.generated.ts');
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8').catch(() => '') !== output) throw new Error('Artwork content manifest is stale. Run npm run art:content.');
} else {
  await writeFile(target, output);
}
console.log(`Artwork content manifest: ${files.size} files, ${packs.length} chapter packs.`);
