import type { OfflinePackManifest, VoiceEntry } from "../engine/types";

/**
 * Generated by `npm run voices:import`.
 *
 * The checked-in development manifest is deliberately empty so the complete
 * story remains playable as subtitles while licensed performances are being
 * prepared. Do not hand-edit this file.
 */
export const generatedVoiceDisclosure: string | undefined = undefined;

export const generatedVoiceEntries = [] as const satisfies readonly VoiceEntry[];

export const generatedOfflinePackManifests =
  [] as const satisfies readonly OfflinePackManifest[];